### ISSUE TITLE
Crash at CustomTabsManager.java line 159 com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind

### ISSUE THREAD

**Issue by theli** [AzureAD/microsoft-authentication-library-for-android#1001]
My app is live and I am seeing crashes in Firebase Crashlytics. I happens on all Android versions. Version of the MSAL library 1.4.0.

Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@257e29a
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1671)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind(CustomTabsManager.java:159)
       at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.dispose(BrowserAuthorizationStrategy.java:166)
       at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.completeAuthorization(BrowserAuthorizationStrategy.java:143)
       at com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken(LocalMSALController.java:217)
       at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.notify(InteractiveTokenCommand.java:61)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.completeInteractive(CommandDispatcher.java:496)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$700(CommandDispatcher.java:60)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3$1.onReceive(CommandDispatcher.java:295)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by tirupatibg** [comment]
I am also getting the same error, not sure what causing the issue.        

Caused by: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@22b7133
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1729)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1870)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
        at com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind(CustomTabsManager.java:158)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.dispose(BrowserAuthorizationStrategy.java:162)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.completeAuthorization(BrowserAuthorizationStrategy.java:139)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken(LocalMSALController.java:205)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.notify(InteractiveTokenCommand.java:66)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.completeInteractive(CommandDispatcher.java:468)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.sendResult(AuthorizationFragment.java:385)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.completeAuthorizationInBrowserFlow(AuthorizationFragment.java:416)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.onResume(AuthorizationFragment.java:347)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
        at android.app.Activity.performResume(Activity.java:8149)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4344)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4386) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7478) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by shahzaibj** [comment]
Hi @theli , @tirupatibg Do you still have this issue on the latest release of MSAL v1.6.0? 
https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.6.0

**Comment by iambmelt** [comment]
Closing due to inactivity

**Comment by eduardothiesen** [comment]
I'm experiencing the same issue on MSAL v2.2.0

**Comment by MarceloEsser** [comment]
> I'm experiencing the same issue on MSAL v2.2.0
> 
> Fatal Exception: java.lang.IllegalArgumentException Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@3c4b6b9
> 
> com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind (CustomTabsManager.java:164) com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.dispose (BrowserAuthorizationStrategy.java:182) com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.completeAuthorization (BrowserAuthorizationStrategy.java:157) com.microsoft.identity.common.internal.controllers.LocalMSALController.completeAcquireToken (LocalMSALController.java:258) com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.notify (InteractiveTokenCommand.java:77) com.microsoft.identity.common.internal.controllers.CommandDispatcher.completeInteractive (CommandDispatcher.java:608) com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1100 (CommandDispatcher.java:83) com.microsoft.identity.common.internal.controllers.CommandDispatcher$4$1.onReceive (CommandDispatcher.java:565)

Same here on redmi 8.

**Comment by LTMezzari** [comment]
> I'm experiencing the same issue on MSAL v2.2.0
> 
> Fatal Exception: java.lang.IllegalArgumentException Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@3c4b6b9
> 
> com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind (CustomTabsManager.java:164) com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.dispose (BrowserAuthorizationStrategy.java:182) com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.completeAuthorization (BrowserAuthorizationStrategy.java:157) com.microsoft.identity.common.internal.controllers.LocalMSALController.completeAcquireToken (LocalMSALController.java:258) com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.notify (InteractiveTokenCommand.java:77) com.microsoft.identity.common.internal.controllers.CommandDispatcher.completeInteractive (CommandDispatcher.java:608) com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1100 (CommandDispatcher.java:83) com.microsoft.identity.common.internal.controllers.CommandDispatcher$4$1.onReceive (CommandDispatcher.java:565)

Same issue happening on Samsung Galaxy S8 and others.
