### ISSUE TITLE
Library performs disk IO on main thread

### ISSUE THREAD

**Issue by MariusVolkhart** [AzureAD/microsoft-authentication-library-for-android#1041]
**Describe the bug**
Calls to `ISingleAccountPublicClientApplication#acquireTokenSilent(String[] scopes, String authority)` result in a disk write on the main thread.

When the task to retrieve the authentication result completes, it goes to save the account information by calling `SingleAccountPublicClientApplication#persistCurrentAccount(...)`. However, the `CommandDispatcher` schedules the callback on the main thread (~`CommandDispatcher#L113`).

**Smartphone (please complete the following information):**
 - Device: Emulator
 - Android Version: 29
 - MSAL Version: 1.5.1

**Stacktrace**
```java
2020-05-11 21:43:16.933 6412-6412/? D/StrictMode: StrictMode policy violation; ~duration=1 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1512)
        at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:338)
        at libcore.io.ForwardingOs.remove(ForwardingOs.java:186)
        at android.app.ActivityThread$AndroidOs.remove(ActivityThread.java:7287)
        at java.io.UnixFileSystem.delete(UnixFileSystem.java:331)
        at java.io.File.delete(File.java:1037)
        at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:808)
        at android.app.SharedPreferencesImpl.access$900(SharedPreferencesImpl.java:55)
        at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:647)
        at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:666)
        at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:55)
        at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:585)
        at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.putString(SharedPreferencesFileManager.java:142)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.persistCurrentAccount(SingleAccountPublicClientApplication.java:497)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.access$100(SingleAccountPublicClientApplication.java:73)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onTaskCompleted(SingleAccountPublicClientApplication.java:333)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onTaskCompleted(SingleAccountPublicClientApplication.java:325)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:212)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by kreedula** [comment]
Thanks @MariusVolkhart for reporting this, we will prioritize looking into this.

**Comment by tanmaymanolkar1** [comment]
Hi @MariusVolkhart Thank you for bringing this issue to our notice, we will be rolling the fix in the next MSAL release. In the meantime you can try relaxing the strictmode to allow diskwrites in the persistCurrentAccount() function.
