### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference

### ISSUE THREAD

**Issue by evenlan1990** [AzureAD/microsoft-authentication-library-for-android#1062]
**Describe the bug**
1.open demo app,enter the select account page after call acquireToken(SingleAccountMode),and take a screenshot.
2.Press the home button,back to desktop.
3.Then click demo app again;select a account;click "continue";it will crash

**Smartphone (please complete the following information):**
 - Device: samsung SM-T510 
 - Android Version: API 29
 - MSAL Version:1.2.0

**Stacktrace**
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.driver.wonder.qa/com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3125)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7100)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
at android.content.ComponentName.<init>(ComponentName.java:131)
at android.content.Intent.<init>(Intent.java:6751)
at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.createCustomTabResponseIntent(AuthorizationFragment.java:185)
at com.microsoft.identity.client.BrowserTabActivity.onCreate(BrowserTabActivity.java:67)
at android.app.Activity.performCreate(Activity.java:7327)
at android.app.Activity.performCreate(Activity.java:7318)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3105)

**To Reproduce**

If related to user experience, use the format:
1.open demo app,enter the select account page after call acquireToken(SingleAccountMode),and take a screenshot.
2.Press the home button,back to desktop.
3.Then click demo app again;select a account;click "continue";it will crash

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**

**Actual Behavior**

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by AdamBJohnsonx** [comment]
@evenlan1990 :

This looks like it was fixed in https://github.com/AzureAD/microsoft-authentication-library-common-for-android/commit/ee2de54749e3c726d85faf9685f5fde9e0d0313d#diff-82b884777e04d64a8841a09ea33cb3f7 as part of MSAL 1.5.0 https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.5.0 and appears to be the same issue as https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/942

If you see a similar issue in our newer versions,  please let us know.

Thanks!
Adam
