### ISSUE TITLE
com.microsoft.identity.client.BrowserTabActivity declared in the manifest (exported activity) can used by any other apps

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-android#1123]
**Describe the bug**
Our app is in production. We have used MSAL for Conditional Access.
Following Activity has been declared in our Manifest as suggested by MSAL:

"com.microsoft.identity.client.BrowserTabActivity"

Any third-party app can start this activity with no permission. If a malicious app constantly start the browser activity, our app will stop work.

**Smartphone (please complete the following information):**
 - Device: All devices
 - Android Version: All version
 - Browser All tested browsers
 - MSAL Version 1.5.+

**Stacktrace**
2020-07-31 00:09:58.117 30869-30869/xx.xx.xxxxx E/: main | UNCAUGHT EXCEPTION | 
    java.lang.RuntimeException: Unable to start activity ComponentInfo{xx.xx.xxxxx/com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
    
    Caused by: Unable to start activity ComponentInfo{xx.xx.xxxx/com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3396)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: 
     Caused by: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:132)
        at android.content.Intent.<init>(Intent.java:6465)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.createCustomTabResponseIntent(AuthorizationFragment.java:197)
        at com.microsoft.identity.client.BrowserTabActivity.onCreate(BrowserTabActivity.java:67)
        at android.app.Activity.performCreate(Activity.java:7783)
        at android.app.Activity.performCreate(Activity.java:7772)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3235)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3396)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)

**To Reproduce**
This can be done via drozer or adb.

1. Install and start drozer agent on a phone
Start the exported activity by running:
dz>run app.activity.start --component xx.xxx.xxx.xx.xxx (package name)
com.microsoft.identity.client.BrowserTabActivity --data-uri msauth://xx.xxx.xxx.xx.xxx  (package name an hash key)
This causes the app uses the MSAL crash.

2. Adb equivalent command is:

adb shell am start -n xx.xxx.xxx.xx.xxx/com.microsoft.identity.client.BrowserTabActivity -d msauth://xx.xxx.xxx.xx.xxx

**Expected behavior**
Handle the "com.microsoft.identity.client.BrowserTabActivity" in a better way. So that app wont get crash.

**Actual Behavior**
BrowserTab activity can be invoke by any third party app(malicious app). This is not the accepted behaviour.

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by kreedula** [comment]
@vramasam : Thanks for reporting this, we use `BrowserTabActivity` to get the result from system browser which is launched to handle the auth request.Of course  `BrowserTabActivity`  will be only invoked for a specific intent filter if the url starts with "msauth://<your_package_name>/<your_signature>". Given that this information is not a secret, I understand this can be used to launch the activity from `adb` or any other app.

But however this is a standard way to handle deep links per [Android documentation](https://developer.android.com/training/app-links/deep-linking)

Also, please refer the documentation here for [`exported`](https://developer.android.com/guide/topics/manifest/service-element.html#exported) , Given we use an intent filter here ,the default value of `exported` is `true` even if we don't set it, so that other apps can invoke this Activity for that intent. 

At least from the preliminary analysis, we are following the approach which Android recommends and am not sure if we can do any better her.  However, I will add this to our backlog and we will try to take a deeper look into this again.

Also, please let us know if you have any suggestions to make this better

**Comment by kreedula** [comment]
Also, can you please update to the latest version of [MSAL (1.6.0) ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.6.0)and try out the scenerio? 

The null pointer issue is already fixed , PR here : https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/845

**Comment by vramasam** [comment]
HI @kreedula 
Used the MSAL 1.6.0 version. It's not crashing instead its showing the following message "Unable to complete the authorization as there is no interactive call in progress. This can be due to closing the app while the authentication in progress" .

Is this expected behaviour. Can you please confirm on this.

**Comment by kreedula** [comment]
@vramasam : Are you seeing this issue only with your environment of simulating a malicious app?

For the regular use case , are you seeing this behavior too ?

**Comment by iambmelt** [comment]
Closing due to inactivity
