### ISSUE TITLE
Cannot refresh token in bg: MsalClientException: There is no signed in account

### ISSUE THREAD

**Issue by azakharenka1** [AzureAD/microsoft-authentication-library-for-android#1150]
**App cannot acquire token silently in bg - quite ofter MsalClientException: There is no signed in account**

**Smartphone**
 - Device: all
 - Android Version: all
 - Browser Chrome
 - MSAL Version 1.6.0

**Stacktrace**
com.microsoft.identity.client.exception.MsalClientException: There is no signed in account.
	at com.microsoft.identity.client.SingleAccountPublicClientApplication.acquireTokenSilentAsync(SingleAccountPublicClientApplication.java:605)
	at pl.predica.nofo.common.repository.AuthorizationRepository$tryToAcquireTokenSilent$1$1.accept(AuthorizationRepository.kt:56)
	at pl.predica.nofo.common.repository.AuthorizationRepository$tryToAcquireTokenSilent$1$1.accept(AuthorizationRepository.kt:30)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
	at pl.predica.nofo.common.azureb2c.AzureB2CConfig$createApplication$1$1.onCreated(AzureB2CConfig.kt:44)
	at com.microsoft.identity.client.PublicClientApplication$11.onCreated(PublicClientApplication.java:978)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:906)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:894)
	at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:216)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**To Reproduce**
Sing in into app
Set access token expiration time to some short value e.g 10 / 20 min
Hide app, turn off screen

Schedule work with workmanager to acquire token ( acquireTokenSilentAsync ) at token expiration time. I tried to do it before -in this case msal still sends us prev token.

**Expected behavior**
Token refreshes correctly 

**Actual Behavior**
A lot of MsalClientException: There is no signed in account in prod

Config:

`{
  "client_id": "***",
  "authorization_user_agent": "WEBVIEW",
  "redirect_uri": "msald***://auth",
  "broker_redirect_uri_registered": false,
  "shared_device_mode_supported": false,
  "account_mode": "SINGLE",
  "logging": {
    "pii_enabled": false,
    "log_level": "VERBOSE",
    "logcat_enabled": true
  },
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "https://***.onmicrosoft.com/B2C_1A_Signup_Signin_With_Kmsi"
    }
  ]
}`

**Comment by azakharenka1** [comment]
Found local issue, closing for now

**Comment by z3ntu** [comment]
@azakharenka1 What was the issue on your end? I'm also seeing `com.microsoft.identity.client.exception.MsalClientException: There is no signed in account.` errors frequently.

https://xkcd.com/979/
