### ISSUE TITLE
AADB2C Callbacks fail via "MsalClientException: Attempt to invoke virtual method on null object reference"

### ISSUE THREAD

**Issue by andres-j** [AzureAD/microsoft-authentication-library-for-android#1162]
**Describe the bug**
I have an empty compose app and am attempting to implement AADB2C auth via MSAL. After configuring the app and the azure portal I am able to launch into a browser, log in and return to the app. Unfortunately the callback consistently reports an error as described by the stack trace below. I am able to test the flow in azure and examine the token in jwt.ms, the app is registered and the credentials are valid but the app still fails. 

**Smartphone (please complete the following information):**
 - Device: Pixel 2, LG G5
 - Android Version: 8.0
 - Browser Chrome
 - MSAL Version 2.0.+

**Stacktrace**
2020-09-22 17:19:25.632 9965-9965/com.companyname.employeeapp W/System.err: com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
2020-09-22 17:19:25.632 9965-9965/com.companyname.employeeapp W/System.err:     at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
2020-09-22 17:19:25.634 9965-9965/com.companyname.employeeapp W/System.err:     at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.save(MsalOAuth2TokenCache.java:282)
2020-09-22 17:19:25.634 9965-9965/com.companyname.employeeapp W/System.err:     at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.saveAndLoadAggregatedAccountData(MsalOAuth2TokenCache.java:336)
2020-09-22 17:19:25.634 9965-9965/com.companyname.employeeapp W/System.err:     at com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:171)

I would expect the callback to be a success - but it is not and I am unable to find a reason why. Any help would be appreciated!

**Comment by iambmelt** [comment]
@andres-j Can you confirm that your policy is issuing a refresh token? That seems to be where most folks run into this issue

**Comment by andres-j** [comment]
Thanks for your quick reply! On your tip I did some investigating and was able to resolve the issue. **Indeed I was not getting a refresh token** In the Azure portal, my app registration did not have any api access beyond 'default' openid and offline_access scopes and so no additional access/refresh tokens were being obtained. **Granting the app an API scope in addition to the default scopes** was necessary to fix the issue.

Curious -  Any reason why adding a custom scope from a custom api is _required_ in this way? 

One last note: I had "openid" and "offline_access" scopes in my code being passed to the param constructor. I had to add the custom scope _and_ delete the two default scopes (openid/offline) for everything to work correctly.

**Comment by iambmelt** [comment]
> Curious - Any reason why adding a custom scope from a custom api is _required_ in this way?

@andres-j Happy to hear you're unblocked! On the client-side, we require a refresh token to make the `acquireTokenSilent` APIs function. As to why a custom scope is required on the service-end to enable this? That I can't speak to; though this feedback may be valuable for the folks on [UserVoice](https://feedback.azure.com/forums/169401-azure-active-directory/category/160596-b2c) or as feedback for [B2C's documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview).
