### ISSUE TITLE
acquireTokenSilentAsync often fails with "MsalClientException: There is no signed in account."

### ISSUE THREAD

**Issue by z3ntu** [AzureAD/microsoft-authentication-library-for-android#1189]
**Describe the bug**

Hi, I'm frequently hitting errors during token refresh in a production app due to reasons I cannot explain.

**Smartphone:**
 - Device: OnePlus 6t (and others)
 - Android Version: Android 10 (and others)
 - Browser Chrome
 - MSAL 2.0.1

**Stacktrace**
This log is with the msal logger set up (`Logger.getInstance().setExternalLogger`)

```
2020-10-13 08:16:31.074 15025-15233/com.mypackage I/MyAccountManager: MyAccountManager.getNewAccessToken()
2020-10-13 08:16:31.096 15025-15233/com.mypackage I/MyAccountManager: MyAccountManager.getAccessToken()
2020-10-13 08:16:31.108 15025-15025/com.mypackage V/AuthenticatorService: AuthenticatorService created
2020-10-13 08:16:31.111 15025-15025/com.mypackage V/AuthenticatorService: onBind Intent { act=android.accounts.AccountAuthenticator cmp=com.mypackage/com.myapp.serviceapp.MSALAuthenticatorService }
2020-10-13 08:16:31.334 15025-15268/com.mypackage I/MSALAuthenticatorService$MSALAuthCallback: MSALAuthCallback: authenticate()
2020-10-13 08:16:31.370 15025-15297/com.mypackage V/AuthorityDeserializer:deserialize:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Type: B2C Android 29
2020-10-13 08:16:31.371 15025-15297/com.mypackage V/PublicClientApplicationConfigurationFactory:loadDefaultConfiguration:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Loading default configuration Android 29
2020-10-13 08:16:31.375 15025-15297/com.mypackage V/AuthorityDeserializer:deserialize:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Type: AAD Android 29
2020-10-13 08:16:31.377 15025-15297/com.mypackage V/AzureActiveDirectoryAudienceDeserializer:deserialize:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Type: AzureADandPersonalMicrosoftAccount Android 29
2020-10-13 08:16:31.379 15025-15297/com.mypackage V/MsalOAuth2TokenCache:create:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Creating MsalOAuth2TokenCache Android 29
2020-10-13 08:16:31.379 15025-15297/com.mypackage V/CacheKeyValueDelegate:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Init: CacheKeyValueDelegate Android 29
2020-10-13 08:16:31.380 15025-15297/com.mypackage V/SharedPreferencesFileManager:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Init with storage helper:  SharedPreferencesFileManager Android 29
2020-10-13 08:16:31.382 15025-15297/com.mypackage V/SharedPreferencesAccountCredentialCache:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Init: SharedPreferencesAccountCredentialCache Android 29
2020-10-13 08:16:31.382 15025-15297/com.mypackage V/MsalOAuth2TokenCache:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Init: MsalOAuth2TokenCache Android 29
    
    [          1602569791.383 15025:15297 V/com.microsoft.identity.client.internal.controllers.MSALControllerFactory:brokerEligible [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Eligible to call broker? [false]. App does not ask for Broker or the authority is not AAD authority. Android 29
2020-10-13 08:16:31.383 15025-15297/com.mypackage V/CommandDispatcher:submitSilent:  [2020-10-13 06:16:31 - {"thread_id":"1160","correlation_id":"UNSET"}] Beginning execution of silent command. Android 29
2020-10-13 08:16:31.383 15025-15297/com.mypackage V/CommandDispatcher:initializeDiagnosticContext:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] Initialized new DiagnosticContext Android 29
2020-10-13 08:16:31.384 15025-15297/com.mypackage V/EstsTelemetry:createLastRequestTelemetryCache:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] Creating Last Request Telemetry Cache Android 29
2020-10-13 08:16:31.384 15025-15297/com.mypackage V/SharedPreferencesFileManager:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] Init: SharedPreferencesFileManager Android 29
2020-10-13 08:16:31.385 15025-15297/com.mypackage V/SharedPreferencesLastRequestTelemetryCache:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] Init: SharedPreferencesLastRequestTelemetryCache Android 29
2020-10-13 08:16:31.385 15025-15297/com.mypackage V/EstsTelemetry:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] Ests Telemetry cache has been initialized properly. Android 29
2020-10-13 08:16:31.385 15025-15297/com.mypackage W/LocalMSALController:getDeviceMode:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] LocalMSALController is not eligible to use the broker. Do not check sharedDevice mode and return false immediately. Android 29
2020-10-13 08:16:31.386 15025-15297/com.mypackage W/Telemetry:  [2020-10-13 06:16:31 - {"thread_id":"1186","correlation_id":"d29f6977-a3a4-4304-adfb-dfdcdd0c82a8"}] Telemetry is disabled because the Telemetry context or configuration is null Android 29
2020-10-13 08:16:31.390 15025-15297/com.mypackage V/PublicClientApplication:  [2020-10-13 06:16:31 - {"thread_id":"2","correlation_id":"UNSET"}] Telemetry configuration is null. Telemetry is disabled. Android 29
2020-10-13 08:16:31.395 15025-15297/com.mypackage W/Telemetry:  [2020-10-13 06:16:31 - {"thread_id":"2","correlation_id":"UNSET"}] Telemetry is disabled because the Telemetry context or configuration is null Android 29
2020-10-13 08:16:31.397 15025-15297/com.mypackage W/PublicClientApplicationConfiguration:  [2020-10-13 06:16:31 - {"thread_id":"2","correlation_id":"UNSET"}] The app is still using legacy MSAL redirect uri. Switch to MSAL local auth.  For brokered auth, the redirect URI is expected to conform to 'msauth://<authority>/.*' where the authority in that uri is the package name of the app. This package name is listed as 'applicationId' in the build.gradle file. Android 29
2020-10-13 08:16:31.397 15025-15297/com.mypackage W/PublicClientApplicationConfiguration:  [2020-10-13 06:16:31 - {"thread_id":"2","correlation_id":"UNSET"}] The app is still using legacy MSAL redirect uri. Switch to MSAL local auth.  For brokered auth, the redirect URI is expected to conform to 'msauth://<authority>/.*' where the authority in that uri is the package name of the app. This package name is listed as 'applicationId' in the build.gradle file. Android 29
2020-10-13 08:16:31.401 15025-15268/com.mypackage E/MSALAuthenticatorService$MSALAuthCallback$authenticate$token: Failed to refresh token from MSAL
    com.microsoft.identity.client.exception.MsalClientException: There is no signed in account.
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.acquireTokenSilentAsync(SingleAccountPublicClientApplication.java:625)
        at com.myapp.login.AzureClient$getTokenSilent$1.subscribe(AzureClient.kt:87)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:46)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5317)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5317)
        at io.reactivex.rxjava3.core.Maybe.blockingGet(Maybe.java:2846)
        at com.myapp.serviceapp.MSALAuthenticatorService$MSALAuthCallback.authenticate(MSALAuthenticatorService.kt:43)
        at com.davidmedenjak.auth.OAuthAuthenticator$CallbackListener.refresh(OAuthAuthenticator.java:253)
        at com.davidmedenjak.auth.OAuthAuthenticator$CallbackListener.access$100(OAuthAuthenticator.java:239)
        at com.davidmedenjak.auth.OAuthAuthenticator.getAuthToken(OAuthAuthenticator.java:125)
        at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:246)
        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:282)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)
2020-10-13 08:16:31.412 15025-15233/com.mypackage E/MyAccountManager: getAccessToken error
    java.io.IOException: com.microsoft.identity.client.exception.MsalClientException: There is no signed in account.
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2537)
        at android.accounts.AccountManager.access$700(AccountManager.java:162)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2388)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:107)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)
```

**To Reproduce**
Unknown, I haven't recognized a pattern yet except that it happens quite often.

**Expected behavior**
The token refresh should succeed and return back a valid token.

**Actual Behavior**
The token refresh errors out with "MsalClientException: There is no signed in account."

**Comment by z3ntu** [comment]
I've come to realize that I do something wrong, I'll update this when I know more. This has to do with registering an account with AccountManager to share the login between two apps

**Comment by z3ntu** [comment]
So in my case two apps were sharing the same login via Android AccountManager, so token refresh happened through the API and is handled by one app only. The mistake I made is that the login was handled in the app where the login was requested and not in the one designated by the authenticator as the app providing the account. This meant that if install App A and then App B, App A gets used for auth. But when we logged into App B (which then saved the auth things in the app data of App B) everything seemed to work fine until token refresh when MSAL of App A would be asked to refresh but it failed. 
So instead of launching the LoginActivity for the current app, we now call `AccountManager.get(this).addAccount(accountType, authTokenType, null, null, this, null, null)`) to make the correct app handle the login.

**Comment by rusmichal** [comment]
@z3ntu I think I have similar problem, User has logged in the azure account in Android system account manager and he uses the same account to login in the app. I don't understand how the token is refreshing. I don't get it how could I handle the login properly. I assume that some of users don't add azure account to android account manager.
