### ISSUE TITLE
Fatal Exception: com.microsoft.identity.client.exception.MsalClientException: No refresh token was found. 

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#1200]
**Describe the bug**
Hi! Recently we've been simulating a scenario where the apps recovers from a process killed by the system. In some devices we're getting this crash when opening the app:

**Smartphone:**
 - Device: moto g(7) plus
 - Android Version: 10
 - MSAL Version: 1.5.4

**Stacktrace**
`Fatal Exception: com.microsoft.identity.client.exception.MsalClientException: No refresh token was found. 
       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
       at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1673)
       at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1664)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:209)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)`

`Caused by com.microsoft.identity.common.exception.ClientException: No refresh token was found. 
       at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:319)
       at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:75)
       at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:41)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:166)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200(CommandDispatcher.java:65)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:126)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by iambmelt** [comment]
Thanks for reporting this issue, @xyzwilliamxyz -- this looks to be addressed by recent changes I submitted in the following PR:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1098

Additionally, I have follow-up item to improve that fix [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/1100).

I'd love to know a bit more about how you simulating this error, and under circumstances you're able to replicate it today. Further, once our next release is available, it would be great if you see if you continue to face this issue

**Comment by xyzwilliamxyz** [comment]
Hi @iambmelt , we tried to upgrade a few days ago but we were facing this same issue where links stopped working (https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1170) and had to go back.

One of the ways to simulate the process can be like this: https://stackoverflow.com/a/18695974 . Not sure you will be able to reproduce though, it seems kinda very specific to some devices from what we've seen so far.

**Comment by xyzwilliamxyz** [comment]
@iambmelt I tried using an artifact from **msal dev branch** and the issue persists. 

One additional detail to this is that this issue seems to be highly related to (https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1201), in our tests out of 8 crashes from this scenario, 6 crashes were said to be this one from MsalUtils.

They happened on android 10 on devices **moto g 7 plus** and **moto g8 plus**. I tried on android 10 emulator and a device with android 9 and it works. So maybe it may be related to android version from specific vendors.

Also, unrelated but related, in crashlytics production we have a lot of this "MsalUtils" error in all android versions, but they are logged as **non-fatal** :thinking:

**Comment by iambmelt** [comment]
@xyzwilliamxyz I posted an update in #1201 -- this appears to be an calling pattern issue where the supplied account is null; if you could verify your input to this function I would expect that crash to go away. I suspect that to be a separate issue?

**Comment by xyzwilliamxyz** [comment]
@iambmelt 

> this appears to be an calling pattern issue where the supplied account is null;

I'm not sure if the account is null. If it's null, shouldn't MSAL be responsible for it since it manages the access to b2c?

> if you could verify your input to this function I would expect that crash to go away.

I'll add some logs here to check the account values and will return with the results.

**Comment by iambmelt** [comment]
#1201 is a calling pattern issue where a `null` parameter is passed to MSAL; it is a separate issue from the one in #1200 (this ticket).

For _this issue_ #1200, it's unclear to me what could cause it under normal execution circumstances but will update this thread with any updates

**Comment by xyzwilliamxyz** [comment]
@iambmelt It was indeed an issue in the app. In the scenario from when the app recovers from the "killed process state", it was unexpectedly not passing through the setup before using MSAL and was logging out at the same time, and for some reason showing those weird false positive fatal exceptions on firebase crashlytics. So, I think we're good to cancel this.
