### ISSUE TITLE
Fatal Exception: com.microsoft.identity.client.exception.MsalArgumentException: account cannot be null or empty

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#1201]
**Describe the bug**
Hi! Recently we've been simulating a scenario where the apps recovers from a process killed by the system. In some devices we're getting this crash when opening the app:

**Smartphone (please complete the following information):**
 - Device: moto g(7) plus
 - Android Version: 10
 - MSAL Version 1.5.4

**Stacktrace**
`
Fatal Exception: com.microsoft.identity.client.exception.MsalArgumentException: account cannot be null or empty
       at com.microsoft.identity.client.internal.MsalUtils.validateNonNullArg(MsalUtils.java:135)
       at com.microsoft.identity.client.PublicClientApplication.validateAcquireTokenSilentParameters(PublicClientApplication.java:1304)
       at com.microsoft.identity.client.PublicClientApplication$13.run(PublicClientApplication.java:1410)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
`

**Comment by iambmelt** [comment]
Hi @xyzwilliamxyz -- Sorry to hear you're running into this; this appears to be a calling pattern issue where the supplied `IAccount` for `acquireTokenSilent` is `null` -- this check is performed by this validation layer [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/af06a8c687129921d017ce5f7163e0820f8ea970/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L1338-L1347).

My suggestion would be to check that the account != null prior to passing it to this API, if there is any question as to the object's contents or initialization state

**Comment by iambmelt** [comment]
Closing due to inactivity
