### ISSUE TITLE
MsalArgumentException: Authority passed to silent parameters does not match with the cloud associated to the account.

### ISSUE THREAD

**Issue by sabans-dev** [AzureAD/microsoft-authentication-library-for-android#1249]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.
The app is currently being tested with PPE env. The issue is that the call to get the token for MAM service is failing with the mentioned error. The auth call for the app resources is passing and hence able to login into the application but MAM registration failed. 
This starting working after I added the authroity_url to the auth_config file as "_"authority_url": "https://login.windows-ppe.net/common"_" without which I was getting the error as AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '95de633a-083e-42f5-b444-a4295d8e9314' which the Identity team told me is because ther eis not authority url mentioned. With this however the issue at hand is the MAM service call that uses MSAL to get the token is failing as it uses the same authority mentioned in the auth_config (which was not there earlier and hence did not use it and passed) and giving the mentioned error. There seems to be some problem with the way MSAL is getting the token for app resources and that for the MAM service.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel, OnePlus 6, etc] Samsung Note 20
 - Android Version: [e.g. API Level, Build Number] 11
 - Browser [e.g. Chrome, Edge] Chome
 - MSAL Version 2.0.4

**Stacktrace**
If a crash occurs, include the stacktrace.
2020-12-17 19:04:10.930 15625-18998/com.microsoft.whiteboard E/AuthenticationCallback: Failed to get token for MAM Service
    com.microsoft.identity.client.exception.MsalArgumentException: Authority passed to silent parameters does not match with the cloud associated to the account.
        at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:59)
        at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1747)
        at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1738)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:340)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1100(CommandDispatcher.java:74)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:322)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8154)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: com.microsoft.identity.common.exception.ArgumentException: Authority passed to silent parameters does not match with the cloud associated to the account.
        at com.microsoft.identity.common.internal.commands.parameters.SilentTokenCommandParameters.validate(SilentTokenCommandParameters.java:56)
        at com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:282)
        at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:76)
        at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:42)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:279)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200(CommandDispatcher.java:74)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$1.run(CommandDispatcher.java:191)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**To Reproduce**

If related to user experience, use the format:

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
The auth call for the resources passed using the authority url and also the MAM service token call should pass as it was without the authority url.

**Actual Behavior**
A description of what actually happened.

**Screenshots**

**Additional context**
Auth_config.json file:
{
  "client_id": "----------------------------------------------",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "-----------------------------------------------------------------------------------",
  "authorities": [
    {
      "type": "AAD",
      "authority_url": "https://login.windows-ppe.net/common",
      "audience": {
        "type": "AzureADMultipleOrgs"
      }
    }
  ]
}

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by sabans-dev** [comment]
This was fixed in a discussion with the team. The missing property for authorities was the rootcause.
