### ISSUE TITLE
Setting DayNight theme to night breaks authentication

### ISSUE THREAD

**Issue by jonodav** [AzureAD/microsoft-authentication-library-for-android#1269]
Hi there, I've been trying to get MSAL working in an app and noticed it was crashing at night time. The cause was the daynight theme being set to night with:

`AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);`

Authentication is done using the following code from the MS Graph Android example app:

In MainActivity:
```
AuthenticationHelper.getInstance(getApplicationContext(),
                new IAuthenticationHelperCreatedListener() {
                    @Override
                    public void onCreated(AuthenticationHelper authHelper) {
                        mAuthHelper = authHelper;
                        if (!mIsSignedIn) {
                            doSilentSignIn(false);
                        } else {
                            hideProgressBar();
                        }
                    }

                    @Override
                    public void onError(MsalException exception) {
                        Log.e("AUTH", "Error creating auth helper", exception);
                    }
                });
```
In AuthenticationHelper:
```
private AuthenticationHelper(Context ctx, final IAuthenticationHelperCreatedListener listener) {
        PublicClientApplication.createSingleAccountPublicClientApplication(ctx, R.raw.msal_config,
                new IPublicClientApplication.ISingleAccountApplicationCreatedListener() {
                    @Override
                    public void onCreated(ISingleAccountPublicClientApplication application) {
                        mPCA = application;
                        listener.onCreated(INSTANCE);
                    }

                    @Override
                    public void onError(MsalException exception) {
                        Log.e("AUTHHELPER", "Error creating MSAL application", exception);
                        listener.onError(exception);
                    }
                });
    }
```
It appears that mPCA is never properly initialized and results in null object references when sign on is attempted:
```
public void acquireTokenSilently(AuthenticationCallback callback) {
        // Get the authority from MSAL config
        String authority = mPCA.getConfiguration().getDefaultAuthority().getAuthorityURL().toString();
        mPCA.acquireTokenSilentAsync(mScopes, authority, callback);
    }
``` 

**Devices**
 - Device: Asus Nexus 7 (2013), OnePlus 6
 - Android Version: API 23, MO30X, API 28
 - MSAL Versions 1.4.0, 2.0.4, and 2.0.5

**Stacktrace**
```
01-07 09:22:04.007 24851-24851/com.sample.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.app, PID: 24851
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.app/com.sample.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'com.microsoft.identity.client.PublicClientApplicationConfiguration com.microsoft.identity.client.ISingleAccountPublicClientApplication.getConfiguration()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
        at android.app.ActivityThread.-wrap15(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.microsoft.identity.client.PublicClientApplicationConfiguration com.microsoft.identity.client.ISingleAccountPublicClientApplication.getConfiguration()' on a null object reference
        at com.sample.app.AuthenticationHelper.acquireTokenSilently(AuthenticationHelper.java:63)
        at com.sample.app.MainActivity.doSilentSignIn(MainActivity.java:338)
        at com.sample.app.MainActivity.access$200(MainActivity.java:53)
        at com.sample.app.MainActivity$1.onCreated(MainActivity.java:186)
        at com.sample.app.AuthenticationHelper.getInstance(AuthenticationHelper.java:42)
        at com.sample.app.MainActivity.onCreate(MainActivity.java:180)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
        at android.app.ActivityThread.-wrap15(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `
```

**To Reproduce**
Add `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);` to the onCreate, and preferably set the AppTheme to DayNight. Setting default night mode to `MODE_NIGHT_NO` does not result in the error.
This can be reproduced in the example app for Microsoft Graph on android [here](https://github.com/microsoftgraph/msgraph-training-android).

**Expected behavior**
The application should silently sign on on launch.

**Actual Behavior**
The application crashes on attempting to sign on.

Thank you!

**Comment by iambmelt** [comment]
Hi @jonodav -- this appears to be an issue with the MSGraph sample. You will need to follow-up with the author of that sample to troubleshoot this issue. If it is later discovered that this is indeed a bug in the MSAL-Android library, please feel free open another issue here and we can investigate.

I have created a new issue for you here, for the owner of that sample to follow-up:
https://github.com/microsoftgraph/msgraph-training-android/issues/46
