### ISSUE TITLE
Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference

### ISSUE THREAD

**Issue by HristoStoevZ** [AzureAD/microsoft-authentication-library-for-android#1289]
it is similar to 
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/563

My B2C AD supports only "Local account" as Identity provider.

Using msal:2.+
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.getExpiresOn(MicrosoftStsAccountCredentialAdapter.java:231)
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:78)
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:45)
      at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.save(MsalOAuth2TokenCache.java:112)
      ...
```
And here is my raw config file:
```json
xxxxxxxxxxxxxxxxandroid:host="xxxxxxxxxxxxxxxxx"{
    "client_id" : "XXX",
    "authorization_user_agent" : "DEFAULT",
    "redirect_uri" : "msauth://xxxxxxxxxxxxxxxxxxx/KEY_HASH",
    "authorities" : [
      {
        "type": "B2C",
        "authority_url": "https://zuhlkeb2c.b2clogin.com/tfp/zuhlkeb2c.onmicrosoft.com/B2C_1_SignUpOrSignIn/",
        "default": true
      }
    ]
  }
```
where XXX is client id.

It seems like the field `expires_in` in token response happens to be null, so the `getExpiresOn()` method in MicrosoftStsAccountCredentialAdapter throws this null pointer exception. But since we have exp in the token, it is not necessary to calculate the expiration data, instead exp can be returned converted to device time zone (if conversion is necessary )  

payload data: 
```json
{
  "exp": 1611740751,
  "nbf": 1611737211,
  "ver": "1.0",
  "iss": "https://zuhlkeb2c.b2clogin.com/d1308f65-xxxxxxxxxxxx-7e3421bcbd41/v2.0/",
  "sub": "77506d5b-xxxxxxxxxxx-0d7339e15dc2",
  "aud": "3137db67-xxxxxxxxxxxx-f5520a19befc",
  "iat": 1611737211,
  "auth_time": 1611737209,
  "oid": "77506d5b-xxxxxxxxxxxx-0d7339e15dc2",
  "city": "Sofia",
  "country": "Bulgaria",
  "name": "Hristo",
  "given_name": "Hristo",
  "family_name": "Stoev",
  "emails": [
    "xxxxxxxxx"
  ],
  "tfp": "B2C_1_SignUpOrSignIn"
}
```

**Comment by iambmelt** [comment]
@HristoStoevZ This is a known limitation; please see the documentation provided in https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1291 and configure your policies accordingly

/cc @hamiltonha FYI ^^
