### ISSUE TITLE
Msal getAccounts Exception 

### ISSUE THREAD

**Issue by horus12** [AzureAD/microsoft-authentication-library-for-android#1290]
I have captured in my project this Execution inside Msal lib:
Someone could help-me ?

Fatal Exception: java.lang.IllegalStateException: method: getAccounts may not be called from main thread.
       at com.microsoft.identity.client.internal.MsalUtils.throwOnMainThread(MsalUtils.java:512)
       at com.microsoft.identity.client.MultipleAccountPublicClientApplication.getAccounts(MultipleAccountPublicClientApplication.java:149)
       at com.abinbev.android.sdk.oauth.b2c.MSALBusiness$start$2.onCreated(MSALBusiness.kt:44)
       at com.microsoft.identity.client.PublicClientApplication$10.onCreated(PublicClientApplication.java:957)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:928)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:914)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:346)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1200(CommandDispatcher.java:74)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:325)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by iambmelt** [comment]
@horus12 The Exception contains the error: `getAccounts may not be called from main thread.` You will need to call this method either through the [async API](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/27375e034fdb40005946f5d1c4a2ae03569248f0/msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java#L45-L50) or from a background thread
