### ISSUE TITLE
Application is getting crash in BrowserTabActivity, when user is enabling/disabling Samsung Dex while using the application.

### ISSUE THREAD

**Issue by rmaramreddy** [AzureAD/microsoft-authentication-library-for-android#1297]
Application is getting crash in BrowserTabActivity, when user is enabling/disabling Samsung Dex while using the application.

When my app(uses MSAL2.+) is in background enabling/disabling Samsung DEX feature setting is leading to crash with below stack trace.

 - Device: Samsung Dex
 - Android Version: Android 9,10,11
 - Browser : Chrome
 - MSAL Version - 2.+

**Stacktrace**
com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.notify(int, int, android.content.Intent)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4657)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4690)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.notify(int, int, android.content.Intent)' on a null object reference
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher.completeInteractive(Unknown Source:2)
        at com.microsoft.identity.client.BrowserTabActivity.onResume(Unknown Source:44)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:8111)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4647)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4690) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 

1. Go to device settings enable Samsung DEX feature.
2. Launch MSAL configured app(My app uses MSAL) on Samsung 10 device.
3. Minimize the app and  go to device settings and disable/enable DEX feature.
4. Relaunch the minimized app and observed app is crashing when MSAL Auth page is loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/24888392/106601569-d0035d00-6581-11eb-8392-e8f4aa757e06.png)
![msalcrash](https://user-images.githubusercontent.com/24888392/106601684-f1644900-6581-11eb-8cde-eb235f9b3401.jpg)

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by iambmelt** [comment]
@hamiltonha Assigning to you, as this is a feature request to add support for Samsung Dex. This functionality is not presently supported
