### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by pedrofarnetaniabi** [AzureAD/microsoft-authentication-library-for-android#1314]
**Describe the bug**
We're having this exception reported by crashlytics since MSAL version 2.0.4 (currently we are using MSAL version 2.0.5 that also has this problem).

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A30s (and many others including other brands)
 - Android Version: 10
 - MSAL Version: 2.0.4 and 2.0.5

**Stacktrace**
> 
       Fatal Exception: java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:496)
       at android.net.Uri$StringUri.<init>(Uri.java:486)
       at android.net.Uri.parse(Uri.java:458)
       at com.microsoft.identity.client.internal.MsalUtils.hasCustomTabRedirectActivity(MsalUtils.java:249)
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:522)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1046)
       at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1029)
       at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:64)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:928)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:914)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:346)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1200(CommandDispatcher.java:74)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:325)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by iambmelt** [comment]
Closed via #1324 and #1327
