### ISSUE TITLE
WebViewAuthorizationFragment.java line 128

### ISSUE THREAD

**Issue by thgmaziero-ciandt** [AzureAD/microsoft-authentication-library-for-android#1336]
**Describe the bug**
We're receiving some crashs that seems to related to not supporting some webview version.

**Smartphone (please complete the following information):**
 - Device: Galaxy J7 Prime
 - Android Version: 8.1.0
 - MSAL Version: 2.0.5

**Stacktrace**
```
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 438907200 actual: 353811000
       at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:253)
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:353)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2530)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2590)
       at android.view.View.<init>(View.java:4868)
       at android.view.View.<init>(View.java:5054)
       at android.view.ViewGroup.<init>(ViewGroup.java:597)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:643)
       at android.webkit.WebView.<init>(WebView.java:588)
       at android.webkit.WebView.<init>(WebView.java:571)
       at android.webkit.WebView.<init>(WebView.java:558)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.microsoft.identity.common.internal.providers.oauth2.WebViewAuthorizationFragment.onCreateView(WebViewAuthorizationFragment.java:128)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
       at com.microsoft.identity.common.internal.ui.DualScreenActivity.onStart(DualScreenActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1342)
       at android.app.Activity.performStart(Activity.java:7278)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`
```

**Comment by iambmelt** [comment]
Hi @thgmaziero-ciandt 

This is not an MSAL issue, but a device configuration issue. Specifically, there's mismatch of the WebView binary version that is installed versus the one expected by WebKit's `WebViewFactory`. This [validation is performed by AOSP](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/WebViewFactory.java#310), not MSAL, and [isn't actually part of the Android public API](https://developer.android.com/s/results?q=MissingWebViewPackageException). I would expect this crash to occur on this device in each app that creates a `WebView`, whether MSAL is used or not.

Device has installed:
- Version: 70.0.3538.110 (353811000) (2018)

Device expects:
- Version: 89.0.4389.72 (438907200) (2021)

Users experiencing this crash need to go to the app store and update the WebView, MSAL cannot update this component nor bypass this validation. As this error would be user/device specific, I would expect any crash numbers you see around this issue to be low, likely a handful of users running on older devices. For devices experiencing this issue, they are likely to experience the crash repeatedly, as reopening the app or restarting the device is unlikely to resolve the version mismatch issue.

Note, [a similar version of this crash may occur if the `WebView` is updated while an app is running](https://bugs.chromium.org/p/chromium/issues/detail?id=506369) -- AOSP had previously marked this issue as transient/wontfix

Because this error is not part of the [public API](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/WebViewFactory.java#103), and MSAL cannot catch it directly, the logic we may need to add to catch this issue could be a bit roundabout. 

Before exploring [potential techniques to detect this issue](https://github.com/gree/unity-webview/issues/406#issuecomment-475942207), can you provide a bit more information about how many unique users you have experiencing this crash and on which Android versions/devices?

**Comment by thgmaziero-ciandt** [comment]
Yes, I understand that, but crashing the app doesn't seems to be good experience for user. Wouldn't be better if and was thrown back to the app so we can show a proper error explaining that the user has to update the webview?

Thanks

**Comment by iambmelt** [comment]
> Yes, I understand that, but crashing the app doesn't seems to be good experience for user. Wouldn't be better if and was thrown back to the app so we can show a proper error explaining that the user has to update the webview?
> 
> Thanks

See below question @thgmaziero-ciandt 

>Before exploring [potential techniques to detect this issue](https://github.com/gree/unity-webview/issues/406#issuecomment-475942207), **can you provide a bit more information about how many unique users you have experiencing this crash and on which Android versions/devices?**

**Comment by thgmaziero-ciandt** [comment]
The crashed happened with a just a couple a users, but those had like 50 crashs each, as I said crash is bad experience cause it does't tells the user what they need to do to fix it.
Your suggestion is to do this webview check on our side instead of the library doing it?

**Comment by iambmelt** [comment]
@thgmaziero-ciandt If resolving this issue for these two users is a high-priority item for you/team in the near term, this may be an item you want to address at the app-level, versus MSAL addressing as part of the auth library.

This being an open source library, you are of course welcome to submit a Pull Request and it would be evaluated for inclusion in a future release. Should you elect to go this route, please include the relevant crash stats/affected devices so we can make an informed decision as to whether this is a code change we want to ship to all users

Issues _external_ to our library (such as subsystem bugs, bad device configurations, or bugs pertaining to rooted/custom ROMs) we appraise from a impact/risk/benefit standpoint and prioritize accordingly -- when many users are likely to face an issue, it moves to a higher-pri and we assess the right fix, workaround, or [in this case] how to catch/surface the error. When an issue is unlikely to affect a substantial number of users or is found in older, unsupported versions of Android, those issues tend to be prioritized lower or, in some cases, marked `wontfix`. Any specific metrics around impact, devices, users, etc you can provide can paint a clearer picture for us as to whether or not this is a change we'd want to consider including

**Comment by iambmelt** [comment]
Closing this issue as 'External'
