### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by evenlan1990** [AzureAD/microsoft-authentication-library-for-android#1372]
**Describe the bug**
Our application has been frequently exposed recently about `SDK:com.microsoft.identity.client.exception.MsalServiceException: net::ERR_NAME_NOT_RESOLVED`

**Smartphone (please complete the following information):**
 - Device: samsung Galaxy Tab A (SM-T510)
 - Android Version: 10
 - Browser 
 - MSAL Version:com.microsoft.identity.client:msal:1.6.0

**Stacktrace**
```java
com.microsoft.identity.client.exception.MsalServiceException: net::ERR_NAME_NOT_RESOLVED
    at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
    at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:339)
    at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:325)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:213)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8107)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.
```

**Comment by iambmelt** [comment]
@evenlan1990 This is not an error message from MSAL: this is a DNS error being returned by the browser (typically Chrome). I suggest reviewing the failing hostname for correctness, as well as the DNS/network configuration of your failing clients.

Please note that MSAL 1.6.0 is out of support as this library has a 'fix-forward' model: our latest releases can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases). Please consider updating to the latest version and reopening this issue if you are able to determine repro steps for this issue that are not specific to your application

**Comment by evenlan1990** [comment]
> @evenlan1990 This is not an error message from MSAL: this is a DNS error being returned by the browser (typically Chrome). I suggest reviewing the failing hostname for correctness, as well as the DNS/network configuration of your failing clients.
> 
> Please note that MSAL 1.6.0 is out of support as this library has a 'fix-forward' model: our latest releases can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases). Please consider updating to the latest version and reopening this issue if you are able to determine repro steps for this issue that are not specific to your application

Thansk!I will update to latest version test it.
