### ISSUE TITLE
Connection is not available to refresh token (v 2.0.10)

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-for-android#1381]
Hi, I have seen issues #998 and set SingleAccountPublicClientApplication.getConfiguration().setPowerOptCheckEnabled(false) in my config but I still get the following exception when I try to refresh token from background service.

`getTokenOrRequestLogin -> exception = com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token
at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:350)
at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:336)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:435)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:80)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:417)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8462)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
05-03 07:31:02.475 D/CLOUD2_OneDriveSigningHelper(21545): Caused by: com.microsoft.identity.common.exception.ClientException: Connection is not available to refresh token
at com.microsoft.identity.common.adal.internal.net.HttpWebRequest.throwIfNetworkNotAvailable(HttpWebRequest.java:219)
at com.microsoft.identity.common.internal.controllers.BaseController.performSilentTokenRequest(BaseController.java:476)
at com.microsoft.identity.common.internal.controllers.BaseController.renewAccessToken(BaseController.java:320)
at com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:332)
at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:76)
at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:42)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:369)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$100(CommandDispatcher.java:80)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher$1.run(CommandDispatcher.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)`

**Comment by shoatman** [comment]
Which version of MSAL are you using?

**Comment by NLLAPPS** [comment]
2.0.10

**Comment by shoatman** [comment]
We moved off a deprecated API for network check recently and identified an issue with the new implementation making that API too sensitive.  I'll update you shortly on when you can expect a new release that fixes this.  

@tanmaymanolkar1, @AdamBJohnsonx , @iambmelt, @gitaumoses4 - FYI

**Comment by ryandegruyter** [comment]
We have the same issue with the following version:
![image](https://user-images.githubusercontent.com/12190633/117662375-c3555d00-b19f-11eb-9bcd-e3e9173c7b78.png)

Users can not log in, does not happen all the time...

**Comment by AdamBJohnsonx** [comment]
Version MSAL version 2.0.12 was released last week to address this problem.  To be clear, this error will happen from time to time because it is a result of the network not being available.

**Comment by ryandegruyter** [comment]
Thank you for the swift response. We made a new build last week Friday, so our build server might not have picked up the 2.0.12 version. We will try and make a new build.

**Comment by abdurahmanadilovic** [comment]
is there a way to force token refresh? It seems very strange to me that msal is refusing to refresh the token when it "thinks" there is no connection because its very difficult to actually determine that.  We noticed a lot of 401 responses from our backend because of this issue, connection is there, requests are going through to the backend but msal is stuck in no connection state, refusing to refresh the token. 

Is it possible to pass in a parameter to ignore network connectivity checks?
