### ISSUE TITLE
We have trouble to signing in.

### ISSUE THREAD

**Issue by rusmichal** [AzureAD/microsoft-authentication-library-for-android#1400]
**Describe the bug**
Starting from 5 May we observed increasing number of following exceptions while logging from our Android Application on Galaxy Note 10 devices.

AADSTS50194: Application 'xxx-aaa-vbbb-ccc-xxxx'(XX) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

We are not sure how to reproduce it because it doesn't happen on all our customers, it just happens on smaller group of users.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10
 - Android Version: API 30
 - Browser Chrome
 - MSAL Version: 2.0.10

**Stacktrace**

```
Caused by com.microsoft.identity.common.exception.ServiceException: AADSTS50194: Application 'XXX'(XXX) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
Timestamp: 2021-05-14 12:39:43Z
       at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getServiceException(MsalBrokerResultAdapter.java:441)
       at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getBaseExceptionFromExceptionType(MsalBrokerResultAdapter.java:286)
       at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getBaseExceptionFromBundle(MsalBrokerResultAdapter.java:199)
       at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getAcquireTokenResultFromResultBundle(MsalBrokerResultAdapter.java:554)
       at com.microsoft.identity.common.internal.controllers.BrokerMsalController.acquireToken(BrokerMsalController.java:266)
       at com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:67)
       at com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:39)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:369)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$100(CommandDispatcher.java:80)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$4.run(CommandDispatcher.java:563)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
```
```
Caused by com.microsoft.identity.client.exception.MsalServiceException: AADSTS50194: Application 'xxxx'(XXX) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
Timestamp: 2021-05-14 12:39:43Z
       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:350)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:336)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:435)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:80)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:417)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
```

**To Reproduce**

Not sure how to reproduce that.

Config file:
```
{
  "client_id": "xxx",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "URL",
  "account_mode": "SINGLE",
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "tenand_uuid-xxx-xxx-xxxxxxxx"
      },
      "default": true
    }
  ]
}

```

**Expected behavior**
User can login to the single tenant app using his account.

**Actual Behavior**
Library return exception because it claims that the user belongs to different tenants that the organization.  

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by cgrathwohl** [comment]
We're experiencing the same problem as of 11 May. It might be related to the new Microsoft Authenticator app update?
In our case there is a (temporary?) workaround by selecting "Use another account" and just reentering the account informations.

**Comment by rusmichal** [comment]
We found out that if we add `broker_redirect_uri_registered: false` to config file. then it is gonna skip Authenticator app and user can login again with the credentials. please try it.

**Comment by GHTaylor** [comment]
I have also been experiencing this with ADAL.

**Comment by miqm** [comment]
If worth adding - devices had also Intune installed and were enrolled as corporate-owned with company account set-up.

**Comment by ryandegruyter** [comment]
We've have also started experiencing this issue.

**Comment by miqm** [comment]
> Both users with authenticator installed or without.
> They will be redirected to select the account in the company portal app

according to docs (https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#when-a-broker-is-installed) first installed broker is used.

**Comment by rpdome** [comment]
We've identified the issue - this is an issue in our code that got shipped with the latest Authentcator/Company Portal.

The fix currently being rolled out in both apps.

Sorry for any inconvenience this may have caused!
-Dome

**Comment by GHTaylor** [comment]
> We've identified the issue - this is an issue in our code that got shipped with the latest Authentcator/Company Portal.
> 
> The fix currently being rolled out in both apps.
> 
> Sorry for any inconvenience this may have caused!
> -Dome

Thank you for the response. When you say now, do you mean right now? Or is there somewhere we can track progress? Thank you

**Comment by GHTaylor** [comment]
> We've identified the issue - this is an issue in our code that got shipped with the latest Authentcator/Company Portal.
> 
> The fix currently being rolled out in both apps.
> 
> Sorry for any inconvenience this may have caused!
> -Dome

Thank you for the information, Dome. Is there anywhere we can track the status of these apps being updated? Also, is there an official page that acknowledges the issue? We are in an enterprise environment and stakeholders are looking for more messaging/information on this. Thank you!

**Comment by ryandegruyter** [comment]
Same here, 8000 enterprise users. Last week, there was also a bug in the Android common library, which caused many authentication errors...

**Comment by rpdome** [comment]
@GHTaylor, @ryandegruyter We don't have any other pages for the issue (It's tracked internally), but I can keep you posted for the rollout status in this thread.

Currently, the fix is being rolled out with Microsoft Authenticator. It's currently 50% in BETA ring as we speak. We're aiming to hit 100% prod by 05-22.

Company Portal is planning to go to 100% BETA by tomorrow (05-19).

**Comment by ryandegruyter** [comment]
Ok thanks for the update!

**Comment by rpdome** [comment]
Authenticator is rolling out to 1% Production today.

**Comment by rpdome** [comment]
Authenticator is rolling out to 20% production today.
Company Portal is 0.5% production.

Both are already 100% Beta.

**Comment by AlbusTrevor** [comment]
are there anymore updates to this please? Still having users not being able to log in (Company Portal)

**Comment by rpdome** [comment]
As of Today (May 24)

Authenticator is rolling out to 100% production.
Company Portal is rolling out to 5% production.

**Comment by rpdome** [comment]
As of Today (May 26)
Company Portal is rolling out to 15% production  (5.0.5155.0)

**Comment by rpdome** [comment]
As of Today (May 26)
Company Portal is rolling out to 100% production  (5.0.5155.0)
