### ISSUE TITLE
AADSTS900384: JWT token failed signature validation with Azure US Government

### ISSUE THREAD

**Issue by christianrowlands** [AzureAD/microsoft-authentication-library-for-android#1454]
I am writing an Android app and setting it up to use authentication against an Azure AD tenant running in Azure US Government Cloud. I followed the guide [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android) to setup AD in the Azure portal and configure my Android application. I was able to get it to work in regular Azure (login.microsoftonline.com) but was unable to get it to work against login.microsoftonline.us. I followed the guide [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-national-cloud?tabs=java) to use MSAL against the US Government cloud, which basically says to update the authority to login.microsoftonline.us, but that did not fix the issue.

The error occurs when calling the MSAL method `com.microsoft.identity.client.ISingleAccountPublicClientApplication#acquireTokenSilentAsync`. I am passing in "https://login.microsoftonline.us/a89....." as the authority to that method, which should be correct for the US Government cloud.

 - Device: Pixel 5
 - Android Version: API Level 30
 - MSAL Version: I have tried 2.0.6, 2.0.8, and 2.0.12

**Stacktrace**
```2021-06-30 14:19:08.549 14344-14406/com.my.app W/MicrosoftStsOAuth2Strategy:TokenResult:  [2021-06-30 18:19:08 - {"thread_id":"1011","correlation_id":"0d3ddc50-45d6-4f86-aba4-7d123d48ad46","x-client-Ver":"1.5.9","x-client-SKU":"MSAL.Android"}] Failure Result Android 30
2021-06-30 14:19:08.549 14344-14406/com.my.app  W/MicrosoftStsOAuth2Strategy:TokenResult:  [2021-06-30 18:19:08 - {"thread_id":"1011","correlation_id":"0d3ddc50-45d6-4f86-aba4-7d123d48ad46","x-client-Ver":"1.5.9","x-client-SKU":"MSAL.Android"}] Error: invalid_request Android 30
2021-06-30 14:19:08.552 14344-14406/com.my.app  W/BaseController:TokenResult:  [2021-06-30 18:19:08 - {"thread_id":"1011","correlation_id":"0d3ddc50-45d6-4f86-aba4-7d123d48ad46","x-client-Ver":"1.5.9","x-client-SKU":"MSAL.Android"}] Failure Result Android 30
2021-06-30 14:19:08.552 14344-14406/com.my.app  W/BaseController:TokenResult:  [2021-06-30 18:19:08 - {"thread_id":"1011","correlation_id":"0d3ddc50-45d6-4f86-aba4-7d123d48ad46","x-client-Ver":"1.5.9","x-client-SKU":"MSAL.Android"}] Error: invalid_request Android 30
2021-06-30 14:19:08.558 14344-14344/com.my.app  D/LoginFragment: Authentication failed
    com.microsoft.identity.client.exception.MsalServiceException: AADSTS900384: JWT token failed signature validation [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: '0E...77', Found key 'Start=12/21/2020 00:00:00, End=12/21/2025 00:00:00']
    Trace ID: 0a528741-7054-4eb8-aab3-f62ae413f700
    Correlation ID: 0d3ddc50-45d6-4f86-aba4-7d123d48ad46
    Timestamp: 2021-06-30 18:19:08Z
        at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:350)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:336)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:348)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1100(CommandDispatcher.java:74)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:330)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**To Reproduce**
I am worried that this is a configuration issue on my end. I am guessing I have setup either the AD App Registration in the Azure Portal incorrectly, or I have setup the Android app incorrectly. But since everything was working great prior to switching to Azure US Government cloud, I am not sure what else to check.

**Expected behavior**
I am expecting to get back a valid JWT token from AD so that the Android app can use it to authenticate against my back end server.

**Actual Behavior**
I get the exception and errors shown above.

**Additional context**
I have seen this error show up in a variety of Google search results, but nothing seems to be providing a resolution, so I am wondering if this is a bug in MSAL itself. However, my guess is that I am just doing something wrong but I wanted to submit this just incase something is wrong with using the MSAL against US Government Cloud.

**Comment by christianrowlands** [comment]
I tried version 1.5.5 of MSAL and I received a different error. It could be that the old library version does not work, but I thought the error might help debug the problem. It seems interesting to me that it is saying "Invalid national Cloud ID (0) is specified". As far as I can tell, I am specifying the cloud correctly in the authority URL, so I am not sure where else to set it.

```
2021-07-06 11:24:56.190 20776-20776/com.my.app D/LoginFragment: Authentication failed
    com.microsoft.identity.client.exception.MsalUiRequiredException: AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (0) is specified.
    Trace ID: c7273d6e-8b39-482e-bf01-a920f0a03c00
    Correlation ID: 8a501c67-2428-47d4-ab82-d2502e8bc769
    Timestamp: 2021-07-06 15:24:57Z
        at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:64)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:339)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:325)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:209)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by shoatman** [comment]
Are you using an account from the US Gov cloud to sign in?  Possible to share you MSAL configuration file contents here?

**Comment by shoatman** [comment]
If you're app is intended to work with multiple clouds, US Gov and public for example.  You may want to take a look at the following: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#multiple_clouds_supported

**Comment by christianrowlands** [comment]
Thank you for getting back to me. I actually just came across that option and it fixed the problem I happened to come across it when I was hitting breakpoints in MSAL for Android and noticed that login.microsoftonline.com was still being used even though I was specifying login.microsoftonline.us. It turns out that the call was not failing on aquireTokenSilentAsync, but it was failing on the actual sign in call. The Sign in call only takes the config file so everything needs to be specified in there. It was my understanding that since the tenant and client were both in that file that the MSAL could figure out that the endpoint was US Government... but that was a bad assumption.

In finding the `multiple_clouds_supported` option I also found the `authority_url` option for the json config file. However, I did not find it on the Microsoft Docs page you mentioned, but instead found it in the source code [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/34809d80927cb509cd59d0a36b72d2c98a636fd6/common/src/main/java/com/microsoft/identity/common/internal/authorities/Authority.java#L65). Once I tried adding that to my config json file everything worked as expected. 

Given all of this, I have a couple thoughts to help the next developer that comes along.

1. I was using the `auth_config_single_account.json` file that was provided to me my by the Azure Portal after I registered the Android App in Active Directory. The one addition I had to make was `"account_mode": "SINGLE",`, but that was clear in the Android tutorial so there were no problems there. Given that I was logged into the Azure Portal at `portal.azure.us` I would suspect that it would be straightforward to add support to auto-populate the json config file with the `authority_url` field with the proper URL (cloud specific URL followed by the tenant ID). 
2. It would be good to update [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration) with the `authority_url` information. It is mentioned on the page, but the description of it is `Required only when type=B2C. Specifies the authority URL or policy your app should use`. This description seems inaccurate since the type I am using is AAD. I had actually read this a week ago, and because of that description I assumed I did not need to set the authority_url.
3. It would also be good to update the [MSAL National Cloud documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-national-cloud?tabs=java). Specifically for the java documentation there is information for setting the `authority` in JSON, but when I tried that I did not know where to set it, and if I try to use it in the `authorities` array it does not work, instead it needs to be `authority_url` as defined in the GitHub link from above. Maybe the tag is correct for other setups, but it lead me astray and was also confusing where the information was supposed to go.
4. Finally, my last suggestion is for MSAL for Android. It might have been nice to be able to pass in the AUTHORITY into the [signIn](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/1afba9735d9201f35b9f10aa5adfc2428153e683/msal/src/main/java/com/microsoft/identity/client/SingleAccountPublicClientApplication.java#L234) method. I looked for an overload of the signIn method specifically because the aquireTokenSilentAsync method allowed for the AUTHORITY to be passed as a parameter. Even now, I find it strange that you can specify it for one, and not the other. Maybe it is because you want to be able to get a token for different authorities, but being new to AD and MSAL, it is not clear to me all the expectations. To me it feels like either both should take it as a parameter, or neither should. And along those lines, a better error message than the signature is invalid would go a long way to save future developers from the same debugging sessions I did.

Thanks for listening to me rant about my suggestions and let me know you want anymore feedback.
