### ISSUE TITLE
Crash in AuthenticationActivity when uiBuilder class is not initialized

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/microsoft-authentication-library-for-android#149]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.microsoft.identity.client.UiEvent$Builder com.microsoft.identity.client.UiEvent$Builder.setUserDidCancel()' on a null object reference
                                                                                                   at com.microsoft.identity.client.AuthenticationActivity.cancelRequest(AuthenticationActivity.java:210)
                                                                                                   at com.microsoft.identity.client.AuthenticationActivity.onResume(AuthenticationActivity.java:173)
                                                                                                   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                                                   at android.app.Activity.performResume(Activity.java:6347)
                                                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
                                                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152) 
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2499) 
                                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by weijjia** [comment]
closed with PR #152
