### ISSUE TITLE
Crash in DevUtil MainActivity when Do Not Keep Activities is turned on

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#150]
```java
FATAL EXCEPTION: main
                                                                                    Process: com.microsoft.identity.client.sample, PID: 3332
                                                                                    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                                        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                                                        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                                                        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
                                                                                        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
                                                                                        at com.microsoft.identity.client.sample.MainActivity.attachFragment(MainActivity.java:222)
                                                                                        at com.microsoft.identity.client.sample.MainActivity.onNavigationItemSelected(MainActivity.java:192)
                                                                                        at com.microsoft.identity.client.sample.MainActivity$2.onSuccess(MainActivity.java:317)
                                                                                        at com.microsoft.identity.client.PublicClientApplication$1.onSuccess(PublicClientApplication.java:668)
                                                                                        at com.microsoft.identity.client.BaseRequest$2.run(BaseRequest.java:278)
                                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by iambmelt** [comment]
Closing as a no-op. No plans to try and support DNKA
