### ISSUE TITLE
Failed to load generated key pair from keystore with Android 7.1.2

### ISSUE THREAD

**Issue by luethib** [AzureAD/microsoft-authentication-library-for-android#1566]
**Failed to load generated key pair from keystore with Android 7.1.2**
When using our app on a normal android Cellphone (e.g. samsung device with Android 8.0.0) it works fine. However when we try to login on an Android device with Android 7.1.2, without screen lock and without google services (unfortunately we cannot change that), we get an error. The error occures during login, the login page is shown without problems and the credentials can be entered, but after pushing the Sign in Button we get the error: 'com.microsoft.identity.client.exception.MsalClientException: Failed to load generated key pair from keystore' or more precisely 'KeyStoreException: Invalid key blob'.

Best hint i found so far is [this](https://stackoverflow.com/questions/36488219/android-security-keystoreexception-invalid-key-blob), so eventually has something to do with the fact that this device has not screen lock implemented.
Do you have any experience if devices without screen lock support your library?

**DJI Smart Controller:**
 - Device: DJI Smart Controller
 - Android Version: 7.1.2
 - Browser: DJI Explorer, Brave
 - MSAL Version: 2.2.1

**Stacktrace**
```
KeyStoreException: Invalid key blob
    at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:224)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
...
(23 additional frame(s) were not displayed)

UnrecoverableKeyException: Failed to obtain information about private key
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
...
(22 additional frame(s) were not displayed)

ProviderException: Failed to load generated key pair from keystore
    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:518)
    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
    at com.microsoft.identity.common.adal.internal.cache.StorageHelper.generateKeyPairFromAndroidKeyStore(StorageHelper.java:747)
    at com.microsoft.identity.common.adal.internal.cache.StorageHelper.saveKeyStoreEncryptedKey(StorageHelper.java:662)
...
(20 additional frame(s) were not displayed)

ClientException: Failed to load generated key pair from keystore
    at com.microsoft.identity.common.internal.controllers.ExceptionAdapter.baseExceptionFromException(ExceptionAdapter.java:274)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:381)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$000(CommandDispatcher.java:83)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher$4.run(CommandDispatcher.java:579)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
...
(2 additional frame(s) were not displayed)

MsalClientException: Failed to load generated key pair from keystore
    at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
    at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1903)
    at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1894)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:442)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$800(CommandDispatcher.java:83)
...
(8 additional frame(s) were not displayed)
User

ID:	6092a2f8-e74f-44b2-935b-e84fc6b2b8e5
Message

com.microsoft.identity.client.exception.MsalClientException: Failed to load generated key pair from keystore
```

**To Reproduce**
Could only be reproduced on this one device, which is crucial for our application.

1. Login
2. Enter Credentials
3. Click on 'Sign in'

**Expected behavior**
Login the user and store keys in keystore

**Actual Behavior**
Login the user, error when loading the generated key pair from keystore

**Comment by Dommerjon** [comment]
I see exactly the same behavior on our DJI Enterprise Smart Controller (Android: 7.1.2), but not a connected Android 11 Phone on MSAL: 3.0.2

**Comment by roja-d** [comment]
This issue still reproducing in new MSAL versions also . Im using and android panel device

**Comment by flavioperucchi** [comment]
Facing the exact same problem.

Device: DJI Smart Controller
Android Version: 7.1.2

**Comment by flavioperucchi** [comment]
I managed to get over it.

Call this method in `onCreate` of your entry Activity. 
This will store a encrypted key based on the Hardware ID of your device.
It is definitely not that secure as a key store, but good enough in my case.

```   private fun generateSecretKey() {
        try {
            if (AuthenticationSettings.INSTANCE.secretKeyData == null) {
                // use same key for tests
                val keyFactory = SecretKeyFactory.getInstance("PBEWithSHA256And256BitAES-CBC-BC")
                val androidId = Settings.Secure.getString(contentResolver, Settings.Secure.ANDROID_ID)
                val temporaryKey = keyFactory.generateSecret(
                    PBEKeySpec(
                        androidId.toCharArray(), androidId.toByteArray(charset("UTF-8")), 100, 256
                    )
                )
                val secretKey: SecretKey = SecretKeySpec(temporaryKey.encoded, "AES")
                AuthenticationSettings.INSTANCE.setSecretKey(secretKey.encoded)
            }
        } catch (ex: Exception) {
            logE("Fail to generate secret key", ex)
        }
    }
```

**Comment by Dommerjon** [comment]
> I managed to get over it.
> 
> Call this method in `onCreate` of your entry Activity. This will store a encrypted key based on the Hardware ID of your device. It is definitely not that secure as a key store, but good enough in my case.
> 
> ```
>         try {
>             if (AuthenticationSettings.INSTANCE.secretKeyData == null) {
>                 // use same key for tests
>                 val keyFactory = SecretKeyFactory.getInstance("PBEWithSHA256And256BitAES-CBC-BC")
>                 val androidId = Settings.Secure.getString(contentResolver, Settings.Secure.ANDROID_ID)
>                 val temporaryKey = keyFactory.generateSecret(
>                     PBEKeySpec(
>                         androidId.toCharArray(), androidId.toByteArray(charset("UTF-8")), 100, 256
>                     )
>                 )
>                 val secretKey: SecretKey = SecretKeySpec(temporaryKey.encoded, "AES")
>                 AuthenticationSettings.INSTANCE.setSecretKey(secretKey.encoded)
>             }
>         } catch (ex: Exception) {
>             logE("Fail to generate secret key", ex)
>         }
>     }
> ```

It works!! Thanks, much appreciated 👍
