### ISSUE TITLE
MsalClientException: No cached accounts found for the supplied homeAccountId and clientId

### ISSUE THREAD

**Issue by mtapiero** [AzureAD/microsoft-authentication-library-for-android#1567]
When requesting a silent token on a custom B2C authorization flow, the MSAL library throws the exception: `No cached accounts found for the supplied homeAccountId and clientId`
Requesting an interactive token works well.

The DotNetCore and Javascript implementations work.
The error occurs when calling the IMultipleAccountPublicClientApplication.acquireTokenSilentAsync method

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: API 30
 - MSAL Version: 2+

**Stacktrace**
com.microsoft.identity.client.exception.MsalClientException: No cached accounts found for the supplied homeAccountId and clientId
    at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
    at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1903)
    at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1894)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:442)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$800(CommandDispatcher.java:83)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:424)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**To Reproduce**
I'm using this sample app to try the authorization flow:
https://github.com/Azure-Samples/ms-identity-android-java

**Expected behavior**
The token is refreshed and stored in the token cache

**Actual Behavior**
An error is thrown

**Additional context**
We have asked Microsoft support, but haven't received an answer so far.
We've been riddled with this bug for a couple of weeks now, and we have no idea how to proceed.
My assumption is, there is a specific setting on the B2C config that is breaking the MSAL Android implementation, but we cannot find anything.

What can be the possible reasons this error occurs?
Can someone share a clue on what to look for?

**Comment by fernando-aguiar-cit** [comment]
Hi @mtapiero Did you find any solution for this?
I'm having the same issue here that only the silent renew token is not working.
I tried everything with my code and the sample code for this.
