### ISSUE TITLE
getting DRS request failed.

### ISSUE THREAD

**Issue by ashu2451990** [AzureAD/microsoft-authentication-library-for-android#1596]
I am getting below error in  acquireToken Interactive callback . Can anyone help me for the same?  

==> getAuthorizationInteractiveCallback onError exception: com.microsoft.identity.client.exception.MsalClientException: DRS request failed
2022-02-21 23:54:57.563 7446-7446/E/App: Authentication error
    com.microsoft.identity.client.exception.MsalClientException: DRS request failed
        at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:350)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:336)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:442)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$800(CommandDispatcher.java:83)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:424)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.microsoft.identity.common.exception.ClientException: DRS request failed
        at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getBaseExceptionFromExceptionType(MsalBrokerResultAdapter.java:294)
        at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getBaseExceptionFromBundle(MsalBrokerResultAdapter.java:193)
        at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getAcquireTokenResultFromResultBundle(MsalBrokerResultAdapter.java:548)
        at com.microsoft.identity.common.internal.controllers.BrokerMsalController.acquireToken(BrokerMsalController.java:268)
        at com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:67)
        at com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:39)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:376)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$000(CommandDispatcher.java:83)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$4.run(CommandDispatcher.java:580)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-02-21 23:54:57.563 7446-7446/ E/App: Authentication error com.microsoft.identity.client.exception.MsalClientException: DRS request failed

**Comment by paulokagiri** [comment]
@ashu2451990 could you kindly share some more information on how your application is configured?
