### ISSUE TITLE
Android MSAL Login failed incase if My app is already Auto enrollment successful using Company portal app

### ISSUE THREAD

**Issue by shanmugpriyan306** [AzureAD/microsoft-authentication-library-for-android#1737]
**We are migrating our authentication of Azure from ADAL to MSAL. Our app support Intune feature.

We are facing login failure during MSAL login, if the app is already automatically enrolled using Company portal app or open-in work flow from the other apps is already Intune Enrollment successfully completed.**

Our app is live in production with ADAL + Intune library integration. Right we have plan to move with MSAL + Intune[currently in development phase]

**Smartphone :**
 - Device: Pixel 2, Pixel 5 , etc. This issue exists across all the verion
 - Android Version: 31
 - Browser Chrome
 - MSAL Version - 4.0.5

**Stacktrace**
```

> "main@10770" prio=5 tid=0x2 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	  at com.xerox.XrxSecurity.AzureAuthenticator$2.onError(AzureAuthenticator.java:101)
> 	  at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1948)
> 	  at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1935)
> 	  at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:555)
> 	  at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:86)
> 	  at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:535)
> 	  at android.os.Handler.handleCallback(Handler.java:873)
> 	  at android.os.Handler.dispatchMessage(Handler.java:99)
> 	  at android.os.Looper.loop(Looper.java:214)
> 	  at android.app.ActivityThread.main(ActivityThread.java:6986)
> 	  at java.lang.reflect.Method.invoke(Method.java:-1)
> 	  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> 	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
> 
> "Jit thread pool worker thread 0@16007" daemon prio=5 tid=0x205c nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Signal Catcher@16021" daemon prio=5 tid=0x205d nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "ADB-JDWP Connection Control Thread@16022" daemon prio=0 tid=0x205e nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "ReferenceQueueDaemon@16023" daemon prio=5 tid=0x205f nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "FinalizerDaemon@16024" daemon prio=5 tid=0x2060 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "FinalizerWatchdogDaemon@16025" daemon prio=5 tid=0x2061 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "HeapTaskDaemon@16026" daemon prio=5 tid=0x2062 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_1@16027" prio=5 tid=0x2063 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_2@16028" prio=5 tid=0x2064 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Profile Saver@10776" daemon prio=5 tid=0x2068 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM file logger@11656" prio=5 tid=0x206a nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM telemetry@11792" prio=5 tid=0x206b nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM enrollment retry@11931" prio=5 tid=0x206c nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "queued-work-looper@11953" prio=5 tid=0x206e nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM telemetry@12089" prio=5 tid=0x2076 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM background-2@12596" prio=5 tid=0x2081 nid=NA waiting for monitor entry
>   java.lang.Thread.State: BLOCKED
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM background-4@12618" prio=5 tid=0x2083 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM background-5@12623" prio=5 tid=0x2084 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM background-6@12627" prio=5 tid=0x2085 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "pool-2-thread-1@12737" prio=5 tid=0x2088 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_3@12916" prio=5 tid=0x208a nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "pool-3-thread-1@13198" prio=5 tid=0x208c nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Intune MAM heartbeat@13651" prio=5 tid=0x208e nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "RenderThread@14709" daemon prio=7 tid=0x20a4 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "hwuiTask1@14890" prio=5 tid=0x20ab nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_4@14910" prio=5 tid=0x20ad nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_5@14945" prio=5 tid=0x20b2 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "magnifier pixel copy result handler@15172" prio=5 tid=0x20b4 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Okio Watchdog@15344" daemon prio=5 tid=0x20c7 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "pool-7-thread-1@15818" prio=5 tid=0x20d1 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "pool-7-thread-2@15819" prio=5 tid=0x20d2 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "pool-6-thread-1@15939" prio=5 tid=0x20d7 nid=NA waiting
>   java.lang.Thread.State: WAITING
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_6@15997" prio=5 tid=0x20dc nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Thread-70@16010" prio=5 tid=0x20e7 nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 
> "Binder:32737_7@16020" prio=5 tid=0x20eb nid=NA runnable
>   java.lang.Thread.State: RUNNABLE
> 	 Incompatible thread state: thread not suspended
> 

```
**To Reproduce**
1) Install company portal app
2) Login to the company portal app
3) Then install the application which is having ADAL + Intune integration i.e **custom apps**
4) Now try to invoke acqureToken[interactive login] request from custom app. We will get the exception as shown above

**Expected behavior**
User should be able to login with out any issue. 

**Actual Behavior**
Acquire token  request fails with exception as shown on screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/1314621/206410670-6513738e-6542-45ef-8eee-0e35022abb87.png)

**Additional context**
One more additional information. Our app doesn't support broker authenticaiton. 

I can see the exception is thrown from below method
`private static boolean isFullBrowser(final ResolveInfo resolveInfo `

**Comment by p3dr0rv** [comment]
@shanmugpriyan306   Could you please reproduce the issue from scratch and sent the logs back to us, So we can investigate the root cause.
Thanks

How to collect Company portal logs
1. Open the Company Portal app.
2. Tap Menu > Help > Email Support. The Menu option may appear as a software button or a hardware button, depending on which Android device you have. 
3. Tap Upload Logs Only.
4. After the upload is complete, you will receive an incident ID. Share this with US.
![image](https://user-images.githubusercontent.com/76129899/220756073-aca33f16-be79-4062-9c6a-d00462f2aaee.png)


Additionally, please collect the MSAL logs on a verbose level.
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-android
