### ISSUE TITLE
Invalid JSON 'claims' value encountered

### ISSUE THREAD

**Issue by dwh1994** [AzureAD/microsoft-authentication-library-for-android#1749]
**Describe the bug**
I am using MSAL for Android and confused about this error:
```
com.microsoft.identity.common.java.exception.ServiceException: Invalid JSON 'claims' value encountered
	at com.microsoft.identity.common.java.controllers.ExceptionAdapter.exceptionFromAcquireTokenResult(ExceptionAdapter.java:96)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.getCommandResultFromTokenResult(CommandDispatcher.java:572)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:480)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:85)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$5.run(CommandDispatcher.java:648)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
 Caused by: com.microsoft.identity.client.exception.MsalServiceException: Invalid JSON 'claims' value encountered
	at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
	at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:351)
	at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:337)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:534)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:85)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:514)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Smartphone (please complete the following information):**
 - Device: ONEPLUS A6000
 - Android Version: 10
- MSAL Version:3.0.2

**Comment by nebulabox** [comment]
Had the same problem, hoping for a quick solution workaround.

**Comment by carlospei1** [comment]
same question, any update?

**Comment by xukai59740** [comment]
same question, 
Do we have fix plan?

**Comment by stevendev** [comment]
It works now. It had been fixed on Microsoft server side.

**Comment by ericklesterdev** [comment]
Currently encountering this error. Happened 3 days ago. Then yesterday it is working fine, then occurred again today.

**Comment by roja-d** [comment]
Im using 4.1.3 msal version, but im still facing this issue

**Comment by Gorebar** [comment]
Same here! I'm using 4.1.3 MSAL Version. But I tested in 3.0.2 and same problem.

**Comment by roja-d** [comment]
Hi Microsoft team, Can you please look on to this issue. As my app is in live on playstore.

**Comment by Gorebar** [comment]
Hi there, @negoe

To give you more info, the issue only appears using a personal account y my case. You can log-in without any problem using Sharepoint/business account.

Thanks.

**Comment by roja-d** [comment]
Hi @Gorebar 
But it should work for personal accounts also. As its working in IOS and other platforms

**Comment by Gorebar** [comment]
> Hi @Gorebar But it should work for personal accounts also. As its working in IOS and other platforms

Yeah yeah, for sure. I really need this issue fixed ASAP.

**Comment by roja-d** [comment]
Hi All,

For some reason below thing for scopes array while calling signin method working for me to login.

**_"user.read".split(" ").toTypedArray()_**

My kotlin code is

**_app!!.signIn(requireActivity(), "", "user.read".split(" ").toTypedArray(), getAuthInteractiveCallback())_**

**Comment by negoe** [comment]
@roja-d, @Gorebar, Thanks for your patience. We identified the issue and rolled back the build. I tested on my end an not seeing this error. Please try it on your side and let us know if you still see this in 24-48 hours.

**Comment by Gorebar** [comment]
> @roja-d, @Gorebar, Thanks for your patience. We identified the issue and rolled back the build. I tested on my end an not seeing this error. Please try it on your side and let us know if you still see this in 24-48 hours.

Hi @negoe, I just tested on my end and it is working good right now. Thank you so much!
