### ISSUE TITLE
Failed resolution of: Lio/opentelemetry/api/trace/Span

### ISSUE THREAD

**Issue by masztalski** [AzureAD/microsoft-authentication-library-for-android#1764]
**Describe the bug**
App in production. Issue while refreshing silently token. On many users I receiv exception not allowing to continue with re-login

**Smartphone (please complete the following information):**
 - Device: Sunmi V2 STGL
 - Android Version: 11
 - MSAL Version: 4.2.0

**Stacktrace**
`com.microsoft.identity.client.exception.MsalClientException: Failed resolution of: Lio/opentelemetry/api/trace/Span; at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:27) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:2) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallBackOnError(CommandDispatcher.java:11) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$700(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$3$1.run(CommandDispatcher.java:7) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7700) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) Caused by: com.microsoft.identity.common.java.exception.ClientException: Failed resolution of: Lio/opentelemetry/api/trace/Span; at com.microsoft.identity.common.java.controllers.ExceptionAdapter.baseExceptionFromException(ExceptionAdapter.java:105) at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallBackOnError(CommandDispatcher.java:7) ... 9 more Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/opentelemetry/api/trace/Span; at com.microsoft.identity.common.java.util.HashMapExtensions.getJsonResponseFromResponseBody(HashMapExtensions.java:6) at com.microsoft.identity.common.java.util.HashMapExtensions.getJsonResponse(HashMapExtensions.java:17) at com.microsoft.identity.common.java.exception.ServiceException.setHttpResponse(ServiceException.java:32) at com.microsoft.identity.common.java.controllers.ExceptionAdapter.setHttpResponseUsingTokenErrorResponse(ExceptionAdapter.java:21) at com.microsoft.identity.common.java.controllers.ExceptionAdapter.getExceptionFromTokenErrorResponse(ExceptionAdapter.java:9) at com.microsoft.identity.common.java.controllers.ExceptionAdapter.getExceptionFromTokenErrorResponse(ExceptionAdapter.java:24) at com.microsoft.identity.common.java.controllers.ExceptionAdapter.exceptionFromTokenResult(ExceptionAdapter.java:33) at com.microsoft.identity.common.java.controllers.ExceptionAdapter.exceptionFromAcquireTokenResult(ExceptionAdapter.java:144) at com.microsoft.identity.common.java.controllers.CommandDispatcher.getCommandResultFromTokenResult(CommandDispatcher.java:31) at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:62) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:98) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:923) Caused by: java.lang.ClassNotFoundException: io.opentelemetry.api.trace.Span ... 15 more`

**To Reproduce**
No idea - happens only on production

**Comment by masztalski** [comment]
Sorry, my bad - seems that we are using previous version 4.0.5. I thought it was merged :(
