### ISSUE TITLE
Unable to perform cloud discovery

### ISSUE THREAD

**Issue by masztalski** [AzureAD/microsoft-authentication-library-for-android#1765]
**Describe the bug**
App in production. Issue while starting SingleClientApplication

**Smartphone (please complete the following information):**
 - Device: Sunmi V2 STGL
 - Android Version: 11
 - MSAL Version: 4.2.0

**Stacktrace**
` com.microsoft.identity.client.exception.MsalClientException: Unable to perform cloud discovery at com.cargus.pudo.data.authenticate.repository.AuthenticateRepositoryImpl$login$1$1.onError(AuthenticateRepositoryImpl.kt:5) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:4) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:15) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:47) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7700) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) Caused by: com.microsoft.identity.client.exception.MsalClientException: Unable to perform cloud discovery at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:27) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:2) ... 11 more Caused by: com.microsoft.identity.common.java.exception.ClientException: Unable to perform cloud discovery at com.microsoft.identity.common.java.authorities.Authority.getKnownAuthorityResult(Authority.java:58) at com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:91) at com.microsoft.identity.common.java.commands.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:6) at com.microsoft.identity.common.java.commands.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:2) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$5.run(CommandDispatcher.java:106) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:923) Caused by: java.net.UnknownHostException: Unable to resolve host "login.microsoftonline.com": No address associated with hostname at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156) at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103) at java.net.InetAddress.getAllByName(InetAddress.java:1152) at com.android.okhttp.Dns$1.lookup(Dns.java:41) at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178) at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144) at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86) at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176) at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128) at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97) at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302) at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248) at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211) at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30) at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.executeHttpSend(UrlConnectionHttpClient.java:25) at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.access$100(UrlConnectionHttpClient.java:1) at com.microsoft.identity.common.java.net.UrlConnectionHttpClient$4.call(UrlConnectionHttpClient.java:2) at com.microsoft.identity.common.java.net.UrlConnectionHttpClient$4.call(UrlConnectionHttpClient.java:1) at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt(StatusCodeAndExceptionRetry.java:4) at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt(StatusCodeAndExceptionRetry.java:1) at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.method(UrlConnectionHttpClient.java:33) at com.microsoft.identity.common.java.net.AbstractHttpClient.get(AbstractHttpClient.java:8) at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery(AzureActiveDirectory.java:66) at com.microsoft.identity.common.java.authorities.Authority.performCloudDiscovery(Authority.java:78) at com.microsoft.identity.common.java.authorities.Authority.getKnownAuthorityResult(Authority.java:35) ... 9 more Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname) at libcore.io.Linux.android_getaddrinfo(Native Method) at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73) at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202) at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73) at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135) ... 36 more`

**To Reproduce**
No idea - happens only on production

**Comment by masztalski** [comment]
Sorry, my bad - seems that we are using previous version 4.0.5. I thought it was merged :(
