### ISSUE TITLE
Cannot refresh token due to power optimization

### ISSUE THREAD

**Issue by masztalski** [AzureAD/microsoft-authentication-library-for-android#1766]
**Describe the bug**
App in production. Issue while refreshing silently token. On many users I receive exception not allowing to continue with re-login
Device is not on doze mode (probably) as from logs I can see actions before executing this operation

**Smartphone (please complete the following information):**
 - Device: Sunmi V2 STGL
 - Android Version: 11
 - MSAL Version: 4.2.0

**Stacktrace**
`com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:27) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:2) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:15) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:47) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7700) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997) Caused by: com.microsoft.identity.common.java.exception.ClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby at com.microsoft.identity.common.internal.platform.AndroidPlatformUtil.throwIfNetworkNotAvailable(AndroidPlatformUtil.java:23) at com.microsoft.identity.common.java.controllers.BaseController.performSilentTokenRequest(BaseController.java:43) at com.microsoft.identity.common.java.controllers.BaseController.renewAccessToken(BaseController.java:5) at com.microsoft.identity.common.internal.controllers.LocalMSALController.renewAT(LocalMSALController.java:6) at com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:312) at com.microsoft.identity.common.java.commands.SilentTokenCommand.execute(SilentTokenCommand.java:8) at com.microsoft.identity.common.java.commands.SilentTokenCommand.execute(SilentTokenCommand.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:2) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:98) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:923) , com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby`

**To Reproduce**
No idea - happens only on production

**Comment by masztalski** [comment]
Sorry, my bad - seems that we are using previous version 4.0.5. I thought it was merged :(
