### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by johnzhu123** [AzureAD/microsoft-authentication-library-for-android#1833]
I'm using [msal_flutter](https://pub.dev/packages/msal_flutter)

after all i configured , the below error occurred
```
I/xample.iconsole( 5745): Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
W/Parcel  ( 5745): Expecting binder but got null!
I/flutter ( 5745): initializing pca
D/MsalFlutter( 5745): Getting the created listener
E/AndroidRuntime( 5745): FATAL EXCEPTION: Thread-4
E/AndroidRuntime( 5745): Process: com.example.iconsole, PID: 5745
E/AndroidRuntime( 5745): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime( 5745): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfigurationInternal(PublicClientApplicationConfigurationFactory.java:96)
E/AndroidRuntime( 5745): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:60)
E/AndroidRuntime( 5745): 	at com.microsoft.identity.client.PublicClientApplication$3.run(PublicClientApplication.java:366)
E/AndroidRuntime( 5745): 	at java.lang.Thread.run(Thread.java:1012)
I/Process ( 5745): Sending signal. PID: 5745 SIG: 9
Lost connection to device.

Exited.
```
Did I miss to config something in the msal_default_config.json?

**Comment by johnzhu123** [comment]
never mind
just add these two line
```
"handle_null_taskaffinity": false,
 "authorization_in_current_task": false,
```

**Comment by fehmidevoteam** [comment]
@johnzhu123 Could you please share you json file content? because i still have same error even i add those two lines

**Comment by aggeloskoutanis** [comment]
I have the same problem. Did you fix it?
