### ISSUE TITLE
Android 13 Leave it in the background for about an hour and an error will occur

### ISSUE THREAD

**Issue by XiaMuYao** [AzureAD/microsoft-authentication-library-for-android#1842]
2023-06-15 10:54:58.609 13523-13655/packageName E/BrokerOperationExecutor:execute: [2023-06-15 02:54:58 - thread_name: pool-19-thread-1, correlation_id: 96268f88-a312-4136-b20c-5d4fe51de0f9 - Android 33] [ipc_connection_error] [content_provider] :Failed to get result from Broker Content Provider, cursor is null
    com.microsoft.identity.common.exception.BrokerCommunicationException: [ipc_connection_error] [content_provider] :Failed to get result from Broker Content Provider, cursor is null
        at com.microsoft.identity.common.internal.broker.ipc.ContentProviderStrategy.communicateToBroker(ContentProviderStrategy.java:115)
        at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.performStrategy(BrokerOperationExecutor.java:230)
        at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.execute(BrokerOperationExecutor.java:145)
        at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getAccounts(BrokerMsalController.java:525)
        at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getCurrentAccount(BrokerMsalController.java:693)
        at com.microsoft.identity.common.internal.commands.GetCurrentAccountCommand.execute(GetCurrentAccountCommand.java:75)
        at com.microsoft.identity.common.internal.commands.GetCurrentAccountCommand.execute(GetCurrentAccountCommand.java:43)
        at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:456)
        at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:87)
        at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:278)
        at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
        at io.opentelemetry.context.Context.$r8$lambda$3Y-T3eyWgYoNX58Un4uW3R7nekc(Unknown Source:0)
        at io.opentelemetry.context.Context$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
2023-06-15 10:54:58.610 13523-13655/packageName E/BrokerOperationExecutor:execute: [2023-06-15 02:54:58 - thread_name: pool-19-thread-1, correlation_id: 96268f88-a312-4136-b20c-5d4fe51de0f9 - Android 33] [ipc_operation_not_supported_on_server_side] [bound_service] :failed to bind. The service is not available.
    com.microsoft.identity.common.exception.BrokerCommunicationException: [ipc_operation_not_supported_on_server_side] [bound_service] :failed to bind. The service is not available.
        at com.microsoft.identity.common.internal.broker.BoundServiceClient.connect(BoundServiceClient.java:150)
        at com.microsoft.identity.common.internal.broker.BoundServiceClient.performOperation(BoundServiceClient.java:120)
        at com.microsoft.identity.common.internal.broker.ipc.BoundServiceStrategy.communicateToBroker(BoundServiceStrategy.java:41)
        at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.performStrategy(BrokerOperationExecutor.java:230)
        at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.execute(BrokerOperationExecutor.java:145)
        at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getAccounts(BrokerMsalController.java:525)
        at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getCurrentAccount(BrokerMsalController.java:693)
        at com.microsoft.identity.common.internal.commands.GetCurrentAccountCommand.execute(GetCurrentAccountCommand.java:75)
        at com.microsoft.identity.common.internal.commands.GetCurrentAccountCommand.execute(GetCurrentAccountCommand.java:43)
        at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:456)
        at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:87)
        at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:278)
        at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
        at io.opentelemetry.context.Context.$r8$lambda$3Y-T3eyWgYoNX58Un4uW3R7nekc(Unknown Source:0)
        at io.opentelemetry.context.Context$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by XiaMuYao** [comment]
In Android 12, it runs normally and the version used is 1.4.0
I tried using version 4.5.0 on Android 13 and got the same error

**Comment by negoe** [comment]
@XiaMuYao Can you also please share the device model you are testing on? Is it on only on one type of device or all devices?

**Comment by negoe** [comment]
@XiaMuYao closing the thread due to no response. Please feel free to reopen if you need to follow up. I will be interested to knwo how did you solve your issue if you already did, feel free to share.
