### ISSUE TITLE
Failed to resolve: io.opentelemetry:opentelemetry-bom:1.18.0

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-for-android#1864]
Hi, since updating to below Android Studio version, MSAL generates following error

Android Studio Hedgehog | 2023.1.1 Canary 14
Build #AI-231.9225.16.2311.10533651, built on July 20, 2023

com.android.tools.build:gradle version 8.2.0-alpha14

MSAL Version 4.6.3

Downgrading back to Canary 12 resolves the issue.

Error is:

> No matching variant of io.opentelemetry:opentelemetry-bom:1.18.0 was found. The consumer was configured to find a library for use during runtime, preferably optimized for Android
> ..... 
> attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
>   - Variant 'apiElements' capability io.opentelemetry:opentelemetry-bom:1.18.0:
>       - Incompatible because this component declares a platform for use during compile-time and the consumer needed a library for use during runtime

**Comment by NLLAPPS** [comment]
Below seems to fix the error for now

  ```
  implementation(libs.microsoft.msal){
        exclude(group = "io.opentelemetry")
    }
    implementation("io.opentelemetry:opentelemetry-api:1.18.0")
    implementation("io.opentelemetry:opentelemetry-context:1.18.0")
```

**Comment by RoarGronmo** [comment]
Linked your solution to my issue in https://issuetracker.google.com/issues/293294914

Thanx for sorting it out, it failed both for AS HH C13 and C14.

**Comment by slowcar** [comment]
With the release of Gradle 8.2 this issue came up for us as well. The workaround is successful, but it would probably be better to fix it generally.

**Comment by belidzs** [comment]
In Groovy DSL the syntax is slightly different:

```groovy
    implementation("com.microsoft.identity.client:msal:4.10.0") {
        exclude(group : "io.opentelemetry")
    }
    implementation("io.opentelemetry:opentelemetry-api:1.18.0")
    implementation("io.opentelemetry:opentelemetry-context:1.18.0")

```

**Comment by davidkarlsson** [comment]
According to https://issuetracker.google.com/issues/301952449 this is working as intended in AGP 8.2 so I'm guessing MSAL must be specifying the opentelemetry dependency incorrectly in its build.gradle?

**Comment by yudhistre** [comment]
Looking forward to when MSAL Actually fixes this issue. Any updates from them?

**Comment by ShmuelCammebys** [comment]
Duplicated by #1970.

**Comment by ShmuelCammebys** [comment]
Using .gradle.kts with .toml version catalog, this is:
```kotlin
implementation(libs.msal4Android.get().let { "${it.module}:${it.versionConstraint.requiredVersion}" }) {
    exclude("io.opentelemetry")
}
```

**Comment by ShmuelCammebys** [comment]
When I use the workaround and run the code in the README, I get this stacktrace:
```log
Process: kmp.msal.androidApp, PID: 6941
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lio/opentelemetry/api/trace/SpanContext;
                                                                                                    	at com.microsoft.identity.client.internal.CommandParametersAdapter.createCommandParameters(CommandParametersAdapter.java:109)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.create(PublicClientApplication.java:1085)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.createMultipleAccountPublicClientApplication(PublicClientApplication.java:1183)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.access$100(PublicClientApplication.java:218)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication$4.run(PublicClientApplication.java:476)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.opentelemetry.api.trace.SpanContext" on path: DexPathList[[dex file "/data/data/kmp.msal.androidApp/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~tf-9BefJEpx-Q_RPoZOmIQ==/kmp.msal.androidApp-I5bk5S5arL1H1hUJhtG_TA==/base.apk"],nativeLibraryDirectories=[/data/app/~~tf-9BefJEpx-Q_RPoZOmIQ==/kmp.msal.androidApp-I5bk5S5arL1H1hUJhtG_TA==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.microsoft.identity.client.internal.CommandParametersAdapter.createCommandParameters(CommandParametersAdapter.java:109) 
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.create(PublicClientApplication.java:1085) 
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.createMultipleAccountPublicClientApplication(PublicClientApplication.java:1183) 
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.access$100(PublicClientApplication.java:218) 
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication$4.run(PublicClientApplication.java:476) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
2024-01-09 00:16:54.332  6941-6977  Process                 kmp.msal.androidApp  I  Sending signal. PID: 6941 SIG: 9
```

**Comment by shahzaibj** [comment]
@NLLAPPS @yudhistre @davidkarlsson  Is this an issue faced in production? We are currently specifying dependency as recommended by Open Telemetry docs. 

From what you are describing it seems like an Android Studio bug on a specific recent version of AS? I'm assuming you are able to build from terminal / pipelines and everything works in prod? Is that right? 

Either way we would mitigate it but just trying to understand the full impact of this issue.

**Comment by ShmuelCammebys** [comment]
@shahzaibj Yes, this is in production, and it does not build from the terminal. Could it be the fact that Gradle 8.2+ requires a higher JDK version than 8? New releases of Android Studio and Gradle won't build the project. I cannot include the library in any company projects without downgrading the entire toolchain/infrastructure - making it a hard sell to management to include the library.

**Comment by davidkarlsson** [comment]
@shahzaibj For me it started happening with both debug and release builds after having updated the Android Gradle Plugin to 8.2.0 so I don't think the AS version has anything to do with it?

Without the workaround that @NLLAPPS posted I get the error in the following build steps:

```
Task :app:dataBindingMergeDependencyArtifactsStandardDebug FAILED
Task :app:mergeStandardDebugResources FAILED
Task :app:checkStandardDebugAarMetadata FAILED
Task :app:mapStandardDebugSourceSetPaths FAILED
Task :app:processStandardDebugMainManifest FAILED
Task :app:mergeStandardDebugAssets FAILED
Task :app:checkStandardDebugDuplicateClasses FAILED
Task :app:desugarStandardDebugFileDependencies FAILED
Task :app:mergeStandardDebugNativeLibs FAILED
```

The error looks like this for all of these build steps:

```
Execution failed for task ':app:mergeStandardDebugResources'.
> Could not resolve all files for configuration ':app:standardDebugRuntimeClasspath'.
   > Could not resolve io.opentelemetry:opentelemetry-bom:1.18.0.
     Required by:
         project :app > com.microsoft.identity.client:msal:4.10.0
      > No matching variant of io.opentelemetry:opentelemetry-bom:1.18.0 was found. The consumer was configured to find a library for use during runtime, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:version' with value 'standard', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.2.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'apiElements' capability io.opentelemetry:opentelemetry-bom:1.18.0:
              - Incompatible because this component declares a platform for use during compile-time and the consumer needed a library for use during runtime
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:version (required 'standard')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedApiElements' capability io.opentelemetry:opentelemetry-bom-derived-enforced-platform:1.18.0:
              - Incompatible because this component declares an enforced platform for use during compile-time and the consumer needed a library for use during runtime
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:version (required 'standard')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedRuntimeElements' capability io.opentelemetry:opentelemetry-bom-derived-enforced-platform:1.18.0 declares a component for use during runtime:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:version (required 'standard')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'runtimeElements' capability io.opentelemetry:opentelemetry-bom:1.18.0 declares a component for use during runtime:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:version (required 'standard')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
```
