### ISSUE TITLE
ANR triggered by com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.executeHttpSend (UrlConnectionHttpClient.java:263)

### ISSUE THREAD

**Issue by DJPretorius** [AzureAD/microsoft-authentication-library-for-android#1904]
**Describe the bug**
I have a released app with Firebase Crashlytics enabled and it detected an ANR originating from `UrlConnectionHttpClient.executeHttpSend` within the `com.microsoft.identity.common.internal.net` package. The blocked thread reports 
```
main (blocked)
tid=1 systid=29312 | waiting to lock <0x08e7542e> (java.lang.Class<com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory>) held by thread 75
```
while the blocking thread indicates the ANR is caused by `com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.executeHttpSend (UrlConnectionHttpClient.java:263)`

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A32 and A04e, and Xiomi Redmi 10C
 - Android Version: Android 12 and 13
 - MSAL Version: 2.1.0

**Stacktrace**
Blocking tread
```
pool-31-thread-1 (native):tid=75 systid=29606 
#00 pc 0xdd14c libc.so (__ppoll + 12) (BuildId: 1ebacf9ecfa355864829d0b3b837afa2)
#01 pc 0x986bc libc.so (poll + 96) (BuildId: 1ebacf9ecfa355864829d0b3b837afa2)
#02 pc 0x293b4 libjavacore.so (Linux_poll(_JNIEnv*, _jobject*, _jobjectArray*, int) + 568) (BuildId: 6b73dfb8421638f17a93ae36d7145b3a)
       at libcore.io.Linux.poll(Native method)
       at libcore.io.ForwardingOs.poll(ForwardingOs.java:573)
       at libcore.io.BlockGuardOs.poll(BlockGuardOs.java:283)
       at libcore.io.ForwardingOs.poll(ForwardingOs.java:573)
       at libcore.io.IoBridge.isConnected(IoBridge.java:326)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
       at libcore.io.IoBridge.connect(IoBridge.java:179)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
       at java.net.Socket.connect(Socket.java:646)
       at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
       at com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.executeHttpSend(UrlConnectionHttpClient.java:263)
       at com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.access$100(UrlConnectionHttpClient.java:73)
       at com.microsoft.identity.common.internal.net.UrlConnectionHttpClient$2.call(UrlConnectionHttpClient.java:176)
       at com.microsoft.identity.common.internal.net.UrlConnectionHttpClient$2.call(UrlConnectionHttpClient.java:174)
       at com.microsoft.identity.common.internal.net.NoRetryPolicy.attempt(NoRetryPolicy.java:42)
       at com.microsoft.identity.common.internal.net.NoRetryPolicy.attempt(NoRetryPolicy.java:36)
       at com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.method(UrlConnectionHttpClient.java:174)
       at com.microsoft.identity.common.internal.net.AbstractHttpClient.get(AbstractHttpClient.java:47)
       at com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery(AzureActiveDirectory.java:188)
       at com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.loadCloudDiscoveryMetadata(AdalMigrationAdapter.java:238)
       at com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.adapt(AdalMigrationAdapter.java:119)
       at com.microsoft.identity.common.internal.migration.TokenMigrationUtility$1.run(TokenMigrationUtility.java:67)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
Blocked thread
```
main (blocked):tid=1 systid=29312 | waiting to lock <0x08e7542e> (java.lang.Class<com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory>) held by thread 75
       at com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory.setEnvironment(unavailable:2)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1069)
       at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1060)
       at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:64)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:943)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:929)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:448)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$900(CommandDispatcher.java:83)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:427)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8309)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

**To Reproduce**
I was unable to reproduce this ANR

**Expected behavior**
No ANR when using the MSAL

**Actual Behavior**
ANR when using MSAL

**Comment by negoe** [comment]
@DJPretorius This is really old version of MSAL. I would recommend upgrading to the [latest version ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases)and then test it again.

**Comment by DJPretorius** [comment]
@negoe I have upgraded to version 5.1.0 since I opened this issue but it is still occurring. This is our biggest cause of ANRs.

Here is the updated stack trace 
```
          pool-42-thread-1 (native):tid=69 systid=31198 
#00 pc 0xe8368 libc.so (__ppoll + 8) (BuildId: 35a04626779868e5f2a30e171716818d)
#01 pc 0x9b65c libc.so (poll + 92) (BuildId: 35a04626779868e5f2a30e171716818d)
#02 pc 0x2bc0c libjavacore.so (Linux_poll + 584) (BuildId: 1467928e917310ec89205f7a4bdf117c)
       at libcore.io.Linux.poll(Native method)
       at libcore.io.ForwardingOs.poll(ForwardingOs.java:573)
       at libcore.io.BlockGuardOs.poll(BlockGuardOs.java:283)
       at libcore.io.ForwardingOs.poll(ForwardingOs.java:573)
       at libcore.io.IoBridge.isConnected(IoBridge.java:326)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
       at libcore.io.IoBridge.connect(IoBridge.java:179)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
       at java.net.Socket.connect(Socket.java:646)
       at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.executeHttpSend(UrlConnectionHttpClient.java:343)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.access$100(UrlConnectionHttpClient.java:85)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient$4.call(UrlConnectionHttpClient.java:255)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient$4.call(UrlConnectionHttpClient.java:253)
       at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt(StatusCodeAndExceptionRetry.java:80)
       at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt(StatusCodeAndExceptionRetry.java:41)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.method(UrlConnectionHttpClient.java:253)
       at com.microsoft.identity.common.java.net.AbstractHttpClient.get(AbstractHttpClient.java:91)
       at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery(AzureActiveDirectory.java:193)
       at com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.loadCloudDiscoveryMetadata(AdalMigrationAdapter.java:241)
       at com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.adapt(AdalMigrationAdapter.java:120)
       at com.microsoft.identity.common.internal.migration.TokenMigrationUtility$1.run(TokenMigrationUtility.java:66)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```
Blocking thread
```
          main (blocked):tid=1 systid=30542 | waiting to lock <0x00837aa1> (java.lang.Class<com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory>) held by thread 69
       at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.setEnvironment(unavailable:2)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1279)
       at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1270)
       at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:67)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:1115)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:1097)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:650)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:99)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:626)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
Firebase Crashlytics reports `AuthorizationActivity` as the last screen that was visited before the ANR occurred.
