### ISSUE TITLE
Token acquisition can fail with undocumented error code device_network_not_available_doze_mode

### ISSUE THREAD

**Issue by bannus** [AzureAD/microsoft-authentication-library-for-android#1915]
**Describe the bug**
Production issue. Repro unknown, observed in customer logs. Presumably when the device is in Doze, token acquisition can fail with an `MsalClientException` with error code `device_network_not_available_doze_mode`, which does not appear in the [public docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-handling-exceptions) or in the `MsalClientException` class.

**Smartphone (please complete the following information):**
 - Device:  Samsung SM-A326B
 - Android Version: API 33
 - MSAL Version: 4.7.0 (code inspection suggests still present in 4.8.1, latest)

**Stacktrace**
```
com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby
	at o.R$color$cancelAll.onError(:139)
	at com.microsoft.identity.client.PublicClientApplication$18.onError(:1996)
	at com.microsoft.identity.client.PublicClientApplication$18.onError(:1983)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(:642)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(:99)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(:622)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby
	at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(:53)
	at com.microsoft.identity.client.PublicClientApplication$18.onError(:1992)
	at com.microsoft.identity.client.PublicClientApplication$18.onError(:1983)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(:642)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(:99)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(:622)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
com.microsoft.identity.common.java.exception.ClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby
	at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getBaseExceptionFromExceptionType(:359)
	at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getBaseExceptionFromBundle(:247)
	at com.microsoft.identity.common.internal.result.MsalBrokerResultAdapter.getAcquireTokenResultFromResultBundle(:706)
	at com.microsoft.identity.common.internal.controllers.BrokerMsalController$5.extractResultBundle(:657)
	at com.microsoft.identity.common.internal.controllers.BrokerMsalController$5.extractResultBundle(:628)
	at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.performStrategy(:232)
	at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.execute(:145)
	at com.microsoft.identity.common.internal.controllers.BrokerMsalController.acquireTokenSilent(:627)
	at com.microsoft.identity.common.java.commands.SilentTokenCommand.execute(:93)
	at com.microsoft.identity.common.java.commands.SilentTokenCommand.execute(:49)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(:542)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(:99)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(:364)
	at io.opentelemetry.context.Context.lambda$wrap$1(:212)
	at io.opentelemetry.context.-$$Lambda$Context$3Y-T3eyWgYoNX58Un4uW3R7nekc.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**To Reproduce**
Exact steps unknown, see above. I belive the code that throws this exception is [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/c4a3281f188293ca262223ac7e2115a74225bf29/common/src/main/java/com/microsoft/identity/common/internal/platform/AndroidPlatformUtil.java#L119C1-L119C1).

**Expected behavior**
Error code string is documented.

**Actual Behavior**
Error code string is not documented.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by negoe** [comment]
@bannus If device has battery optimization enabled this can prevent the app from receiving necessary updates in the background and working properly. Hence, it’s best to remove any battery restrictions for the app to ensure optimal performance. You can also ask your user to disable if they have  battery optimization on [Authenticator App](https://support.microsoft.com/en-us/account-billing/troubleshoot-problems-using-microsoft-authenticator-a3a74493-566b-4c2e-b949-a2789bac0fd3) or [Company Portal ](https://learn.microsoft.com/en-us/mem/intune/user-help/turn-off-battery-optimization-android)enabled for their device. 

Thanks for sharing this. We will make sure to document this error code for better experience in future.
