### ISSUE TITLE
NoClassDefFoundError version upgrade from 2.2.3 -> 3.0.2

### ISSUE THREAD

**Issue by nannandenden** [AzureAD/microsoft-authentication-library-for-android#1921]
Hello,

We are using version [2.2.3](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.2.3) and everything is working fine for a couple years now. Currently we are trying to upgrade to a newer version to avoid some security issue. 

We are getting `NoClassDefFoundError` when trying to upgrade to [3.0.2](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v3.0.2) and project crashes. (no code or config file changes other than version upgrade)

When calling `PublicClientApplication.createMultipleAccountPublicClientApplication` method, app crashes with below stacktrace 

**Smartphone (please complete the following information):**
 - Device: All Android 
 - Android Version: All Version  
 - Browser:N/A 
 - MSAL Version: 3.0.2 (trying to upgrade from 2.2.3)

**Stacktrace**
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcz/msebera/android/httpclient/client/utils/URIBuilder;
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.getGsonForLoadingConfiguration(PublicClientApplicationConfigurationFactory.java:179)
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:166)
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:120)
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:71)
	at com.microsoft.identity.client.PublicClientApplication$4.run(PublicClientApplication.java:456)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassNotFoundException: Didn't find class "cz.msebera.android.httpclient.client.utils.URIBuilder" on path: DexPathList[[zip file "/data/app/XXXXX”],nativeLibraryDirectories=[/data/app/~~XXXXX]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.getGsonForLoadingConfiguration(PublicClientApplicationConfigurationFactory.java:179) 
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:166) 
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:120) 
	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:71) 
	at com.microsoft.identity.client.PublicClientApplication$4.run(PublicClientApplication.java:456) 
	at java.lang.Thread.run(Thread.java:1012) 
```

**Additional context**

list of msal dependencies under the project. 
no `cz.msebera.android.httpclient.client`(from stacktrace) under the project dependencies.  

![Screenshot 2023-10-13 at 4 20 57 PM](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/7422884/5d50f6ad-e40a-4eff-b932-fe1e01af37e5)

Tried upgrade to a higher library version(4.0.0...etc) but nothing happens when code is executed. No callbacks and log messages. It seems like code is terminated at some point but was not able to identify where...

Any suggestions & feedbacks are appreciated!

**Comment by negoe** [comment]
Hi, We do not support Major versions twelve months after the release of the next major version. I would recommend upgrading to the [latest 4.9.0](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases). Please try upgrading to the latest and we are happy to help with any issue you experience. 

Thanks.

**Comment by nannandenden** [comment]
Hi,
I have tried upgrading to 4.9.0 but code is getting terminated at some point without any error message I have mentioned in the initial inquiries.

```
Tried upgrade to a higher library version(4.0.0...etc) but nothing happens when code is executed. No callbacks and log messages. It seems like code is terminated at some point but was not able to identify where...
```

since I am not getting useful error message I am not sure what information to provide. 
@negoe, do you have any suggestion on what information I can provide? 

Thank you.

**Comment by sinhpn92** [comment]
Hi @nannandenden 

Did you resolve this issue?

**Comment by Im-flying-sparrow** [comment]
@nannandenden @sinhpn92 @negoe 
Did you resolve this issue?
