### ISSUE TITLE
Crash in library for sign in on shared device mode device

### ISSUE THREAD

**Issue by adit-modhvadia** [AzureAD/microsoft-authentication-library-for-android#1934]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel, OnePlus 6, etc] Bluebird EF550R
 - Android Version: [e.g. API Level, Build Number] Android 10
 - Browser [e.g. Chrome, Edge]
 - MSAL Version 4.7.0

**Stacktrace**
```If a crash occurs, include the stacktrace.
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at java.lang.String.contains(String.java:2224)
       at com.microsoft.identity.client.AccountAdapter$GuestAccountFilter.filter(AccountAdapter.java:63)
       at com.microsoft.identity.client.AccountAdapter.filterCacheRecords(AccountAdapter.java:356)
       at com.microsoft.identity.client.AccountAdapter.adapt(AccountAdapter.java:161)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.getAccountFromICacheRecordList(SingleAccountPublicClientApplication.java:609)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.getPersistedCurrentAccount(SingleAccountPublicClientApplication.java:573)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.access$000(SingleAccountPublicClientApplication.java:84)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication$1$1.onTaskCompleted(SingleAccountPublicClientApplication.java:139)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication$1$1.onTaskCompleted(SingleAccountPublicClientApplication.java:133)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:649)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:99)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:625)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)```

**To Reproduce**
Steps to reproduce the behavior:
Clicking sign in on Microsoft button causes the crash. When our app creates the PublicClientApplication.createSingleAccountPublicClientApplication

If related to user experience, use the format:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual Behavior**
A description of what actually happened.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by negoe** [comment]
@adit-modhvadia Was fixed in the latest release [4.9.2](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/untagged-93515a0dbf903c7809ad).
