### ISSUE TITLE
Fatal Exception: android.os.DeadSystemRuntimeException: android.os.DeadSystemException

### ISSUE THREAD

**Issue by rahulbmatte18** [AzureAD/microsoft-authentication-library-for-android#1937]
**Describe the bug**
We have integrated the MSAL SDK version 2.+ into our PROD app. Recently we started receiving crash on Firebase console

**Smartphone (please complete the following information):**
 - Device: Samsung A33, A32, Motto 5G plus, Samsung A40, A51, Android OS version 13
 - Min sdk version- 25, Target sdk version- 30
 - Edge
 - MSAL Version: 2.+

**Stacktrace**
Fatal Exception: android.os.DeadSystemRuntimeException: android.os.DeadSystemException
       at android.app.ApplicationPackageManager.queryContentProviders(ApplicationPackageManager.java:1798)
       at android.app.ApplicationPackageManager.queryContentProviders(ApplicationPackageManager.java:1779)
       at android.app.ApplicationPackageManager.queryContentProviders(ApplicationPackageManager.java:1773)
       at com.microsoft.identity.common.internal.broker.ipc.ContentProviderStrategy.isBrokerContentProviderAvailable(ContentProviderStrategy.java:3)
       at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getIpcStrategies(BrokerMsalController.java:5)
       at com.microsoft.identity.common.internal.controllers.BrokerMsalController.<init>(BrokerMsalController.java:7)
       at com.microsoft.identity.client.internal.controllers.MSALControllerFactory.getDefaultController(MSALControllerFactory.java:2)
       at com.microsoft.identity.client.PublicClientApplication.create(PublicClientApplication.java:34)
       at com.microsoft.identity.client.PublicClientApplication.createSingleAccountPublicClientApplication(PublicClientApplication.java:20)
       at com.microsoft.identity.client.PublicClientApplication.access$200(PublicClientApplication.java:1)
       at com.microsoft.identity.client.PublicClientApplication$6.run(PublicClientApplication.java:3)
       at java.lang.Thread.run(Thread.java:1012)

**To Reproduce**
Keep the app idle for more than a day and try to click on App launcher icon as we are checking for user's active session via silent API call.

**Comment by negoe** [comment]
@rahulbmatte18 Unfortunately, you are using a very old version of the library. I would strongly recommend to update to the latest [version ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases)and test. If you are still experiencing the issue, please let us know and feel free to reopen the issue.
