### ISSUE TITLE
MsalClientException: PRT is present but Session Key is NULL!

### ISSUE THREAD

**Issue by gcastaldi** [AzureAD/microsoft-authentication-library-for-android#1948]
**Describe the bug**
We are going live with an android app using msal. When Authenticator is used and we call ISingleAccountPublicClientApplication.signIn we have this exception when our app returns in foreground. Problem verified with versions 4.7.0 and 4.9.0. Two weeks ago it worked correctly (same code and same msal library).
It works correctly if the login is executed in the browser.

**Smartphone (please complete the following information):**
 - Device: Samsung A52
 - Android Version: Android 12, Sdk 31
 - Browser: Chrome
 - MSAL Version: 4.7.0, 4.9.0

**Stacktrace**
`
    error code: unknown_error
    error message: PRT is present but Session Key is NULL!
    ex: com.microsoft.identity.common.exception.BaseException
    com.microsoft.identity.client.exception.MsalClientException: PRT is present but Session Key is NULL!
    	at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:53)
    	at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:433)
    	at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:419)
    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:642)
    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:99)
    	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:622)
    	at android.os.Handler.handleCallback(Handler.java:938)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:226)
    	at android.os.Looper.loop(Looper.java:313)
    	at android.app.ActivityThread.main(ActivityThread.java:8663)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
`

**To Reproduce**
Create accountApp
Call signIn

**Expected behavior**
User logged

**Actual Behavior**
Exception

**Comment by negoe** [comment]
@gcastaldi Fixed https://github.com/AzureAD/ad-accounts-for-android/pull/2596
