### ISSUE TITLE
ANR as main thread waits for the lock in IO thread

### ISSUE THREAD

**Issue by m-kubis** [AzureAD/microsoft-authentication-library-for-android#1952]
**Describe the bug**
Production issue coming from Firebase Crashlytics. Rare (3 users so far), non reproducible locally. Low severity, ANR only.

**Smartphone (please complete the following information):**
 - Device: Galaxy S22
 - Android Version: 12
 - Browser: Unknown
 - MSAL Version: 4.9.0

**Stacktrace**
Blocking IO thread:
```
pool-26-thread-3 (native):tid=64 systid=16748 
#00 pc 0x9ea44 libc.so (read + 4)
#01 pc 0xaa40c libc.so (__sread + 44)
#02 pc 0xaa304 libc.so (__srefill + 260)
#03 pc 0xae6a8 libc.so (fread_unlocked + 204)
#04 pc 0xae598 libc.so (fread + 72)
#05 pc 0x6af74 libc.so (android_getaddrinfo_proxy + 332)
#06 pc 0x6ac08 libc.so (android_getaddrinfofornetcontext + 1612)
#07 pc 0x6a594 libc.so (android_getaddrinfofornet + 56)
#08 pc 0x2230c libjavacore.so (Linux_android_getaddrinfo(_JNIEnv*, _jobject*, _jstring*, _jobject*, int) + 336)
       at libcore.io.Linux.android_getaddrinfo(Native method)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
       at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.perf.network.InstrURLConnectionBase.getInputStream(InstrURLConnectionBase.java:138)
       at com.google.firebase.perf.network.InstrHttpsURLConnection.getInputStream(InstrHttpsURLConnection.java:79)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.executeHttpSend(UrlConnectionHttpClient.java:337)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.access$100(UrlConnectionHttpClient.java:79)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient$4.call(UrlConnectionHttpClient.java:249)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient$4.call(UrlConnectionHttpClient.java:247)
       at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt(StatusCodeAndExceptionRetry.java:80)
       at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt(StatusCodeAndExceptionRetry.java:41)
       at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.method(UrlConnectionHttpClient.java:247)
       at com.microsoft.identity.common.java.net.AbstractHttpClient.get(AbstractHttpClient.java:91)
       at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery(AzureActiveDirectory.java:193)
       at com.microsoft.identity.common.java.commands.parameters.SilentTokenCommandParameters.performCloudDiscovery(SilentTokenCommandParameters.java:119)
       at com.microsoft.identity.common.java.commands.parameters.SilentTokenCommandParameters.authorityMatchesAccountEnvironment(SilentTokenCommandParameters.java:89)
       at com.microsoft.identity.common.java.commands.parameters.SilentTokenCommandParameters.validate(SilentTokenCommandParameters.java:59)
       at com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:283)
       at com.microsoft.identity.common.java.commands.SilentTokenCommand.execute(SilentTokenCommand.java:94)
       at com.microsoft.identity.common.java.commands.SilentTokenCommand.execute(SilentTokenCommand.java:49)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:456)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:87)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:278)
       at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

Blocks the main thread:
```
main (blocked):tid=1 systid=4861 | waiting to lock <0x0fb18004> (java.lang.Class<com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory>) held by thread 64
       at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.setEnvironment(AzureActiveDirectory.java:3)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1070)
       at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1061)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:104)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:941)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:929)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:563)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:87)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:539)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
 As described directly by Crashlytics:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/12443516/9e9e61dd-dda8-43e2-9cb2-29fe83d68f33)

**To Reproduce**
Unknown

Seems to be the same issue as https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1904

**Comment by negoe** [comment]
@m-kubis Thanks for reaching out. We had been occupied with our releases. Please let us know if this is still an issue for you.

**Comment by negoe** [comment]
Closing due to no response.

**Comment by shen-david** [comment]
Hi! We're also encountering this, and it appears to be our #1 most common ANR. Here's stacktrace in two formats - screenshot from google play console, and plaintext

<img width="1610" height="554" alt="Image" src="https://github.com/user-attachments/assets/6e94ada5-b539-4ea6-ae27-8375a7d32806" />
<img width="1600" height="1127" alt="Image" src="https://github.com/user-attachments/assets/2ec73bc3-0e4e-4a1c-9e97-1c0094b8ca37" />

:

```
"main" tid=1 Blocked
  at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.setEnvironment (AzureActiveDirectory.java:3)
  at com.microsoft.identity.client.PublicClientApplication.initializeApplication (PublicClientApplication.java:37)
  at com.microsoft.identity.client.PublicClientApplication.<init> (PublicClientApplication.java:27)
  at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init> (SingleAccountPublicClientApplication.java:1)
  at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted (PublicClientApplication.java:9)
  at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted (PublicClientApplication.java:1)
  at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted (CommandDispatcher.java:9)
  at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000 (CommandDispatcher.java:1)
  at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run (CommandDispatcher.java:39)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8810)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)

"pool-31-thread-1" tid=94 Native
  #00  pc 0x00000000000dc778  /apex/com.android.runtime/lib64/bionic/libc.so (__ppoll+8)
  #01  pc 0x0000000000096e3c  /apex/com.android.runtime/lib64/bionic/libc.so (poll+92)
  #02  pc 0x000000000002b7e0  /apex/com.android.art/lib64/libjavacore.so (Linux_poll+860)
  at libcore.io.Linux.poll (Native method)
  at libcore.io.ForwardingOs.poll (ForwardingOs.java:573)
  at libcore.io.BlockGuardOs.poll (BlockGuardOs.java:283)
  at libcore.io.ForwardingOs.poll (ForwardingOs.java:573)
  at libcore.io.IoBridge.isConnected (IoBridge.java:326)
  at libcore.io.IoBridge.connectErrno (IoBridge.java:237)
  at libcore.io.IoBridge.connect (IoBridge.java:179)
  at java.net.PlainSocketImpl.socketConnect (PlainSocketImpl.java:142)
  at java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:390)
  at java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:230)
  at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:212)
  at java.net.SocksSocketImpl.connect (SocksSocketImpl.java:436)
  at java.net.Socket.connect (Socket.java:646)
  at com.android.okhttp.internal.Platform.connectSocket (Platform.java:182)
  at com.android.okhttp.internal.io.RealConnection.connectSocket (RealConnection.java:145)
  at com.android.okhttp.internal.io.RealConnection.connect (RealConnection.java:116)
  at com.android.okhttp.internal.http.StreamAllocation.findConnection (StreamAllocation.java:186)
  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection (StreamAllocation.java:128)
  at com.android.okhttp.internal.http.StreamAllocation.newStream (StreamAllocation.java:97)
  at com.android.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:289)
  at com.android.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:232)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:465)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse (HttpURLConnectionImpl.java:411)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode (HttpURLConnectionImpl.java:542)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode (DelegatingHttpsURLConnection.java:106)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:30)
  at com.google.firebase.perf.network.c.z (InstrURLConnectionBase.java:8)
  at com.google.firebase.perf.network.b.getInputStream (InstrHttpsURLConnection.java:3)
  at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.getHttpResponse (UrlConnectionHttpClient.java:2)
  at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.executeHttpSend (UrlConnectionHttpClient.java:24)
  at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.a (UrlConnectionHttpClient.java:9)
  at com.microsoft.identity.common.java.net.b.call (R8$$SyntheticClass:5)
  at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt (StatusCodeAndExceptionRetry.java:4)
  at com.microsoft.identity.common.java.net.StatusCodeAndExceptionRetry.attempt (StatusCodeAndExceptionRetry.java:1)
  at com.microsoft.identity.common.java.net.UrlConnectionHttpClient.method (UrlConnectionHttpClient.java:33)
  at com.microsoft.identity.common.java.net.AbstractHttpClient.get (AbstractHttpClient.java:8)
  at com.microsoft.identity.common.java.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery (AzureActiveDirectory.java:65)
  at com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.loadCloudDiscoveryMetadata (AdalMigrationAdapter.java:26)
  at com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.adapt (AdalMigrationAdapter.java:19)
  at com.microsoft.identity.common.internal.migration.TokenMigrationUtility$1.run (TokenMigrationUtility.java:5)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)

```
