### ISSUE TITLE
AccountAdapter$HomeAccountFilter.filter NullPointerException

### ISSUE THREAD

**Issue by m-kubis** [AzureAD/microsoft-authentication-library-for-android#1953]
**Describe the bug**
Production crash from Crashlytics. Single user so far with rising occurrence count (100+ atm and counting).

**Smartphone (please complete the following information):**
 - Device: Zebra Technologies TC57x
 - Android Version: 11
 - Browser: Unknown
 - MSAL Version: 4.9.0

**Stacktrace**
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at java.lang.String.contains(String.java:2224)
       at com.microsoft.identity.client.AccountAdapter$HomeAccountFilter.filter(AccountAdapter.java:86)
       at com.microsoft.identity.client.AccountAdapter.filterCacheRecords(AccountAdapter.java:357)
       at com.microsoft.identity.client.AccountAdapter.adapt(AccountAdapter.java:154)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.getAccountFromICacheRecordList(SingleAccountPublicClientApplication.java:628)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.getPersistedCurrentAccount(SingleAccountPublicClientApplication.java:592)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.access$000(SingleAccountPublicClientApplication.java:84)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication$1$1.onTaskCompleted(SingleAccountPublicClientApplication.java:147)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication$1$1.onTaskCompleted(SingleAccountPublicClientApplication.java:141)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:563)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:87)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:539)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7747)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**To Reproduce**
Unable to reproduce locally.

**Comment by negoe** [comment]
@m-kubis We fixed account adapter related issue in the latest release [4.9.2](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/untagged-93515a0dbf903c7809ad). Please upgrade to this version and let us know if you are still experiencing the issue.
