### ISSUE TITLE
NullPointerException during sing out from ContentProviderStrategy.communicateToBrokerAfterValidation

### ISSUE THREAD

**Issue by peter-grajko** [AzureAD/microsoft-authentication-library-for-android#1961]
**Describe the bug**
Production issue affecting multiple users. NullPointerException is thrown during sign out.

**Smartphone (please complete the following information):**
 - Device: Samsung
 - Android Version: 13
 - Browser: Unknown
 - MSAL Version: 4.10.0

**Stacktrace**
```
Non-fatal Exception: com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:53)
       at com.microsoft.identity.client.PublicClientApplication$9.onError(PublicClientApplication.java:933)
       at com.microsoft.identity.client.PublicClientApplication$9.onError(PublicClientApplication.java:930)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:642)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:99)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:622)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3029)
       at android.os.Parcel.createException(Parcel.java:3007)
       at android.os.Parcel.readException(Parcel.java:2990)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
       at android.content.ContentResolver.query(ContentResolver.java:1226)
       at android.content.ContentResolver.query(ContentResolver.java:1158)
       at android.content.ContentResolver.query(ContentResolver.java:1114)
       at com.microsoft.identity.common.internal.broker.ipc.ContentProviderStrategy.communicateToBrokerAfterValidation(ContentProviderStrategy.java:93)
       at com.microsoft.identity.common.internal.broker.ipc.AbstractIpcStrategyWithServiceValidation.communicateToBroker(AbstractIpcStrategyWithServiceValidation.kt:68)
       at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.performStrategy(BrokerOperationExecutor.java:236)
       at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.execute(BrokerOperationExecutor.java:150)
       at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getDeviceMode(BrokerMsalController.java:811)
       at com.microsoft.identity.common.internal.commands.GetDeviceModeCommand.execute(GetDeviceModeCommand.java:60)
       at com.microsoft.identity.common.internal.commands.GetDeviceModeCommand.execute(GetDeviceModeCommand.java:41)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:542)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:99)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:364)
       at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**To Reproduce**
Unable to reproduce

**Comment by negoe** [comment]
@petergrajkowandera Can you please try upgrading to the [latest ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases) version of MSAL and test again.

**Comment by negoe** [comment]
Closing the issue due to no response. Feel free to reopen if needed.
