### ISSUE TITLE
No static method current()Lio/opentelemetry/context/Context

### ISSUE THREAD

**Issue by yeling** [AzureAD/microsoft-authentication-library-for-android#2025]
@melissaahn Can you help me with this issue?

**Describe the bug**
a development issue
I also create a issue here https://github.com/Azure-Samples/ms-identity-android-java/issues/76

**Smartphone (please complete the following information):**
 - Device: XiaoMi
 - Android Version: [ro.build.version.sdk]: [33]
 - Browser [e.g. Chrome, Edge]
 - MSAL Version
    4.10
 

**Stacktrace**
The stacktrace.
No static method current()Lio/opentelemetry/context/Context; in class Lio/opentelemetry/context/Context; or its super classes (declaration of 'io.opentelemetry.context.Context' appears in /data/app/~~8CPrvi8BZW5Z9icWy5F3zg==/com.azuresamples.msalandroidapp-uMjEMjDR9Vu5SuNEj-XLDg==/base.apk)
java.lang.NoSuchMethodError: No static method current()Lio/opentelemetry/context/Context; in class Lio/opentelemetry/context/Context; or its super classes (declaration of 'io.opentelemetry.context.Context' appears in /data/app/~~8CPrvi8BZW5Z9icWy5F3zg==/com.azuresamples.msalandroidapp-uMjEMjDR9Vu5SuNEj-XLDg==/base.apk)
at com.microsoft.identity.common.java.opentelemetry.OtelContextExtension.wrap(OtelContextExtension.java:57)
at com.microsoft.identity.common.java.controllers.CommandDispatcher.submitSilentReturningFuture(CommandDispatcher.java:341)
at com.microsoft.identity.common.java.controllers.CommandDispatcher.submitSilent(CommandDispatcher.java:181)
at com.microsoft.identity.client.SingleAccountPublicClientApplication$1.onMigrationFinished(SingleAccountPublicClientApplication.java:171)
at com.microsoft.identity.client.PublicClientApplication.performMigration(PublicClientApplication.java:2245)
at com.microsoft.identity.client.SingleAccountPublicClientApplication.getCurrentAccountAsyncInternal(SingleAccountPublicClientApplication.java:175)
at com.microsoft.identity.client.SingleAccountPublicClientApplication.getCurrentAccountAsync(SingleAccountPublicClientApplication.java:118)
at com.azuresamples.msalandroidapp.SingleAccountModeFragment.loadAccount(SingleAccountModeFragment.java:252)
at com.azuresamples.msalandroidapp.SingleAccountModeFragment.access$100(SingleAccountModeFragment.java:69)
at com.azuresamples.msalandroidapp.SingleAccountModeFragment$1.onCreated(SingleAccountModeFragment.java:106)
at com.microsoft.identity.client.PublicClientApplication$11.onCreated(PublicClientApplication.java:1031)
at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:942)
at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:930)
at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:649)
at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:99)
at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:625)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8252)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**To Reproduce**
1.git clone https://github.com/Azure-Samples/ms-identity-android-java.git
2../gradlew build
3.adb install -r ./app/build/outputs/apk/external/debug/app-external-debug.a

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

build environment
Apple M2
macOS Ventura 13.6.3 (22G436)
![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/6251064/10eaf096-dff0-4a58-aed7-c2b5fed79f9e)
![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/6251064/46b16ffe-7318-4d25-a0fa-22b464aff787)

**Expected behavior**

**Actual Behavior**
A description of what actually happened.

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by yeling** [comment]
Finally , I find a solution. Change the minsdk from 21 to 24 in build.gradle file.

The root cause is masl sdk com.microsoft.identity.client depends on  io.opentelemetry:opentelemetry-bom:1.18.0。

And io.opentelemetry uses some java8 features, and it need support android api 21+。I run some tests, I need 24+.

https://github.com/open-telemetry/opentelemetry-java/blob/main/VERSIONING.md

![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/6251064/7051d789-b6e0-4c72-a35c-a3e42a335110)


There are two places about min sdk api level, maybe you can help update them.

https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-android

![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/6251064/d54bf8d5-b58c-4cd0-be63-ca686a518f23)

 

https://github.com/AzureAD/microsoft-authentication-library-for-android

![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/6251064/364b48aa-d6ca-40ee-b955-a4fe600e004a)

**Comment by melissaahn** [comment]
Hi yeling, thanks for creating this issue and letting us know how you solved it. Let me ask our team internally about the min SDK, and I'll get back to you shortly.

**Comment by melissaahn** [comment]
@yeling Wanted to ask some clarifying questions, so that we can get some more context:
1. Does the app get successfully installed on the device, and then the stacktrace you posted is just seen in the logs (does the app still work as expected)? Or does the app not get installed due to such errors?
2. Does using our latest MSAL version 5.0.1 result in a different experience?

Thank you.

**Comment by yeling** [comment]
@melissaahn 
1.The app was installed successfully, and the app work as expected.

2.MSAL version that I use is 4.10.0
   com.microsoft.identity.client:msal:4.+ -> 4.10.0
