### ISSUE TITLE
Error on MsalExceptionAdapter.java line 73 

### ISSUE THREAD

**Issue by lzancan** [AzureAD/microsoft-authentication-library-for-android#2043]
**Describe the bug**
We got the following crash: 
```
Caused by com.microsoft.identity.client.exception.MsalUiRequiredException: AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1708110953, Grant issued time: 1708007529, Grant expiration time: 1708093929
Correlation ID: 587fbdd3-127f-416a-a43b-6d49a228bcd4
Timestamp: 2024-02-16 19:15:53Z
```

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A10
 - Android Version: Android 11
 - MSAL Version 4.5.0

**Stacktrace**
```
    at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:73)
       at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1948)
       at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1939)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:556)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:87)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:536)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`
```

There are other opened issues for this:
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1561
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1216

**Comment by negoe** [comment]
@lzancan 1. Please provide repro steps, what you did, what you expected, what happened instead
2. This Exception should not result in a crash - our `acquireTokenSilent` function declares that it `throws MsalException` (and `MsalUiRequiredException` is a subclass of that), unless you are rethrowing the error, I would expect this to be caught at runtime
3. If you are not catching this error at runtime because you don't know what to do with it, the appropriate fallback for a failed silent request is to try an interactive authentication flow via `acquireToken`

**Comment by negoe** [comment]
closing due to no response.
