### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: uriString

### ISSUE THREAD

**Issue by Javs-21** [AzureAD/microsoft-authentication-library-for-android#2110]
**Describe the bug**
we are having some crashes reported in crashlytics, it's happening in the version 4.7.0

**Smartphone (please complete the following information):**
 - Device: Samsung A32
 - Android Version: 13
 - Browser [e.g. Chrome, Edge]
 - MSAL Version: 4.7.0

**Stacktrace**
Fatal Exception: java.lang.NullPointerException: uriString
       at [android.net](http://android.net/).Uri$StringUri.<init>(Uri.java:504)
       at [android.net](http://android.net/).Uri$StringUri.<init>()
       at [android.net](http://android.net/).Uri.parse(Uri.java:466)
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.validateCustomTabRedirectActivity(PublicClientApplicationConfiguration.java:630)
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:676)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1078)
       at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1062)
       at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:67)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:944)
       at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:930)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:649)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:99)
       at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:625)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:224)
       at android.os.Looper.loop(Looper.java:318)
       at android.app.ActivityThread.main(ActivityThread.java:8772)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Expected behavior**
show the login or no get any crash

**Actual Behavior**
suddenly  get a crash

**Comment by oguncan** [comment]
++
I experienced the same situation. One user encountered 27 crashes. Does anyone have a solution or information?

**Comment by Javs-21** [comment]
I already update the version from `4.7.0` to `5.3.1` and I am still having the issue, looking in internet I watched this [Issue](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1314) that you solved in past, in my case I am passing a configFile, because I can have different logins, so I am using this method 

`public static void createMultipleAccountPublicClientApplication(@NonNull final Context context,
                                                                    @NonNull final File configFile,
                                                                    @NonNull final IMultipleAccountApplicationCreatedListener listener) {

        validateNonNullArgument(context, NONNULL_CONSTANTS.CONTEXT);
        validateNonNullArgument(listener, NONNULL_CONSTANTS.LISTENER);

        runOnBackground(new Runnable() {
            @Override
            public void run() {
                createMultipleAccountPublicClientApplication(
                        initializeConfiguration(context, configFile),
                        listener
                );
            }
        });
    }`

**Comment by negoe** [comment]
@Javs-21 Can you please try to check the config file? Please make sure that is is correctly formatted and includes all necessary fields, particularly the redirectUri.

**Comment by Javs-21** [comment]
@negoe  yes is correct, we are pasign the correct values, we can show the webview with the login but for some reason some users get that crash, the last one was yesterday 
this image in my QA environment
![Captura de pantalla 2024-07-09 a la(s) 4 55 36 p m](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/124821091/f765e71d-360c-4df4-85fe-01d3c3304e76)


this one is in my PROD environment 

![Captura de pantalla 2024-07-09 a la(s) 4 56 39 p m](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/124821091/d289312a-8e5a-4d60-bdc3-fa51bcc694e3)


@negoe please don't ignore me

**Comment by negoe** [comment]
@Javs-21 Can you please share your config file so that we can try reproducing the issue on our side?

**Comment by oguncan** [comment]
@negoe 

{
  "account_mode": "SINGLE",
  "authorities": [
    {
      "audience": {
        "tenant_id": "devjunointranet.onmicrosoft.com",
        "type": "AzureADandPersonalMicrosoftAccount"
      },
      "type": "AAD"
    }
  ],
  "authorization_user_agent": "DEFAULT",
  "broker_redirect_uri_registered": false,
  "client_id": "1b28d7e5-0441-46c2-96c2-ba388b33a6ae",
  "redirect_uri": "msauth://com.juno.intranet/TJh8ynjErPLNjVXA3ymWz4mYDms%3D"
}

I am still getting crashes. I am showing the crash exception messages below;

Fatal Exception: java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:504)
       at android.net.Uri$StringUri.<init>()
       at android.net.Uri.parse(Uri.java:466)
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.validateCustomTabRedirectActivity(PublicClientApplicationConfiguration.java:652)
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:698)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1285)

**Comment by oguncan** [comment]
> [@Javs-21](https://github.com/Javs-21) Can you please share your config file so that we can try reproducing the issue on our side?

Can you explain why I still get this crash if I provide the config file information?
