### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "cz.msebera.android.httpclient.client.utils.URIBuilder"

### ISSUE THREAD

**Issue by Im-flying-sparrow** [AzureAD/microsoft-authentication-library-for-android#2191]
The app crash when create an MSAL PublicClientApplication

 - Device: All Device
 - Android Version: All Version
 - Browser: None
 - MSAL Version: 4.9.+

`java.lang.NoClassDefFoundError: Failed resolution of: Lcz/msebera/android/httpclient/client/utils/URIBuilder;
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.getGsonForLoadingConfiguration(PublicClientApplicationConfigurationFactory.java:180)
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:167)
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:120)
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:71)
                                                    	at com.microsoft.identity.client.PublicClientApplication$6.run(PublicClientApplication.java:655)
                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cz.msebera.android.httpclient.client.utils.URIBuilder" on path: DexPathList[[zip file "/data/app/~~IuyARbxH0R4JtJceSzBiWQ==/kr.co.ksystem.forms-Wt8YcaKLcqOkwcC2YN8fCA==/base.apk"],nativeLibraryDirectories=[/data/app/~~IuyARbxH0R4JtJceSzBiWQ==/kr.co.ksystem.forms-Wt8YcaKLcqOkwcC2YN8fCA==/lib/arm64, /data/app/~~IuyARbxH0R4JtJceSzBiWQ==/kr.co.ksystem.forms-Wt8YcaKLcqOkwcC2YN8fCA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.getGsonForLoadingConfiguration(PublicClientApplicationConfigurationFactory.java:180) 
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:167) 
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration(PublicClientApplicationConfigurationFactory.java:120) 
                                                    	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:71) 
                                                    	at com.microsoft.identity.client.PublicClientApplication$6.run(PublicClientApplication.java:655) 
                                                    	at java.lang.Thread.run(Thread.java:1012) `

It looks the same as the issue in the link below.
[NoClassDefFoundError version upgrade from 2.2.3 -> 3.0.2 #1921](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1921)

**Comment by Im-flying-sparrow** [comment]
And NoClassDefFoundError URIBuilder using MSAL 4.2.0 for Android #1797 [https://github.com/AzureAD/microsoft-authentication-library-for-android/discussions/1797](url) It looks the same as the issue too.

**Comment by Im-flying-sparrow** [comment]
It operates normally after build clean.
