### ISSUE TITLE
Andriod 15 Failed to get result from Broker Content Provider

### ISSUE THREAD

**Issue by chuckz1321** [AzureAD/microsoft-authentication-library-for-android#2232]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.
Unable to auth with Authenticator installed. Need to reinstall the Authenticator. 

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel, OnePlus 6, etc] Xiaomi Huawei
 - Android Version: [e.g. API Level, Build Number] Andriod 15
 - Browser [e.g. Chrome, Edge]
 - MSAL Version

**Stacktrace**
If a crash occurs, include the stacktrace.
2024-12-16 11:17:48.654 16737-18286 ActivityThread         xxxxx                E  Failed to find provider info for com.azure.authenticator.microsoft.identity.broker
2024-12-16 11:17:48.654 16737-18176 ContentPro...teToBroker xxxx                E  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Failed to get result from Broker Content Provider, cursor is null  
2024-12-16 11:17:48.655 16737-18176 BrokerOper...DeviceMode xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Executing with IIpcStrategy: BoundServiceStrategy  
2024-12-16 11:17:48.655 16737-18176 BrokerOperationBundle   xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Requested Active Broker Data  
2024-12-16 11:17:48.655 16737-18176 BoundServi...teToBroker xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Broker operation: MSAL_GET_DEVICE_MODE brokerPackage: com.azure.authenticator  
2024-12-16 11:17:48.657 16737-16737 MiuiMultiWindowUtils    xxxx                D  freeform resolution args raw data:{  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}    },    "mini_freeform_args":{        "vertical_portrait":{"original_ratio":0.147},        "horizontal_portrait":{"original_ratio":0.147},        "vertical_landscape":{"original_ratio":0.165},        "horizontal_landscape":{"original_ratio":0.165}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}    },    "mini_freeform_args":{        "vertical_portrait":{"original_ratio":0.26},        "horizontal_portrait":{"original_ratio":0.26},        "vertical_landscape":{"original_ratio":0.293},        "horizontal_landscape":{"original_ratio":0.293}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.4244,"top_margin":0.109,"left_margin":-1},      "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.4244,"top_margin":-1,"left_margin":0.026}    },    "mini_freeform_args":{      "vertical_portrait":{"original_ratio":0.25},      "horizontal_portrait":{"original_ratio":0.25},      "vertical_landscape":{"original_ratio":0.25},      "horizontal_landscape":{"original_ratio":0.25}    }  },  "pad_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.375,"original_scale":0.835,"top_margin":0.049,"left_margin":0.2775},      "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.375,"original_scale":0.835,"top_margin":-1,"left_margin":0.6525},      "vertical_landscape":{"aspect_ratio":-1, "original_ratio":1,"original_scale":0.468,"top_margin":0.049,"left_margin":-1},      "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":1,"original_scale":0.468,"top_margin":-1,"left_margin":0.4976}    },    "mini_freeform_args":{      "vertical_portrait":{"original_ratio":0.144},      "horizontal_portrait":{"original_ratio":0.144},      "vertical_landscape":{"original_ratio":0.2},      "horizontal_landscape":{"original_ratio":0.2}    }  }}
2024-12-16 11:17:48.657 16737-16737 MiuiMultiWindowUtils    xxxx                D  initFreeFormResolutionArgs failed, device is haotian
2024-12-16 11:17:48.657 16737-16737 IS_CTS_MODE             xxxx                D  false
2024-12-16 11:17:48.657 16737-16737 MULTI_WIND...CH_ENABLED xxxx                D  false
2024-12-16 11:17:48.658 16737-18176 BoundServi...nt:connect xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] failed to bind. The service is not available.  
2024-12-16 11:17:48.658 16737-18176 BrokerOper...DeviceMode xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Executing with IIpcStrategy:    
2024-12-16 11:17:48.658 16737-18176 BrokerOperationBundle   xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Requested Active Broker Data  
2024-12-16 11:17:48.658 16737-18176 AccountMan...teToBroker xxxx                I  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Broker operation: MSAL_GET_DEVICE_MODE brokerPackage: com.azure.authenticator  
2024-12-16 11:17:48.660 16737-18176 AccountMan...teToBroker xxxxx                V  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] Received result from broker  
2024-12-16 11:17:48.661 16737-18176 AccountMan...teToBroker xxxx                E  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] bind failure  
                                                                                                    android.accounts.AuthenticatorException: bind failure
                                                                                                    	at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2658)
                                                                                                    	at android.accounts.AccountManager.-$$Nest$mconvertErrorToException(Unknown Source:0)
                                                                                                    	at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2494)
                                                                                                    	at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:105)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1512)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1451)
2024-12-16 11:17:48.661 16737-18176 BrokerOper...or:execute xxxx                E  [2024-12-16 03:17:48 - thread_id: 3177, correlation_id: 232c43c9-3afb-4d4a-a83a-78f76ac91f03 - Android 35] [ipc_return_null_cursor] [content_provider] :Failed to get result from Broker Content Provider, cursor is null  
                                                                                                    com.microsoft.identity.common.exception.BrokerCommunicationException: [ipc_return_null_cursor] [content_provider] :Failed to get result from Broker Content Provider, cursor is null
                                                                                                    	at com.microsoft.identity.common.internal.broker.ipc.ContentProviderStrategy.communicateToBrokerAfterValidation(ContentProviderStrategy.java:132)
                                                                                                    	at com.microsoft.identity.common.internal.broker.ipc.AbstractIpcStrategyWithServiceValidation.communicateToBroker(AbstractIpcStrategyWithServiceValidation.kt:66)
                                                                                                    	at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.performStrategy(BrokerOperationExecutor.java:236)
                                                                                                    	at com.microsoft.identity.common.internal.controllers.BrokerOperationExecutor.execute(BrokerOperationExecutor.java:150)
                                                                                                    	at com.microsoft.identity.common.internal.controllers.BrokerMsalController.getDeviceMode(BrokerMsalController.java:888)
                                                                                                    	at com.microsoft.identity.common.internal.commands.GetDeviceModeCommand.execute(GetDeviceModeCommand.java:54)
                                                                                                    	at com.microsoft.identity.common.internal.commands.GetDeviceModeCommand.execute(GetDeviceModeCommand.java:42)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:539)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$100(CommandDispatcher.java:98)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher$1.run(CommandDispatcher.java:364)
                                                                                                    	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
                                                                                                    	at io.opentelemetry.context.Context$$ExternalSyntheticLambda4.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**To Reproduce**
configuration
![image](https://github.com/user-attachments/assets/a275135b-7c5b-4053-86ca-6b08c7ccd526)

If related to user experience, use the format:

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
Able to login from App

**Actual Behavior**
A description of what actually happened.
Cannot Login, with exceptions 

Tried the latest MSAL version, issue persists. Please share some insights on this issue. All devices are Andriod 15, is that related? 

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by jyrwm** [comment]
设备：小米15 pro
Android 版本：Andriod 15
浏览器：webview
MSAL ：5.8.2

**Comment by melissaahn** [comment]
Hi @jyrwm , after reinstalling Authenticator, does the issue repro?
