### ISSUE TITLE
Cancel button on the registration process cause RuntimeException

### ISSUE THREAD

**Issue by jrodriguezpuigvert** [AzureAD/microsoft-authentication-library-for-android#227]
In the broker the user can choose the option to "sign up now". 
Then appears a registration web with a Create and a Cancel Button. If I press cancel, the app crashes with the following error **: URLDecoder: Illegal hex characters in escape (%) pattern : %u0**

Nexus 5X
Android 8.0.0

>  Process: de.app, PID: 26259
                                                                                java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2003, data=Intent { (has extras) }} to activity {de.app/de.app.LoginActivity}: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %u0
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
                                                                                    at android.app.ActivityThread.-wrap19(Unknown Source:0)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                 Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %u0
                                                                                    at java.net.URLDecoder.decode(URLDecoder.java:177)
                                                                                    at com.microsoft.identity.client.MsalUtils.urlFormDecode(MsalUtils.java:127)
                                                                                    at com.microsoft.identity.client.MsalUtils.decodeUrlToMap(MsalUtils.java:298)
                                                                                    at com.microsoft.identity.client.AuthorizationResult.parseAuthorizationResponse(AuthorizationResult.java:94)
                                                                                    at com.microsoft.identity.client.AuthorizationResult.create(AuthorizationResult.java:72)
                                                                                    at com.microsoft.identity.client.InteractiveRequest.onActivityResult(InteractiveRequest.java:157)
                                                                                    at com.microsoft.identity.client.PublicClientApplication.handleInteractiveRequestRedirect(PublicClientApplication.java:313)
                                                                                    at de.app.LoginActivity.onActivityResult(LoginActivity.java:257)
                                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:7235)
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367) 
                                                                                    at android.app.ActivityThread.-wrap19(Unknown Source:0) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
10-16 09:29:49.392 26259-27245/de.app E/BaseRequest: MSAL 0.1.1 Android 26 [2017-10-16 07:29:49 - 27b7d43f-f083-478f-8873-419ea7df1994] Error occurred during authentication. com.microsoft.identity.client.MsalClientException: Receives empty result for authorize request
                                                                                 at com.microsoft.identity.client.InteractiveRequest.processAuthorizationResult(InteractiveRequest.java:270)
                                                                                 at com.microsoft.identity.client.InteractiveRequest.preTokenRequest(InteractiveRequest.java:126)
                                                                                 at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:106)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                 at java.lang.Thread.run(Thread.java:764)

**Comment by temirlannurdinov** [comment]
Still appears. 
In Spanish locale. When trying to push cancel button, app crashes. 

 >2018-09-19 09:39:37.209 30913-30913 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: some.p, PID: 30913
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2003, data=Intent { (has extras) }} to activity {.ui.splash.SignUpActivity}: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %u0
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4284)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %u0
        at java.net.URLDecoder.decode(URLDecoder.java:177)
        at com.microsoft.identity.client.MsalUtils.urlFormDecode(MsalUtils.java:127)
        at com.microsoft.identity.client.MsalUtils.decodeUrlToMap(MsalUtils.java:300)
        at com.microsoft.identity.client.AuthorizationResult.parseAuthorizationResponse(AuthorizationResult.java:94)
        at com.microsoft.identity.client.AuthorizationResult.create(AuthorizationResult.java:72)
        at com.microsoft.identity.client.InteractiveRequest.onActivityResult(InteractiveRequest.java:158)

**Comment by Om83** [comment]
@temirlannurdinov can you please confirm if this is still happening on latest broker?

**Comment by iambmelt** [comment]
Closing due to inactivity
