### ISSUE TITLE
[BUG ?] Unable to stop activity: ... on .getCustomTabsServiceIsBound()

### ISSUE THREAD

**Issue by jaragones** [AzureAD/microsoft-authentication-library-for-android#244]
I'm getting a reported crash that I'm not sure what it could be causing it from my side. Any help or clue would be appreciated. :)

Reported crash:
```java
Unable to stop activity {com.zynbit.app/com.microsoft.identity.client.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference

>>>

Fatal Exception: java.lang.RuntimeException: Unable to stop activity {com.zynbit.app/com.microsoft.identity.client.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3504)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3554)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
       at com.microsoft.identity.client.AuthenticationActivity.onStop(AuthenticationActivity.java:114)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1278)
       at android.app.Activity.performStop(Activity.java:6395)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3501)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3554)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by iambmelt** [comment]
Hi @jaragones - Thank you for filing this issue; apologies for any inconvenience.

Wanted to confirm, this appears to be a bug in the binding/unbinding logic of `CustomTabService`. I'll be working up a fix for this today.

**Comment by jaragones** [comment]
Looks like by the fabric.io information but I can't reproduce this issue on any of my accounts to provide you further information about it. Let me know, if I can do anything to help on it. Thanks for your work!

**Comment by iambmelt** [comment]
@jaragones No problem! Pull request is open [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/247).

From my investigation, [`onStop()` checks if a service is bound](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/AuthenticationActivity.java#L114) without checking that the connection has been initialized. Because it is [conditionally created](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/AuthenticationActivity.java#L106-L108) (depending on platform support), it can be null (causing this crash).

**Comment by jaragones** [comment]
@iambmelt just another question. I'm getting this library into my android project doing:

    compile('com.microsoft.identity.client:msal:0.1.+') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }

if I check external libraries, I can see that your changes (that seems merged to branch dev) are not imported, should I assume that gradle only gets what it is on release tab or master and it is not updated there? Or am I doing something wrong?

Thanks for your help.

**Comment by iambmelt** [comment]
Hi @jaragones - Nope, you've done everything correctly. There are a few more changes in the works for the `dev` branch before we deploy our next version. Our releases also go through an internal/partner test-cycle prior to publication so some amount of latency from change to deployment is expected.

If you're looking to take these changes while still in `alpha` you can build these changes from source (via `clone` or [zip](https://github.com/AzureAD/microsoft-authentication-library-for-android/archive/dev.zip)) or as less-involved alternative, use a 3rd party loader such as [JitPack](https://jitpack.io).

I hope this helps!

**Comment by jaragones** [comment]
Thanks for your reply!
