### ISSUE TITLE
IllegalArgumentException when encountering errors from non-english languages

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#253]
https://stackoverflow.com/questions/48552603/ad-b2c-msal-integration-for-android-fails-upon-profile-policy-cancellation-in-sp

Occurred with French and Spanish accent marks when using Azure AD B2C on an expected error case (user cancel). 

```
java.lang.IllegalArgumentException: Invalid % sequence at 50: AADB2C90091:+El+usuario+ha+cancelado+la+introducci%u00f3n+de+informaci%u00f3n+afirmada+por+%u00e9l+mismo.
              Correlation+ID:+c413b66a-4a69-43d2-8a3c-6111cea7f1b0
              Timestamp:+2018-01-28+20:33:39Z

                  at android.app.ActivityThread.deliverResults(ActivityThread.java:4067)
                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:4110)
                  at android.app.ActivityThread.access$1400(ActivityThread.java:177)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:145)
                  at android.app.ActivityThread.main(ActivityThread.java:5953)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at java.lang.reflect.Method.invoke(Method.java:372)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
               Caused by: java.lang.IllegalArgumentException: Invalid % sequence at 50: AADB2C90091:+El+usuario+ha+cancelado+la+introducci%u00f3n+de+informaci%u00f3n+afirmada+por+%u00e9l+mismo.
              Correlation+ID:+c413b66a-4a69-43d2-8a3c-6111cea7f1b0
              Timestamp:+2018-01-28+20:33:39Z

                  at libcore.net.UriCodec.decode(UriCodec.java:169)
                  at java.net.URLDecoder.decode(URLDecoder.java:60)
                  at com.microsoft.identity.client.MsalUtils.urlFormDecode(MsalUtils.java:127)
                  at com.microsoft.identity.client.MsalUtils.decodeUrlToMap(MsalUtils.java:298)
                  at com.microsoft.identity.client.AuthorizationResult.parseAuthorizationResponse(AuthorizationResult.java:94)
                  at com.microsoft.identity.client.AuthorizationResult.create(AuthorizationResult.java:72)
                  at com.microsoft.identity.client.InteractiveRequest.onActivityResult(InteractiveRequest.java:157)
                  at com.microsoft.identity.client.PublicClientApplication.handleInteractiveRequestRedirect(PublicClientApplication.java:313)
                  at com.tekmar.msal.TekmarMSAL.onActivityResult(TekmarMSAL.java:200)
                  at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
                  at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:358)
                  at android.app.Activity.dispatchActivityResult(Activity.java:6549)
                  at android.app.ActivityThread.deliverResults(ActivityThread.java:4063)
```

**Comment by jpittman01** [comment]
Any updates on this or ETA for getting resolved?  It is preventing us from going live with a new solution for a customer.

**Comment by iambmelt** [comment]
@danieldobalian I suggest we coordinate w/ B2C resources on this - I suspect this is misbehavior on the server end:

- [RFC 3986 S. 2.5](https://tools.ietf.org/html/rfc3986#section-2.5) advises implementers to use UTF-8

>When a new URI scheme defines a component that represents textual data consisting of characters from the Universal Character Set [UCS], **the data should first be encoded as octets according to the UTF-8 character encoding [STD63]**; then only those octets that do not correspond to characters in the unreserved set should be percent- encoded. For example, the character A would be represented as "A", the character LATIN CAPITAL LETTER A WITH GRAVE would be represented as "%C3%80", and the character KATAKANA LETTER A would be represented as "%E3%82%A2".

For form params, [UTF-8 is also suggested by the W3C](https://www.w3.org/TR/html40/appendix/notes.html#non-ascii-chars)

And Java's [URLDecoder#decode](https://docs.oracle.com/javase/6/docs/api/java/net/URLDecoder.html#decode(java.lang.String,%20java.lang.String)) cites the above W3C recommendation, while warning of incompatibilities (emphasis mine)

>Decodes a application/x-www-form-urlencoded string using a specific encoding scheme. The supplied encoding is used to determine what characters are represented by any consecutive sequences of the form "%xy".
**Note: The World Wide Web Consortium Recommendation states that UTF-8 should be used. Not doing so may introduce incompatibilites.**

In theory we could coordinate with the server to send an [`Accept-Charset`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset) which we use to optionally support alternate charsets: the preferred solution IMO is to properly UTF-8 encode all URLs.

**Comment by iambmelt** [comment]
Not aware of any recurrences of this issue - will reopen if necessary
