### ISSUE TITLE
[branch: unified/dev] Mockito-Android warns on pass, Mockito-Core fails outright

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#284]
See https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/282#discussion_r185518238 for context

`mockito-android` emits the following warning when tests are run:
```
IMPORTANT NOTE FROM MOCKITO:

You included the 'mockito-android' dependency in a non-Android environment.
The Android mock maker was disabled. You should only include the latter in your 'androidTestCompile' configuration
If disabling was a mistake, you can set the 'org.mockito.mock.android' property to 'true' to override this detection.

Visit https://javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.1 for more information

Process finished with exit code 0
```

because the dependencies are declared thusly:

```groovy
dependencies {
    // test dependencies
    testImplementation "junit:junit:$rootProject.ext.junitVersion"

    // TODO the below dependency should be mockito-core but the MockMaker isn't working...
    testImplementation "org.mockito:mockito-android:$rootProject.ext.mockitoAndroidVersion"

    // instrumentation test dependencies
    androidTestImplementation "com.android.support.test:runner:$rootProject.ext.runnerVersion"

    // Set this dependency to use JUnit 4 rules
    androidTestImplementation "com.android.support.test:rules:$rootProject.ext.rulesVersion"
    androidTestImplementation "org.mockito:mockito-android:$rootProject.ext.mockitoAndroidVersion"
}
```

But it really _should_ be declared as:
```groovy
dependencies {
    // test dependencies
    testImplementation "junit:junit:$rootProject.ext.junitVersion"

    // TODO the below dependency should be mockito-core but the MockMaker isn't working...
    testImplementation "org.mockito:mockito-core:$rootProject.ext.mockitoVersion" // <-- Should use 'core' for non-instrumented tests

    // instrumentation test dependencies
    androidTestImplementation "com.android.support.test:runner:$rootProject.ext.runnerVersion"

    // Set this dependency to use JUnit 4 rules
    androidTestImplementation "com.android.support.test:rules:$rootProject.ext.rulesVersion"
    androidTestImplementation "org.mockito:mockito-android:$rootProject.ext.mockitoAndroidVersion"
}
```

But when it's declared 'correctly' tests fail with:
```java
java.lang.AbstractMethodError: com.google.dexmaker.mockito.DexmakerMockMaker.isTypeMockable(Ljava/lang/Class;)Lorg/mockito/plugins/MockMaker$TypeMockability;

	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:232)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
	at org.mockito.Mockito.mock(Mockito.java:1875)
	at org.mockito.Mockito.mock(Mockito.java:1784)
	at com.microsoft.identity.client.MockUtil.getCommonHttpUrlConnection(MockUtil.java:68)
	at com.microsoft.identity.client.MockUtil.getMockedConnectionWithSocketTimeout(MockUtil.java:61)
	at com.microsoft.identity.client.HttpRequestTest.testGetFailedWithSocketTimeoutRetryFailedWithSocketTimeout(HttpRequestTest.java:585)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by Om83** [comment]
@iambmelt  can this be closed now?

**Comment by iambmelt** [comment]
@Om83 Providing status: this issue still exists but is of low-pri. The tests execute, despite warnings informing us that the wrong dependency is being used. "Fixing" the issue per the documentation breaks the tests 😕

**Comment by iambmelt** [comment]
@Om83 Given this isn't a call to action, I will close. We can reactivate later if this becomes pri
