### ISSUE TITLE
java.lang.RuntimeException: Unable to stop activity

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#307]
```07-20 15:03:21.650 13957-13957/com.microsoft.identity.client.sample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.microsoft.identity.client.sample, PID: 13957
java.lang.RuntimeException: Unable to stop activity {com.microsoft.identity.client.sample/com.microsoft.identity.client.AuthenticationActivity}: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.client.MsalChromeCustomTabManager$MsalCustomTabsServiceConnection@a73717a
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4557)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4618)
    at android.app.ActivityThread.-wrap7(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6692)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.client.MsalChromeCustomTabManager$MsalCustomTabsServiceConnection@a73717a
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1352)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1553)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:708)
    at com.microsoft.identity.client.MsalChromeCustomTabManager.unbindCustomTabsService(MsalChromeCustomTabManager.java:127)
    at com.microsoft.identity.client.AuthenticationActivity.onStop(AuthenticationActivity.java:150)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
    at android.app.Activity.performStop(Activity.java:7138)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4552)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4618) 
    at android.app.ActivityThread.-wrap7(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6692) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by iambmelt** [comment]
@heidijinxujia Which branch is this on? Is it related to #297?
