### ISSUE TITLE
[B2C - Common Integration] com.microsoft.identity.client.MsalClientException: Failed to save tokens.

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#308]
Update the stacktrace and log
```Failed to save tokens
07-24 11:30:46.985 26446-27246/? I/MicrosoftAccount:getUniqueId:  [2018-07-24 18:30:46 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] Using ObjectId as uniqueId Android 24
07-24 11:30:46.987 26446-27246/? V/MicrosoftStsAccount:  [2018-07-24 18:30:46 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] Init: MicrosoftStsAccount Android 24
07-24 11:30:46.990 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:46 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] Account does not contain all required fields. Android 24
07-24 11:30:46.994 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:46 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] home_account_id is null? [false] Android 24
07-24 11:30:46.997 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:46 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] environment is null? [false] Android 24
07-24 11:30:46.999 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:46 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] realm is null? [true] Android 24
07-24 11:30:47.001 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] local_account_id is null? [false] Android 24
07-24 11:30:47.003 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] username is null? [true] Android 24
07-24 11:30:47.005 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] authority_type is null? [false] Android 24
07-24 11:30:47.008 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] AccessToken does not contain all required fields. Android 24
07-24 11:30:47.010 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] credential_type is null? [false] Android 24
07-24 11:30:47.012 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] home_account_id is null? [false] Android 24
07-24 11:30:47.014 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] realm is null? [true] Android 24
07-24 11:30:47.016 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] environment is null? [false] Android 24
07-24 11:30:47.018 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] client_id is null? [false] Android 24
07-24 11:30:47.021 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] target is null? [false] Android 24
07-24 11:30:47.023 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] cached_at is null? [false] Android 24
07-24 11:30:47.025 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] expires_on is null? [false] Android 24
07-24 11:30:47.027 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] secret is null? [false] Android 24
07-24 11:30:47.029 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] IdToken does not contain all required fields. Android 24
07-24 11:30:47.031 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] home_account_id is null? [false] Android 24
07-24 11:30:47.034 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] environment is null? [false] Android 24
07-24 11:30:47.037 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] realm is null? [true] Android 24
07-24 11:30:47.039 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] credential_type is null? [false] Android 24
07-24 11:30:47.041 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] client_id is null? [false] Android 24
07-24 11:30:47.042 26446-27246/? W/MsalOAuth2TokenCache:isSchemaCompliant:  [2018-07-24 18:30:47 - {"thread_id":"6786","correlation_id":"cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd"}] secret is null? [false] Android 24
07-24 11:30:47.046 26446-27246/? E/BaseRequest:  [2018-07-24 18:30:47 - cbfdfdf3-f88d-42c4-86fc-ab3d7ebb04dd] Error occurred during authentication. SDK ver:0.1.1 Android 24
com.microsoft.identity.client.MsalClientException: Failed to save tokens.
    at com.microsoft.identity.client.TokenCache.saveTokensToCommonCache(TokenCache.java:142)
    at com.microsoft.identity.client.BaseRequest.postTokenRequest(BaseRequest.java:219)
    at com.microsoft.identity.client.InteractiveRequest.postTokenRequest(InteractiveRequest.java:227)
    at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
    Caused by: com.microsoft.identity.common.exception.ClientException
    at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.validateCacheArtifacts(MsalOAuth2TokenCache.java:203)
    at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.saveTokens(MsalOAuth2TokenCache.java:152)
    at com.microsoft.identity.client.TokenCache.saveTokensToCommonCache(TokenCache.java:139)
    at com.microsoft.identity.client.BaseRequest.postTokenRequest(BaseRequest.java:219) 
    at com.microsoft.identity.client.InteractiveRequest.postTokenRequest(InteractiveRequest.java:227) 
    at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:112) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
    at java.lang.Thread.run(Thread.java:762)

**Comment by iambmelt** [comment]
@heidijinxujia Specifically the `realm` was absent from the `Account`, `AccessToken`, and `IdToken`, correct?

**Comment by heidijinxujia** [comment]
@iambmelt  Please refer to here https://github.com/AzureAD/microsoft-authentication-library-common-for-android/compare/34558961aafee785f89a8df6a40e163bcb90a341...85cf210eb89614d358711216273279a84c24c9cf#diff-aafccf05a87e17ad20add6611f0e94d0

**Comment by iambmelt** [comment]
Closing old/invalid
