### ISSUE TITLE
Android O StrictMode: Untagged socket detected

### ISSUE THREAD

**Issue by MatkovIvan** [AzureAD/microsoft-authentication-library-for-android#317]
# Reproduction steps
1. Set `VmPolicy` to `detectAll`;
2. Use the SDK;

# Stacktrace
```
E/StrictMode: null
    java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
        at libcore.io.IoBridge.socket(IoBridge.java:667)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
        at java.net.Socket.createImpl(Socket.java:484)
        at java.net.Socket.getImpl(Socket.java:547)
        at java.net.Socket.setSoTimeout(Socket.java:1175)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at com.microsoft.identity.client.HttpRequest.executeHttpSend(HttpRequest.java:191)
        at com.microsoft.identity.client.HttpRequest.sendWithRetry(HttpRequest.java:157)
        at com.microsoft.identity.client.HttpRequest.send(HttpRequest.java:138)
        at com.microsoft.identity.client.HttpRequest.sendGet(HttpRequest.java:129)
        at com.microsoft.identity.client.Oauth2Client.executeHttpRequest(Oauth2Client.java:140)
        at com.microsoft.identity.client.Oauth2Client.discoverEndpoints(Oauth2Client.java:113)
        at com.microsoft.identity.client.Authority.resolveEndpoints(Authority.java:155)
        at com.microsoft.identity.client.BaseRequest.preTokenRequest(BaseRequest.java:61)
        at com.microsoft.identity.client.InteractiveRequest.preTokenRequest(InteractiveRequest.java:91)
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by iambmelt** [comment]
Closing as not a current priority (3 yr old ask); doesn't appear to present any real-world authn issues
