### ISSUE TITLE
Signed AAR and jetifier causes unit test failures

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#455]
I am experiencing an issue similar to https://stackoverflow.com/questions/53224778/androidx-jetifier-mockito-java-lang-securityexception-sha-256-digest-error-for

I am using AndroidX + jetifier.
```
android.useAndroidX=true
android.enableJetifier=true
```

I have a JUnit4 test which instantiates an MSAL class:
```
@Test
    fun myTest() {
        MsalUiRequiredException("")
    }
```

When I run this test I get the following exception:
```
java.lang.SecurityException: SHA-256 digest error for com/microsoft/identity/client/exception/MsalUiRequiredException.class

	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:218)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:241)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:482)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.example.TestClass.myTest(TestClass.kt:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.example.TestClass.testutils.TrampolineSchedulerRule$apply$1.evaluate(TrampolineSchedulerRule.kt:28)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

The cause is that:
1. The MSAL AAR is signed.
2. Jetifier rewrites the classes.jar
As a result, the manifest signatures not longer match.

I was able to workaround this by deleting the manifest files in the re-written jar. This is not a permanent workaround, however, as I made the change in my local gradle cache.

Could MSAL remove the signing?

**Comment by wyber** [comment]
There is a similar bug submitted with Google already:
https://issuetracker.google.com/issues/115556774

**Comment by joshfriend** [comment]
[Here's my temporary workaround](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/354#issuecomment-475282552)

**Comment by iambmelt** [comment]
Related: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/702

**Comment by iambmelt** [comment]
Newer releases are no longer signed -- AndroidX compatibility should no longer be an issue
