### ISSUE TITLE
[B2C] Fatal Crash: NullPointerException on invalid_grant

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#472]
```java
2018-12-03 14:15:03.866 7813-29445/com.example.brianmel.msalsampleapp V/OAuth2Strategy:requestToken:  [2018-12-03 22:15:03 - {"thread_id":"17721","correlation_id":"0d195b9b-ba14-4d46-8036-15ee75be0533"}] Requesting token... Android 28
2018-12-03 14:15:03.867 7813-29445/com.example.brianmel.msalsampleapp V/OAuth2Strategy:performTokenRequest:  [2018-12-03 22:15:03 - {"thread_id":"17721","correlation_id":"0d195b9b-ba14-4d46-8036-15ee75be0533"}] Performing token request... Android 28
2018-12-03 14:15:06.448 7813-29445/com.example.brianmel.msalsampleapp V/MicrosoftStsOAuth2Strategy:getTokenResultFromHttpResponse:  [2018-12-03 22:15:06 - {"thread_id":"17721","correlation_id":"0d195b9b-ba14-4d46-8036-15ee75be0533"}] Getting TokenResult from HttpResponse... Android 28
2018-12-03 14:15:06.467 7813-29445/com.example.brianmel.msalsampleapp V/TokenResult:  [2018-12-03 22:15:06 - {"thread_id":"17721","correlation_id":"0d195b9b-ba14-4d46-8036-15ee75be0533"}] Init: TokenResult Android 28
2018-12-03 14:15:06.467 7813-29445/com.example.brianmel.msalsampleapp W/LocalMSALController:  [2018-12-03 22:15:06 - {"thread_id":"17721","correlation_id":"0d195b9b-ba14-4d46-8036-15ee75be0533"}] invalid_grant Android 28
2018-12-03 14:15:06.467 7813-29445/com.example.brianmel.msalsampleapp W/LocalMSALController:  [2018-12-03 22:15:06 - {"thread_id":"17721","correlation_id":"0d195b9b-ba14-4d46-8036-15ee75be0533"}] AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_SISOPolicy and Expected Value : B2C_1_SignInPolicy
    Correlation ID: d2b07b56-7546-4cd6-aaa1-ea6754f2ffe5
    Timestamp: 2018-12-03 22:15:06Z
     Android 28
2018-12-03 14:15:06.481 7813-29445/com.example.brianmel.msalsampleapp E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
    Process: com.example.brianmel.msalsampleapp, PID: 7813
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.microsoft.identity.common.internal.providers.oauth2.AuthorizationResult com.microsoft.identity.client.internal.controllers.AcquireTokenResult.getAuthorizationResult()' on a null object reference
        at com.microsoft.identity.client.internal.controllers.ExceptionAdapter.exceptionFromAcquireTokenResult(ExceptionAdapter.java:46)
        at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher$2.run(MSALApiDispatcher.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by iambmelt** [comment]
Closing with no repro in latest version, will reopen if recurs
