### ISSUE TITLE
Using domain_hint causes MSAL exception

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#537]
When using `acquireToken` with a domain hint, the MSAL logger generates an exception.

My code:

```
        List temp = new ArrayList<String>();
        temp.add("domain_hint=facebook.com");
        sampleApp.acquireToken(
                getActivity(),
                SCOPES,
                (String) null,
                UiBehavior.SELECT_ACCOUNT,
                temp,
                getAuthInteractiveCallback());
```

Exception
```
                  java.lang.ClassCastException: java.lang.String cannot be cast to android.util.Pair
                      at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher.logInteractiveRequestParameters(MSALApiDispatcher.java:174)
                      at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher.access$000(MSALApiDispatcher.java:39)
                      at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher$1.run(MSALApiDispatcher.java:61)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
```

**Comment by danieldobalian** [comment]
Fixed! This overload requires a List of Pairs.

 ```         
ArrayList<Pair<String, String>>();
```
