### ISSUE TITLE
CustomTabsService failed binding on Huawei Device

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#549]
Install MSAL test app on Huawei Mate device.
Initiate interactive auth.
Observe error message.

```java
2019-03-22 14:37:39.090 8373-8536/com.microsoft.identity.client.sample.local E/ApiDispatcher:beginInteractive:  [2019-03-22 21:37:39 - {"thread_id":"485","correlation_id":"77892acc-d2b0-4498-9adc-3a2a3b0931c6"}] Interactive request failed with Exception Android 26
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.customtabs.CustomTabsSession android.support.customtabs.CustomTabsClient.newSession(android.support.customtabs.CustomTabsCallback)' on a null object reference
        at com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.bind(CustomTabsManager.java:102)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.requestAuthorization(BrowserAuthorizationStrategy.java:83)
        at com.microsoft.identity.common.internal.providers.oauth2.OAuth2Strategy.requestAuthorization(OAuth2Strategy.java:93)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.performAuthorizationRequest(LocalMSALController.java:139)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:93)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:59)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1.run(ApiDispatcher.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by heidijinxujia** [comment]
Fixing here. https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/432
