### ISSUE TITLE
NPE on PublicClientApplication handler init

### ISSUE THREAD

**Issue by titorodi** [AzureAD/microsoft-authentication-library-for-android#568]
MSAL has a NPE to fix:

https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/f05e13f92815f1049746f5299a5b638f08db52c1/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L369

 Caused by: java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference

2019-04-10 10:51:42.692 27347-27398/? W/System.err:     at android.os.Handler.<init>(Handler.java:233)

2019-04-10 10:51:42.692 27347-27398/? W/System.err:     at android.os.Handler.<init>(Handler.java:141)

2019-04-10 10:51:42.692 27347-27398/? W/System.err:     at com.microsoft.identity.client.PublicClientApplication.getAccounts(PublicClientApplication.java:373)

**Comment by titorodi** [comment]
Thanks @wyber

**Comment by iambmelt** [comment]
@titorodi @wyber ACK - will get a fix into `dev` today
