### ISSUE TITLE
Error on getAccounts - crash with java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/Set; in class Lcom/google/gson/JsonObject;

### ISSUE THREAD

**Issue by chrisriner** [AzureAD/microsoft-authentication-library-for-android#574]
Here is the error from console:
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.southerncompany.southerndirectory, PID: 1433
    java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/Set; in class Lcom/google/gson/JsonObject; or its super classes (declaration of 'com.google.gson.JsonObject' appears in /data/app/com.southerncompany.southerndirectory-60SkmUI5DyzT6cUo4CkmTQ==/split_lib_dependencies_apk.apk)
        at com.microsoft.identity.common.internal.cache.CacheKeyValueDelegate.fromCacheValue(CacheKeyValueDelegate.java:210)
        at com.microsoft.identity.common.internal.cache.AccountCredentialCache.getAccountsWithKeys(AccountCredentialCache.java:167)
        at com.microsoft.identity.common.internal.cache.AccountCredentialCache.getAccounts(AccountCredentialCache.java:184)
        at com.microsoft.identity.common.internal.cache.AccountCredentialCache.getAccountsFilteredBy(AccountCredentialCache.java:205)
        at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.getAccounts(MsalOAuth2TokenCache.java:337)
        at com.microsoft.identity.client.PublicClientApplication.getAccounts(PublicClientApplication.java:330)
        at com.southerncompany.southerndirectory.AuthenticationHelper.hasAccount(AuthenticationHelper.java:52)
        at com.southerncompany.southerndirectory.CalendarActivity.onCreate(CalendarActivity.java:174)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by iambmelt** [comment]
This looks like Gson is missing from the classpath - are you shipping with a version of Gson other than `2.8.4`?

**Comment by chrisriner** [comment]
I did not see that thanks.  I moved the version up to 2.8.4 in the Gradle file and I am good now, thanks again.

**Comment by CodyEddings** [comment]
I get the same error, but it only occurs if I reinstall over an existing installation of my app. If I uninstall the current copy first and then install the exact same app code I don't get this crash. Any idea what would cause this?
