### ISSUE TITLE
MSAL crashed when V1 broker installed

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#601]
We should have the validation for broker call before starting the broker calls.
```java
05-07 15:45:55.664 7686-9373/? E/ApiDispatcher:beginInteractive:  [2019-05-07 22:45:55 - {"thread_id":"6047","correlation_id":"8772ecbc-75be-4955-baf0-060e803749e5"}] Interactive request failed with Exception Android 23
    com.microsoft.identity.common.exception.ClientException
        at com.microsoft.identity.common.internal.broker.MicrosoftAuthClient.connect(MicrosoftAuthClient.java:73)
        at com.microsoft.identity.client.internal.controllers.BrokerMsalController.getBrokerAuthorizationIntent(BrokerMsalController.java:135)
        at com.microsoft.identity.client.internal.controllers.BrokerMsalController.acquireToken(BrokerMsalController.java:98)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:60)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1.run(ApiDispatcher.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by heidijinxujia** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/679
