### ISSUE TITLE
Getting a Service not Registered on Oneplus 6

### ISSUE THREAD

**Issue by rc8marcelo** [AzureAD/microsoft-authentication-library-for-android#633]
I'm using a modified version of the example app and for the past few weeks it worked like a charm but just yesterday it started crashing on me giving me this error:

>2019-06-04 15:22:07.807 20645-20645/com.example.myApp E/AndroidRuntime: FATAL 

> EXCEPTION: main
>     Process: com.example.myApp, PID: 20645
>     java.lang.RuntimeException: Unable to resume activity {com.example.myApp/com.example.myApp.Activities.LoginActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2003, data=Intent { (has extras) }} to activity {com.example.myApp/com.example.myApp.Activities.LoginActivity}: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@f965d28
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3961)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3993)
>         at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
>         at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6940)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
>      Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2003, data=Intent { (has extras) }} to activity {com.example.myApp/com.example.myApp.Activities.LoginActivity}: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@f965d28

I haven't changed anything with the logic of how the example app works. The only thing I did was move the logic of logging in into a separate static class.

The code still works with most phones and even on emulators but I can't get it to work anymore with my Oneplus 6. Has anyone encountered this before?

It's just weird because I haven't changed anything and it started to stop working all of a sudden.

**Comment by Om83** [comment]
Can you please test with the latest version and let us know if this is still happening?

**Comment by iambmelt** [comment]
Closing due to lack of activity
