### ISSUE TITLE
Fatal Crash on clone - Investigating...

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#705]
```
2019-08-07 11:48:57.716 10317-10411/com.microsoft.identity.client.sample.dist E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.microsoft.identity.client.sample.dist, PID: 10317
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.requestAuthorization(BrowserAuthorizationStrategy.java:85)
        at com.microsoft.identity.common.internal.providers.oauth2.OAuth2Strategy.requestAuthorization(OAuth2Strategy.java:95)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.performAuthorizationRequest(LocalMSALController.java:170)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:110)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:57)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$3.run(ApiDispatcher.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/data/app/com.microsoft.identity.client.sample.dist-3CIxllo0fUjKcON01OCPYQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.microsoft.identity.client.sample.dist-3CIxllo0fUjKcON01OCPYQ==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.requestAuthorization(BrowserAuthorizationStrategy.java:85) 
        at com.microsoft.identity.common.internal.providers.oauth2.OAuth2Strategy.requestAuthorization(OAuth2Strategy.java:95) 
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.performAuthorizationRequest(LocalMSALController.java:170) 
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:110) 
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:57) 
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$3.run(ApiDispatcher.java:190) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by iambmelt** [comment]
This was an androidx config issue
