### ISSUE TITLE
No virtual method getAuthorizationStrategy when calling acquireToken (msal:0.3.2-alpha)

### ISSUE THREAD

**Issue by yajenya** [AzureAD/microsoft-authentication-library-for-android#752]
manifest

```
>   <activity
>             android:name="com.microsoft.identity.client.BrowserTabActivity">
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 <data android:scheme="msal<ClientId>"
>                     android:host="auth" />
>             </intent-filter>
>         </activity>
```

config json

```
{
  "client_id" : "client_id",
  "redirect_uri" : "msal<client_id>://auth",
  "authorization_user_agent": "BROWSER_FLOW"
}

```
code in Kotlin

```
init{
 context?.let {
            myApp = PublicClientApplication(
                it,
                R.raw.json_config
            )
        }
}
```

```
myApp?.acquireToken(
                activity,
                arrayOf("User.Read"),
                object : AuthenticationCallback {
}

```
stack trace

   java.lang.NoSuchMethodError: No virtual method getAuthorizationStrategy(Landroid/app/Activity;Lcom/microsoft/identity/common/internal/ui/AuthorizationAgent;Landroid/content/Intent;)Lcom/microsoft/identity/common/internal/providers/oauth2/AuthorizationStrategy; in class Lcom/microsoft/identity/common/internal/ui/AuthorizationStrategyFactory; or its super classes (declaration of 'com.microsoft.identity.common.internal.ui.AuthorizationStrategyFactory' appears in )
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.performAuthorizationRequest(LocalMSALController.java:143)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:101)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:60)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1.run(ApiDispatcher.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by shoatman** [comment]
@kreedula - Is this something that you can investigate?  Looks like an issue related to common?

**Comment by rpdome** [comment]
@yajenya Could you try with the [MSAL v1.0.0](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.0.0) and see if the issue still persists? Thanks!

**Comment by iambmelt** [comment]
Closing due to lack of activity. Please try with `v1.0.x+` and file an issue if the problem persists

**Comment by shakiz** [comment]
Possibly I am facing the same issue. @yajenya  any luck with it?

`
java.lang.NoSuchMethodError: No virtual method getAuthorizationStrategy(Landroid/app/Activity;Lcom/microsoft/identity/common/internal/ui/AuthorizationAgent;Landroid/content/Intent;)Lcom/microsoft/identity/common/internal/providers/oauth2/AuthorizationStrategy; in class Lcom/microsoft/identity/common/internal/ui/AuthorizationStrategyFactory; or its super classes (declaration of 'com.microsoft.identity.common.internal.ui.AuthorizationStrategyFactory' appears in /data/app/com.officework.mam_intune-2/base.apk)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.performAuthorizationRequest(LocalMSALController.java:143)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:101)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:60)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1.run(ApiDispatcher.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
`

**Comment by yajenya** [comment]
Yes, u just need the base lib to match, try changing the basic lib version
