### ISSUE TITLE
Null pointer on Telemetry UIEvent creation in AuthorizationActivity

### ISSUE THREAD

**Issue by kreedula** [AzureAD/microsoft-authentication-library-for-android#786]
**Describe the bug**
Webview hangs on the `AccountPicker` Screen when `Back` is pressed

**Stacktrace**
```
Process: com.microsoft.identity.client.sample.local, PID: 11608
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.identity.client.sample.local/com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.identity.common.internal.ui.AuthorizationAgent.name()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.identity.common.internal.ui.AuthorizationAgent.name()' on a null object reference
        at com.microsoft.identity.common.internal.telemetry.events.UiStartEvent.putUserAgent(UiStartEvent.java:37)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity.onCreate(AuthorizationActivity.java:201)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**To Reproduce**
Sign in to MSAL with any cloud account with the test app
Click `acquireToken` on the test without loginhint.
AccountPicker screen will be displayed by Ests.
Click back button.

**Expected behavior**
Go back to the test app with `user cancel`

**Actual Behavior**
WebView hangs - progress indicator starts but never completes

**Comment by shahzaibj** [comment]
Fixed by #790
