### ISSUE TITLE
RedirectURI should be consistent and consumed ideally from one location

### ISSUE THREAD

**Issue by titorodi** [AzureAD/microsoft-authentication-library-for-android#806]
**Is your feature request related to a problem? Please describe.**
It's inconvenient to get the brokerRedirectUri, which from the getBrokerRedirectAPI is not URL encoded, cannot be URL encoded in the Android manifest, but must be URL encoded in the JSON config, and the make sure I copy it to the AndroidManifest.xml and tweak it as appropriate as I debug with one signature or make an official build with another signature.

Also, the error logged is incorrect JSON (see quoting ' vs " on path:)

2019-10-15 15:16:41.633 30515-30515/com.microsoft.identity.client.sample.dist E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.identity.client.sample.dist, PID: 30515
    java.lang.IllegalStateException: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml 
    
    <activity android:name="com.microsoft.identity.client.BrowserTabActivity">
    	<intent-filter>
    		<action android:name="android.intent.action.VIEW" />
    		<category android:name="android.intent.category.DEFAULT" />
    		<category android:name="android.intent.category.BROWSABLE" />
    		<data
    			android:host="com.microsoft.identity.client.sample.dist"
    			android:path='/4Zbe4iISKyw2VEycARmSsWI9gfc="
    			android:scheme="msauth" />
    	</intent-filter>
    </activity>
    
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:466)
        at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:994)
        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:977)
        at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:71)
        at com.microsoft.identity.client.PublicClientApplication$2.onGetMode(PublicClientApplication.java:863)
        at com.microsoft.identity.client.internal.controllers.BrokerMsalController$1$1.run(BrokerMsalController.java:390)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Describe the solution you'd like**
1: Fix the logging
2: Make URL encoded vs not url encoded both be supported ideally?
3: Make both locations to store the redirect URI at least be consistently URL encoded or not
4: Make the get redirect URI methods return the matching encoding
5: Ideally find a place to enter this in 1 location
6: Simple paradigm for swapping based on build configs would be nice but likely out of scope, do it with Android flavors.

**Describe alternatives you've considered**
Currently we plan on using different JSON configs for different build flavors, and with matching Android Manifests

**Additional context**
People see issues on redirect URIs frequently I think.

**Comment by rpdome** [comment]
Logging fix should go out with the next release (MSAL 1.1).
For the suggestions, I'll put the investigation work item in my backlog.

**Comment by ryanholden8** [comment]
Just ran into this issue with the trailing `=` causing the error. Confused too which Redirect URI I need to register in the Azure portal. The one that ends in `=` of the one that ends in `%3D`

Do you, @negoe,  know if this was fixed somewhere and I am on the wrong MSAL version since this issue was completed?
