### ISSUE TITLE
"returned_account_does_not_match_current_account" error is returned on request for password change

### ISSUE THREAD

**Issue by adenisyuk** [AzureAD/microsoft-authentication-library-for-android#820]
**1st flow**:
1. Log in to the app using B2C signIn/signUp policy (ISingleAccountPublicClientApplication)
2. Launch change password flow using dedicated policy (tried using the same instance of ISingleAccountPublicClientApplication but requesting acquireToken with different authority URL pointing to a change password policy, as well as creating a separate instance of ISingleAccountPublicClientApplication)

ER: AuthenticationCallback.onSuccess is invoked
AR: 1st time AuthenticationCallback.onError with reason "returned_account_does_not_match_current_account" is invoked. 2nd time AuthenticationCallback.onSuccess. (3rd time it's again onError, 4th time it's onSuccess and so on...)

**2nd flow**
After changing password, sign out from the app (ISingleAccountPublicClientApplication.sigOut) and try to log in again.

ER: Log in succeed.
AR: AuthenticationCallback.onError with reason "returned_account_does_not_match_current_account" is invoked. User cannot log in back to the app.

 - Device: Pixel XL, Samsung Note 8
 - Android Version: 10, 9
 - MSAL Version 1.0

**Stacktrace**
```
com.my.app D/SessionManager: handleFailedLogin: returned_account_does_not_match_current_account
    com.microsoft.identity.client.exception.MsalClientException: 
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$4.onSuccess(SingleAccountPublicClientApplication.java:255)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$3$2.run(ApiDispatcher.java:227)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by iambmelt** [comment]
@adenisyuk Due to how to B2C policies are cached internally to MSAL, you'll want to use an `IMultipleAccountPublicClientApplication` for your requests -- we have a sample [here ](https://github.com/Azure-Samples/ms-identity-android-java)with some B2C specific guidance in the readme [here](https://github.com/Azure-Samples/ms-identity-android-java#b2cmodefragment-class).

Please have a look and let me know if this resolves your issue.

**Comment by iambmelt** [comment]
Closing due to inactivity
