### ISSUE TITLE
Is it possible do not throw exception when the package hash not valid because it crash application? In my opinion this not good approach. Facebook just showing message at least.

### ISSUE THREAD

**Issue by SergeyMilevskiy** [AzureAD/microsoft-authentication-library-for-android#879]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shoatman** [comment]
I think this is reasonable.  I'm treating this as an enhancement request for now, but I'm tempted to call it a bug and try to get it addressed opportunistically.

**Comment by rpdome** [comment]
@SergeyMilevskiy would it be acceptable to return this exception in the ApplicationCreatedListener.onError()?

**Comment by SergeyMilevskiy** [comment]
@rpdome For me, all variants are good, instead of a crash application in the development cycle.

**Comment by rpdome** [comment]
@SergeyMilevskiy I've pushed the change to the dev branch. Thanks for the feedback!

**Comment by SergeyMilevskiy** [comment]
`java.lang.IllegalStateException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.verifyRedirectUriWithAppSignature(PublicClientApplicationConfiguration.java:472)
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:518)
        at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:984)
        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:966)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:78)
        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:864)
        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:852)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:180)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)`
Still have a crash in the 'com.microsoft.identity.client:msal:1.2.0' @rpdome

**Comment by rpdome** [comment]
@SergeyMilevskiy I missed one exception there. Sorry. I've pushed a fix and it should go out with the next release.

**Comment by SergeyMilevskiy** [comment]
<img width="1333" alt="Screenshot 2020-02-15 at 11 31 07" src="https://user-images.githubusercontent.com/5111553/74586330-d7cf9780-4fe6-11ea-982f-e70256c626f1.png">
Still crash with version 1.3.0 @rpdome

**Comment by rpdome** [comment]
@SergeyMilevskiy 1.3.0 is technically a 'hotfix' (based on1.2.0-hf1). The fix is in the dev branch, which will be out with the next non-hotfix release.
