### ISSUE TITLE
Hard crash when clientId is null

### ISSUE THREAD

**Issue by rwrife** [AzureAD/microsoft-authentication-library-for-android#890]
When calling PublicClientApplication.create(context, clientid, listener) w/o going through the typical example of providing a config resource file, the app has a hard crash because the OperationalParameters are not being updated with the provided clientId, so line 252 in OperationParameters.java (getClientId().hashCode()) is bombing due to a null exception.  Ideally, at least from my perspective, in the main create() in PublicClientApplication.java after (or during) line 854 (params = OperationParamatersAdapter.createOperationParameters) the clientId and authority should be replaced with any value provided to the method...in addition to sanity checks in OperationParameters.

**Comment by iambmelt** [comment]
@rwrife Can you include a stack trace in your bug report?

**Comment by rwrife** [comment]
2020-01-10 10:24:10.657 10991-11070/com.microsoft.icmmobiledev E/AndroidRuntime: FATAL EXCEPTION: pool-8-thread-1
    Process: com.microsoft.icmmobiledev, PID: 10991
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.microsoft.identity.common.internal.request.OperationParameters.hashCode(OperationParameters.java:252)
        at com.microsoft.identity.common.internal.controllers.BaseCommand.hashCode(BaseCommand.java:123)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
        at android.util.LruCache.get(LruCache.java:117)
        at com.microsoft.identity.common.internal.controllers.CommandResultCache.get(CommandResultCache.java:48)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$1.run(CommandDispatcher.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by iambmelt** [comment]
Thanks @rwrife -- someone will investigate

**Comment by rwrife** [comment]
Seems like https://github.com/rwrife/microsoft-authentication-library-for-android/commit/fb14d00923ad729df4fa17174fa5c0ca0a302a91 would be a quick fix, but I'll defer to someone with more Java knowledge.
