### ISSUE TITLE
[Teams] NPE When adapting CacheRecords for result

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#910]
Reported by Teams, NPE when calling `adapt()` after switch between app ids.

```java
 Process: com.microsoft.skype.teams.dev, PID: 26253
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.identity.common.internal.dto.Credential.getSecret()' on a null object reference
        at com.microsoft.identity.client.AccountAdapter.getIdToken(AccountAdapter.java:321)
        at com.microsoft.identity.client.AccountAdapter.createRootAccounts(AccountAdapter.java:292)
        at com.microsoft.identity.client.AccountAdapter.adapt(AccountAdapter.java:176)
        at com.microsoft.identity.client.AuthenticationResult.<init>(AuthenticationResult.java:49)
        at com.microsoft.identity.client.AuthenticationResultAdapter.adapt(AuthenticationResultAdapter.java:44)
        at com.microsoft.identity.client.PublicClientApplication.postAuthResult(PublicClientApplication.java:1658)
        at com.microsoft.identity.client.PublicClientApplication$9.onSuccess(PublicClientApplication.java:1616)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$3$2.run(ApiDispatcher.java:227)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by iambmelt** [comment]
Closed via #911
