### ISSUE TITLE
Redirect URI doesn't match with the one generated with package name and signature hash.

### ISSUE THREAD

**Issue by kadalcj** [AzureAD/microsoft-authentication-library-for-android#914]
Why the app always crash and saying that the URI doesn't match with the one that showing on the AD? I've been tried to delete it and make a new one and that not helping either? Is this really a problem with the library either the AD or was that my mistake?

Here the Log: 
```
Process: com.ilhamwahyu.testapp, PID: 10038
    java.lang.IllegalStateException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.verifyRedirectUriWithAppSignature(PublicClientApplicationConfiguration.java:453)
        at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:471)
        at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1024)
        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1006)
        at com.microsoft.identity.client.MultipleAccountPublicClientApplication.<init>(MultipleAccountPublicClientApplication.java:72)
        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:889)
        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:870)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:179)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by tulika17** [comment]
I am also facing same issue with MSAL 1.2+ version.

**Comment by kadalcj** [comment]
I thought that only me facing this kind of issue. I can't find anything related to the problem anywhere.

**Comment by shoatman** [comment]
If you check logcat i believe you will see what MSAL expects as input.  Let me know if you don't see this and i'll follow up.

**Comment by iambmelt** [comment]
As an additional tip:
For an APK already pushed to a device, there is a [handy tool provided in the MSAL repo here](https://github.com/AzureAD/microsoft-authentication-library-for-android/tree/dev/package-inspector) which can export the signature hash of an app installed on a device. You can cross reference this value against your configuration in the application and in the Azure Portal.

Here's a screenshot of our test app:
![Screenshot_20191218-143550](https://user-images.githubusercontent.com/990063/71129334-15a96e80-21a4-11ea-8677-899b10d0a6ce.png)

**Comment by kadalcj** [comment]
@shoatman , I tried to look up to the logcat and I can't find any information about the MSAL expected the input. Would you help me with that? Thank you.

@iambmelt , I tried to compile it but somehow it showing me an error. Is the way I open the project is wrong? I look up to the previous issue #846 to generate the signature key, but it kinda confusing because of the specific location of the keytool or keystore. And after seeing that issue, I think maybe it's true that I was giving a wrong Signature Hash. Thanks.

**Comment by shoatman** [comment]
@kadalcj When you get the exception logcat should output what it expects as part of the error message.  Would you mind pasting the logcat output here so that I can ensure that the library is working as expected.

**Comment by shoatman** [comment]
@kadalcj - The easiest way to generate the signature hash is follow the instructions in the Azure Portal using the "new experience".  Open your app registration, Click "Authentication" tab, click new experience, click add Android Platform.  Follow instructions in the portal for generating the signature hash.  It's likely that be default you are using the debug.keystore.  I find it useful to refer to this explicity in gradle using the signing config configuration section.... so that it's clear which keystore is being to used to sign your apk.

**Comment by kadalcj** [comment]
This had to be true all along that my Signature Hash was wrong. I follow the steps on Azure Portal but Android Studio gives me an error log. So I come across [this](https://stackoverflow.com/questions/4388992/key-hash-for-android-facebook-app). There was a code that I can use to Log the Signature Hash directly from the project.

This is the code.
```PackageInfo info;
try {
    info = getPackageManager().getPackageInfo("com.you.name", PackageManager.GET_SIGNATURES);
    for (Signature signature : info.signatures) {
        MessageDigest md;
        md = MessageDigest.getInstance("SHA");
        md.update(signature.toByteArray());
        String something = new String(Base64.encode(md.digest(), 0));
        //String something = new String(Base64.encodeBytes(md.digest()));
        Log.e("hash key", something);
    }
} catch (NameNotFoundException e1) {
    Log.e("name not found", e1.toString());
} catch (NoSuchAlgorithmException e) {
    Log.e("no such an algorithm", e.toString());
} catch (Exception e) {
    Log.e("exception", e.toString());
}
```

Finally, I can make the right redirect_uri.

Thank you everyone for helping me out.

**Comment by tulika17** [comment]
after applying above hash code generation . my application is not crashing but now I am facing another problem while generating token it says "the reply URL specified in the request does not match the reply URLs configured for the application:"

**Comment by kadalcj** [comment]
Is that so? I haven't tested all the functions that I need tho. I just testing for the auth and it work. Will check it soon

**Comment by shoatman** [comment]
@tulika17 - Be sure that your configuration file has the correct value.  Unfortunately the encoding differs between the android manifest and the configuration file.  In the portal you can see examples of both so it's a good idea to take a look.  @hamiltonha do you want to add this to the FAQ?

**Comment by shoatman** [comment]
I'm going to close this issue for now.

**Comment by nfgallimore** [comment]
Facing same issue. +1 for adding to FAQ.

**Comment by shoatman** [comment]
Added here: https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-FAQ

**Comment by nfgallimore** [comment]
I am getting an error saying that the redirect uri in the app does not match the one set in the AAD app registration.

_AndroidManifest.xml_

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="{{PACKAGE_NAME}}">

        ...

        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
                android:host="{{PACKAGE_NAME}}"
                android:path="/{{SIGNATURE_HASH}}"
                android:scheme="msauth" />
        </intent-filter>

        ...

    </manifest>

_msal_config.json_

    {
      "client_id" : "xxxx",
      "authorization_user_agent" : "DEFAULT",
      "redirect_uri" : "{{REDIRECT_URI}}",
      "account_mode" : "SINGLE",
      "authorities" : [
        {
          "type": "AAD",
          "audience": {
            "type": "AzureADMyOrg",
            "tenant_id": "xxx"
          }
        }
      ]
    }

Where **{{PACKAGE_NAME}}** both match, and **{{REDIRECT_URI}}** and **{{SIGNATURE_HASH}}** both match with the ones from AAD. The signature hash is url encoded in the redirect uri, and the signature hash is just base 64.

Here is the error from Logcat:


	2020-02-11 13:20:35.439 21207-21207/com.company.appname E/AndroidRuntime: FATAL EXCEPTION: main
	    Process: com.company.appname, PID: 21207
	    java.lang.IllegalStateException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.
	        at com.microsoft.identity.client.PublicClientApplicationConfiguration.verifyRedirectUriWithAppSignature(PublicClientApplicationConfiguration.java:472)
	        at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:518)
	        at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:984)
	        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:966)
	        at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:78)
	        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:864)
	        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:852)
	        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:180)
	        at android.os.Handler.handleCallback(Handler.java:790)
	        at android.os.Handler.dispatchMessage(Handler.java:99)
	        at android.os.Looper.loop(Looper.java:164)
	        at android.app.ActivityThread.main(ActivityThread.java:6494)
	        at java.lang.reflect.Method.invoke(Native Method)
	        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	2020-02-11 13:20:35.439 21207-21207/com.company.appname E/company DashboardAct: ************ CAUSE OF ERROR ************
	    
	    java.lang.IllegalStateException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.
	        at com.microsoft.identity.client.PublicClientApplicationConfiguration.verifyRedirectUriWithAppSignature(PublicClientApplicationConfiguration.java:472)
	        at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:518)
	        at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:984)
	        at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:966)
	        at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:78)
	        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:864)
	        at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted(PublicClientApplication.java:852)
	        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:180)
	        at android.os.Handler.handleCallback(Handler.java:790)
	        at android.os.Handler.dispatchMessage(Handler.java:99)
	        at android.os.Looper.loop(Looper.java:164)
	        at android.app.ActivityThread.main(ActivityThread.java:6494)
	        at java.lang.reflect.Method.invoke(Native Method)
	        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	    
	    ************ DEVICE INFORMATION ***********
	    Brand: google
	    Device: generic_x86
	    Model: Android SDK built for x86
	    Id: OSM1.180201.031
	    Product: sdk_gphone_x86
	    
	    ************ FIRMWARE ************
	    SDK: 27
	    Release: 8.1.0
	    Incremental: 5455776
	2020-02-11 13:20:35.455 21207-21207/com.company.appname I/Process: Sending signal. PID: 21207 SIG: 9

**Comment by nfgallimore** [comment]
Basically when you are debugging in Android Studio, it will use the debug key found under your user folder/.android/debug.keystore

The default password to get into the `debug.keystore` is `android`, the default password for the key is `android`

So generating your own key/keystore when setting up the app registration will lead to the wrong redirect URI error, since it will use the debug one when running locally.

**Comment by kadalcj** [comment]
I already add the keytool to my path but still that give me the same problem. But somehow I tried it on MacOS and Linux and it was straight give me the correct Signature Hash, not like on the Windows. I wonder tho.

**Comment by nfgallimore** [comment]
@kadalcj Find the binary for it here https://stackoverflow.com/questions/4830253/where-is-the-keytool-application

**Comment by OrionStark** [comment]
Hello, I'm facing the same problem. I've already generate my release hash from my keystore. Then, I build the app. It works well. After I put it on google play, it said "The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal". Please someone help me. I need it ASAP. My client keep asking me for it.

**Comment by rpdome** [comment]
@OrionStark Have you registered the release keystore's signature hash with the portal? 

(Also, could you please open a new issue next time? That way it is easier for us to notice.)

**Comment by DivyaYadav25** [comment]
@OrionStark check this out for the solution [https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/931#issuecomment-648186356](url)

**Comment by OrionStark** [comment]
@DivyaYadav25 Mercy!!!, thanks for the solutions.

**Comment by OrionStark** [comment]
@rpdome Yes, I did. The solutions from @DivyaYadav25 really works.

**Comment by rpdome** [comment]
@OrionStark setting broker_redirect_uri_registered=false means the app will never [use Broker](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth) (and therefore making it pointless for MSAL to verify redirect url against the app's signature hash, which is why it was skipped).

**Comment by OrionStark** [comment]
@rpdome cool. Thanks for the resolutions. BTW, It was the first time for me to create a project using MSAL to access the outlook API. Honestly, it was cool. Thanks anyway.

**Comment by RoarGronmo** [comment]
Is the key point here that APKs generated from AAB (internally) are re-signed at Google and the reason for why MSAL is failing ? Since Google / Android in the long run is abandoning APK in favor of AAB, M$ should fix this situation and give an advice on how to cope with this situation when using AAB.

**Comment by RoarGronmo** [comment]
There are some explanations here:
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/931

RG

**Comment by Ddv0623** [comment]
> @OrionStark setting broker_redirect_uri_registered=false means the app will never [use Broker](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth) (and therefore making it pointless for MSAL to verify redirect url against the app's signature hash, which is why it was skipped).
> 
> That means the user will not get SSO, and I'd advise against it, especially if your app is developed for organizational user.
> 
> I'd suggest printing out signature hash to a log file (or logcat) after you've uploaded the app with Google Play (but don't publish it yet), and compare with the redirect uri you use in the app. See the sample code [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/44b9414f3be233053f441435440db7fbcee312b0/msal/src/main/java/com/microsoft/identity/client/PublicClientApplicationConfiguration.java#L493).

This example is really good.
Now I want to support both debug version, test version in App Center and Google Play version.
which will have different signatureHash.
For using Borker I think it will work as long as I put correct RedirrectUri.

My question is in file AndroidManifest.xml
I create a activity for webview:

```
		<activity
			android:name="com.microsoft.identity.client.BrowserTabActivity"
			android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data
					android:host="my.app.name"
					android:path="/myappsignatureHash"
					android:scheme="msauth" />
			</intent-filter>
		</activity>
```
		
How can I support login with WebView for both 3 cases: debug version, test version in App Center and Google Play version?

**Comment by vermala04** [comment]
He

> APKs generated from AAB

Hello Sir, I have gone through all the comments, I am wondering, if there's any solution for this as of now ?
