### ISSUE TITLE
NullPointerException on LocalMSALController.completeAcquireToken (completeAuthorization(int, int, android.content.Intent))

### ISSUE THREAD

**Issue by ArtyomBasharkevich** [AzureAD/microsoft-authentication-library-for-android#924]
**Describe the bug**
NullPointerException on LocalMSALController.completeAcquireToken (completeAuthorization(int, int, android.content.Intent))

**Smartphone:**
 - Samsung Galaxy S9, Pixel 3
 - Android 9
 - Chrome
 - MSAL Version = 1.1.0-hf1

**Stacktrace**
Samsung

com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken LocalMSALController.java:205
com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.notify CommandDispatcher.java:66
com.microsoft.identity.common.internal.controllers.CommandDispatcher.completeInteractive AuthorizationActivity.java:467
com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity.sendResult AuthorizationActivity.java:326
com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity.access$100 LoadedApk.java:49
com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity$1.onReceive AuthorizationActivity.java:99
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0 Handler.java:1483

Pixel 3:

2020-02-07 15:02:01.918 2787-2787/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ***, PID: 2787
    java.lang.RuntimeException: Error receiving broadcast Intent { act=cancel_interactive_request_action flg=0x10 } in com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity$a@3bae047
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void n0.i.b.a.f.i.c.h.completeAuthorization(int, int, android.content.Intent)' on a null object reference
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken(LocalMSALController.java:7)
        at n0.i.b.a.f.c.d.a(CommandDispatcher.java:10)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity.a(AuthorizationActivity.java:27)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity$a.onReceive(AuthorizationActivity.java:5)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

**To Reproduce**
I received a crash report that the user was trying to create a new account and received a crash after clicking on the "Create Account" button on the Samsung Galaxy S9. Tried to reproduce it on Pixel 3 and Samsung Galaxy S9 but everything was fine. Then just started to click different buttons, open different screens and go back (create account, log in, forgot password). In some clicks the app was crashed with the same issue.

**Comment by ArtyomBasharkevich** [comment]
completeAuthorization(int, int, android.content.Intent) call is started from AuthorizationActivity.completeAuthorization() in 288 line

**Comment by shoatman** [comment]
@ArtyomBasharkevich - We'll try to find a consistent repro using our test app and will report back.

**Comment by ArtyomBasharkevich** [comment]
@shoatman - Ok, I am waiting for the result

**Comment by shahzaibj** [comment]
@ArtyomBasharkevich We have a fix for this issue and I've opened up a PR [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/828). We are currently planning to start cutting an MSAL release some time next week. I'll keep you updated on the status of that.

**Comment by ArtyomBasharkevich** [comment]
@shahzaibj I am glad to hear that

**Comment by shahzaibj** [comment]
@ArtyomBasharkevich This issue has been closed as the above linked PR has merged. I am currently working on getting the release process started (can take 2-4 days to complete). I'll give you an update once the release is available in Maven.

**Comment by shahzaibj** [comment]
@ArtyomBasharkevich The latest release of MSAL with this fix is available on Maven Central. The release version is `1.4.0`
