### ISSUE TITLE
Crash related to start a new B2C journey from the onError callback of another journey

### ISSUE THREAD

**Issue by enirsilvaferraz** [AzureAD/microsoft-authentication-library-for-android#935]
**Describe the bug**
Crash related to start a new B2C journey from the onError callback of another journey

**Smartphone (please complete the following information):**
 - Device: Galaxy S6
 - Android Version: 7
 - MSAL Version: 1.3.0

**Stacktrace**

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=cancel_interactive_request_action flg=0x10 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 } in com.microsoft.identity.common.internal.providers.oauth2.b$a@4a4baeb
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.providers.oauth2.f.a(int, int, android.content.Intent)' on a null object reference
       at com.microsoft.identity.client.internal.controllers.e.a(LocalMSALController.java:205)
       at com.microsoft.identity.common.internal.controllers.j.a(InteractiveTokenCommand.java:66)
       at com.microsoft.identity.common.internal.controllers.e.a(CommandDispatcher.java:468)
       at com.microsoft.identity.common.internal.providers.oauth2.b.a(AuthorizationFragment.java:407)
       at com.microsoft.identity.common.internal.providers.oauth2.b.a(AuthorizationFragment.java:78)
       at com.microsoft.identity.common.internal.providers.oauth2.b$a.onReceive(AuthorizationFragment.java:155)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**To Reproduce**
1. Open a journey
2. This journey call onError calback
3. On this callback start another journey
4. See the error

![image](https://user-images.githubusercontent.com/12086873/74436607-80de8c80-4e45-11ea-8461-60c216026708.png)

Related to https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/920
Related to https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/924

**Comment by shahzaibj** [comment]
@enirsilvaferraz Thanks for reporting the issue. I am able to get a repro for this. Seems to be a threading related issue. I will work on a fix for this, discuss it with the team next week and then we will report back to you. Thanks!

**Comment by shahzaibj** [comment]
@enirsilvaferraz We have a fix for this issue and I've opened up a PR [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/828). We are currently planning to start cutting an MSAL release some time next week. I'll keep you updated on the status of that.

**Comment by shahzaibj** [comment]
@enirsilvaferraz This issue has been closed as the above linked PR has merged. I am currently working on getting the release process started (can take 2-4 days to complete). I'll give you an update once the release is available in Maven.

**Comment by shahzaibj** [comment]
@enirsilvaferraz The latest release of MSAL with this fix is available on Maven Central. The release version is `1.4.0`
