### ISSUE TITLE
Returning error from acquireSilentToken callback

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#960]
Hi!

sometimes when our app perform a call to acquireSilentToken, we get this error... any ideia of what it might be by this exception?

`com.microsoft.identity.client.exception.MsalClientException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.microsoft.identity.client.internal.controllers.g.a(MsalExceptionAdapter.java:51)
        at com.microsoft.identity.client.o$i.a(PublicClientApplication.java:1630)
        at com.microsoft.identity.client.o$i.b(PublicClientApplication.java:1621)
        at com.microsoft.identity.common.internal.controllers.e$b.run(CommandDispatcher.java:184)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.microsoft.identity.common.exception.ClientException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.microsoft.identity.common.internal.controllers.h.a(ExceptionAdapter.java:252)
        at com.microsoft.identity.common.internal.controllers.e.b(CommandDispatcher.java:150)
        at com.microsoft.identity.common.internal.controllers.e.a(CommandDispatcher.java:60)
        at com.microsoft.identity.common.internal.controllers.e$a.run(CommandDispatcher.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$b.a(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.e.a(Gson.java:932)
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:126)
        at com.google.gson.e.a(Gson.java:897)
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:117)
        at com.google.gson.e.a(Gson.java:846)
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:99)
        at com.google.gson.e.a(Gson.java:817)
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:90)
        at d.j.a.a.e.d.d.a(ObjectMapper.java:85)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.g.a(MicrosoftStsOAuth2Strategy.java:510)
        at com.microsoft.identity.common.internal.providers.oauth2.m.b(OAuth2Strategy.java:132)
        at com.microsoft.identity.common.internal.controllers.b.a(BaseController.java:400)
        at com.microsoft.identity.common.internal.controllers.b.a(BaseController.java:234)
        at com.microsoft.identity.client.internal.controllers.e.a(LocalMSALController.java:321)
        at com.microsoft.identity.common.internal.controllers.o.a(TokenCommand.java:70)
        at com.microsoft.identity.common.internal.controllers.o.a(TokenCommand.java:39)
        at com.microsoft.identity.common.internal.controllers.e.b(CommandDispatcher.java:145)
        at com.microsoft.identity.common.internal.controllers.e.a(CommandDispatcher.java:60) 
        at com.microsoft.identity.common.internal.controllers.e$a.run(CommandDispatcher.java:102) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.a.f(JsonReader.java:386)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$b.a(ReflectiveTypeAdapterFactory.java:215)
        at com.google.gson.e.a(Gson.java:932) 
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:126) 
        at com.google.gson.e.a(Gson.java:897) 
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:117) 
        at com.google.gson.e.a(Gson.java:846) 
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:99) 
        at com.google.gson.e.a(Gson.java:817) 
        at com.newrelic.agent.android.instrumentation.GsonInstrumentation.fromJson(GsonInstrumentation.java:90) 
        at d.j.a.a.e.d.d.a(ObjectMapper.java:85) 
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.g.a(MicrosoftStsOAuth2Strategy.java:510) 
        at com.microsoft.identity.common.internal.providers.oauth2.m.b(OAuth2Strategy.java:132) 
        at com.microsoft.identity.common.internal.controllers.b.a(BaseController.java:400) 
        at com.microsoft.identity.common.internal.controllers.b.a(BaseController.java:234) 
        at com.microsoft.identity.client.internal.controllers.e.a(LocalMSALController.java:321) 
        at com.microsoft.identity.common.internal.controllers.o.a(TokenCommand.java:70) 
        at com.microsoft.identity.common.internal.controllers.o.a(TokenCommand.java:39) 
        at com.microsoft.identity.common.internal.controllers.e.b(CommandDispatcher.java:145) 
        at com.microsoft.identity.common.internal.controllers.e.a(CommandDispatcher.java:60) 
        at com.microsoft.identity.common.internal.controllers.e$a.run(CommandDispatcher.java:102) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) `

Best regards,
William

**Comment by abdurahmanadilovic** [comment]
I got the same exception, can't do silent login at all. Initial login is fine, but when access token expires and silent login requested, in a retrofit Authenticator, it fails with this exception every time.

**Comment by slowcar** [comment]
Do you use proguard? It could be an issue with proguard optimizing away the fields needed for Gson to work.
Check if your app works if you disable proguard/minifyenabled.
I added this line in my rules:
-keep class com.microsoft.identity.** { *; }

**Comment by iambmelt** [comment]
This appears to be a proguard issue with Gson

A ProGuard config was added to MSAL in #989 -- if you continue to see this issue I suggest applying the configuration from that PR. Once our next release goes out (around end of April) this config will be shipped with MSAL
